<article class="col-md-10">							
							<!-- Widget ID (each widget will need unique ID)-->
		

							<!-- Widget ID (each widget will need unique ID)-->
							<div class="jarviswidget" id="wid-id-18" >
								<!-- widget options:
									usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">
									
									data-widget-colorbutton="false"	
									data-widget-editbutton="false"
									data-widget-togglebutton="false"
									data-widget-deletebutton="false"
									data-widget-fullscreenbutton="false"
									data-widget-custombutton="false"
									data-widget-collapsed="true" 
									data-widget-sortable="false"
									
								-->
								<header style="color:#fff; background:#274A80;">
									<span class="widget-icon"><i class="glyphicon glyphicon-tasks"></i></span><h2><strong>Student Psychomotor skill rating</strong></h2>			
									
								</header>

								<!-- widget div-->
								<div>
									
									<!-- widget edit box -->
									<div class="jarviswidget-editbox">
										<!-- This area used as dropdown edit box -->
										<input class="form-control" type="text">
										<span class="note"><i class="fa fa-check text-success"></i> Change title to update and save instantly!</span>
										
									</div>
									<!-- end widget edit box -->
									
									<!-- widget content -->
									<div class="widget-body">

										<div class="row">
				
											<div class="col-md-12">
										<div class="widget-body-toolbar">
											
											<div class="row">
												
												<div class="col-xs-9 col-sm-9 col-md-9 col-lg-9">
													
                    							<div class="alert alert-info alert-block">
                                                		<i class="fa-fw fa fa-money font-sm"></i>
                                             
		                                                <?php $sessions=$this->myHelper();?>
		                                                <?php if($sessions):?>
		                                                	<?php foreach ($sessions as $session):?>
		                                                		<?php echo $session['year']['name'].' - '.$session['term']['name'] . ' Academic Session Psychomotor Skill';?>
		                                                	<?php endforeach;?>
		                                            	<?php endif;?>
                                            </div>
												</div>
												<div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 text-right">
													
													<button data-toggle="modal" data-target="#Fee" class="btn btn-success">
														<i class="fa fa-mobile"></i> <span class="hidden-mobile">View Results</span>
													</button>

													
													
												</div>
												
											</div>
											
												

										</div>
										
										<div class="custom-scroll table-responsive" >
											

									<table data-toggle="table" data-show-export="true" data-pagination="true" data-click-to-select="true" data-show-refresh="true" data-show-toggle="true" data-show-columns="true" data-search="true" data-select-item-name="toolbar1" class="table table-bordered table-hover smart-form">
													<thead> 
							<tr>
								<th>photo</th>
								<th>Admission No:</th>
								<th>Name</th>
								<th>Class</th>
								<th>Skill Status</th>
								<th>Action</th>
							</tr>
						</thead>
						<tbody><?php foreach ($students as $student):?>
						 
                        <td style="width:15%;"><img src="<?php echo $this->basePath?>/data/uploads/students/<?php echo $student['s_image'];?>" alt="student pic" style="max-width:30px; border:2px solid #FFF;"></td>
                         <td><?php echo $student['s_admNo'];?></td>
                        <td><?php echo $student['p_fname'].' '.$student['p_lname'].' '.$student['p_mname'];?></td>
                        <td><?php echo $student['c_name'];?></td>
                   		<td><?php $status = $student['r_id'];
                   			if($status){
                   				echo '<label class="txt-color-white  label label-success">Skill set</label>'; 
                   			}
       
                   			else {
                   				echo '<label class="txt-color-white label label-danger">Not set</label>';
                   			} ?>
							</td>
						    <td>
	 <a data-dismiss="modal" data-toggle="modal" data-target="#edit" href="<?php echo $this->url('rating',array('controller' => 'rating','action'=>'rating', 'id'=>$student['s_id']));?>"><button type="button" class="btn btn-xs btn-info"><i class="fa fa-money"></i>Set Skill</button></a>

 <a data-dismiss="modal" data-toggle="modal" data-target="#edit" href="<?php echo $this->url('rating',array('controller' => 'rating','action'=>'view', 'id'=>$student['s_id']));?>"><button type="button" class="btn btn-xs btn-primary"><i class="glyphicon glyphicon-zoom-in"></i> view</button></a>   
							</td>
						</tr>
							
									<?php endforeach;?>
												</tbody>
											</table>
										</div>
										
										
									
									</div>
									
	
									</div>

									
									
								</div>
								<!-- end widget div -->
								
							</div>
							<!-- end widget -->

						</article>
<div class="modal fade" id="itemsx" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            
           
                        </div><!-- /.modal-content -->
                    </div><!-- /.modal-dialog -->
                </div><!-- /.modal -->

<div class="modal fade" id="items" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-md">
        <div class="modal-content">
            
           
                        </div><!-- /.modal-content -->
                    </div><!-- /.modal-dialog -->
                </div><!-- /.modal -->
						<!-- MODAL FOR EDITING ACADEMIC SESSION -->
<div class="modal fade" id="edit" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-md">
        <div class="modal-content">
            
           
                        </div><!-- /.modal-content -->
                    </div><!-- /.modal-dialog -->
                </div><!-- /.modal -->


<!-- END OF MODAL FOR EDITING ACADEMIC SESSION-->
						<!-- end widget div -->
<!-- MODAL FOR EDITING ACADEMIC SESSION -->

 <script>
  /* DO NOT REMOVE : GLOBAL FUNCTIONS!
     *
     * pageSetUp(); WILL CALL THE FOLLOWING FUNCTIONS
     *
     * // activate tooltips
     * $("[rel=tooltip]").tooltip();
     *
     * // activate popovers
     * $("[rel=popover]").popover();
     *
     * // activate popovers with hover states
     * $("[rel=popover-hover]").popover({ trigger: "hover" });
     *
     * // activate inline charts
     * runAllCharts();
     *
     * // setup widgets
     * setup_widgets_desktop();
     *
     * // run form elements
     * runAllForms();
     *
     ********************************
     *
     * pageSetUp() is needed whenever you load a page.
     * It initializes and checks for all basic elements of the page
     * and makes rendering easier.
     *
     */

    pageSetUp();
    
    /*
     * ALL PAGE RELATED SCRIPTS CAN GO BELOW HERE
     * eg alert("my home function");
     * 
     * var pagefunction = function() {
     *   ...
     * }
     * loadScript("js/plugin/_PLUGIN_NAME_.js", pagefunction);
     * 
     * TO LOAD A SCRIPT:
     * var pagefunction = function (){ 
     *  loadScript(".../plugin.js", run_after_loaded);  
     * }
     * 
     * OR you can load chain scripts by doing
     * 
     * loadScript(".../plugin.js", function(){
     *   loadScript("../plugin.js", function(){
     *     ...
     *   })
     * });
     */
    
    // pagefunction
    
    var pagefunction = function() {
        // clears the variable if left blank
    };
    
    // end pagefunction

    // destroy generated instances 
    // pagedestroy is called automatically before loading a new page
    // only usable in AJAX version!

    var pagedestroy = function(){
        
        /*
        Example below:

        $("#calednar").fullCalendar( 'destroy' );
        if (debugState){
            root.console.log("✔ Calendar destroyed");
        } 

        For common instances, such as Jarviswidgets, Google maps, and Datatables, are automatically destroyed through the app.js loadURL mechanic

        */
    }

    // end destroy
    
    // run pagefunction
    pagefunction();

</script>
