<?php

namespace DoctrineORMModule\Proxy\__CG__\Admin\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Student extends \Admin\Entity\Student implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'user', 'person', 'result', 'studentTotal', 'rating', 'section', 'class', 'currentclass', 'admDate', 'admNo', 'status', 'year', 'term', 'image');
        }

        return array('__isInitialized__', 'id', 'user', 'person', 'result', 'studentTotal', 'rating', 'section', 'class', 'currentclass', 'admDate', 'admNo', 'status', 'year', 'term', 'image');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Student $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setStudentTotal(\Admin\Entity\FeeStudentTotal $studentTotal = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStudentTotal', array($studentTotal));

        return parent::setStudentTotal($studentTotal);
    }

    /**
     * {@inheritDoc}
     */
    public function getStudentTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStudentTotal', array());

        return parent::getStudentTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function setRating(\Admin\Entity\Rating $rating = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRating', array($rating));

        return parent::setRating($rating);
    }

    /**
     * {@inheritDoc}
     */
    public function getRating()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRating', array());

        return parent::getRating();
    }

    /**
     * {@inheritDoc}
     */
    public function getResult()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResult', array());

        return parent::getResult();
    }

    /**
     * {@inheritDoc}
     */
    public function setSection(\Admin\Entity\Section $section)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSection', array($section));

        return parent::setSection($section);
    }

    /**
     * {@inheritDoc}
     */
    public function getSection()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSection', array());

        return parent::getSection();
    }

    /**
     * {@inheritDoc}
     */
    public function setSession(\Admin\Entity\Session $session)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSession', array($session));

        return parent::setSession($session);
    }

    /**
     * {@inheritDoc}
     */
    public function getSession()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSession', array());

        return parent::getSession();
    }

    /**
     * {@inheritDoc}
     */
    public function setPerson(\Admin\Entity\Person $person)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPerson', array($person));

        return parent::setPerson($person);
    }

    /**
     * {@inheritDoc}
     */
    public function getPerson()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPerson', array());

        return parent::getPerson();
    }

    /**
     * {@inheritDoc}
     */
    public function setClass(\Admin\Entity\Classes $class)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClass', array($class));

        return parent::setClass($class);
    }

    /**
     * {@inheritDoc}
     */
    public function getClass()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClass', array());

        return parent::getClass();
    }

    /**
     * {@inheritDoc}
     */
    public function setCurrentclass(\Admin\Entity\Classes $currentclass = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurrentclass', array($currentclass));

        return parent::setCurrentclass($currentclass);
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrentclass()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrentclass', array());

        return parent::getCurrentclass();
    }

    /**
     * {@inheritDoc}
     */
    public function setYear(\Admin\Entity\year $year)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setYear', array($year));

        return parent::setYear($year);
    }

    /**
     * {@inheritDoc}
     */
    public function getYear()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getYear', array());

        return parent::getYear();
    }

    /**
     * {@inheritDoc}
     */
    public function setTerm(\Admin\Entity\term $term)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTerm', array($term));

        return parent::setTerm($term);
    }

    /**
     * {@inheritDoc}
     */
    public function getTerm()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTerm', array());

        return parent::getTerm();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdmNo($admNo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdmNo', array($admNo));

        return parent::setAdmNo($admNo);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdmNo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdmNo', array());

        return parent::getAdmNo();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function SetAdmDate($admDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'SetAdmDate', array($admDate));

        return parent::SetAdmDate($admDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdmDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdmDate', array());

        return parent::getAdmDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage($image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage', array($image));

        return parent::setImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', array());

        return parent::getImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(\EduUser\Entity\User $user = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', array($user));

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', array());

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function getArrayCopy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArrayCopy', array());

        return parent::getArrayCopy();
    }

}
