<?php

namespace DoctrineORMModule\Proxy\__CG__\Admin\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Staff extends \Admin\Entity\Staff implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'user', 'fname', 'lname', 'mname', 'sex', 'mobile1', 'mobile2', 'raddress', 'religion', 'dob', 'country', 'state', 'lga', 'nokRel', 'nokName', 'nokMobile', 'image', 'email', 'facebook', 'twitter', 'paddress', 'year', 'level', 'step', 'staffno', 'employdate', 'stafftype', 'qualification', 'clevel', 'cstep', 'status');
        }

        return array('__isInitialized__', 'id', 'user', 'fname', 'lname', 'mname', 'sex', 'mobile1', 'mobile2', 'raddress', 'religion', 'dob', 'country', 'state', 'lga', 'nokRel', 'nokName', 'nokMobile', 'image', 'email', 'facebook', 'twitter', 'paddress', 'year', 'level', 'step', 'staffno', 'employdate', 'stafftype', 'qualification', 'clevel', 'cstep', 'status');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Staff $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(\EduUser\Entity\User $user = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', array($user));

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', array());

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setFname($fname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFname', array($fname));

        return parent::setFname($fname);
    }

    /**
     * {@inheritDoc}
     */
    public function getFname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFname', array());

        return parent::getFname();
    }

    /**
     * {@inheritDoc}
     */
    public function setReligion($religion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReligion', array($religion));

        return parent::setReligion($religion);
    }

    /**
     * {@inheritDoc}
     */
    public function getReligion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReligion', array());

        return parent::getReligion();
    }

    /**
     * {@inheritDoc}
     */
    public function SetDob($dob)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'SetDob', array($dob));

        return parent::SetDob($dob);
    }

    /**
     * {@inheritDoc}
     */
    public function getDob()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDob', array());

        return parent::getDob();
    }

    /**
     * {@inheritDoc}
     */
    public function setFacebook($facebook)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFacebook', array($facebook));

        return parent::setFacebook($facebook);
    }

    /**
     * {@inheritDoc}
     */
    public function getFacebook()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFacebook', array());

        return parent::getFacebook();
    }

    /**
     * {@inheritDoc}
     */
    public function setTwitter($twitter)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTwitter', array($twitter));

        return parent::setTwitter($twitter);
    }

    /**
     * {@inheritDoc}
     */
    public function getTwitter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTwitter', array());

        return parent::getTwitter();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setLname($lname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLname', array($lname));

        return parent::setLname($lname);
    }

    /**
     * {@inheritDoc}
     */
    public function getLname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLname', array());

        return parent::getLname();
    }

    /**
     * {@inheritDoc}
     */
    public function setMname($mname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMname', array($mname));

        return parent::setMname($mname);
    }

    /**
     * {@inheritDoc}
     */
    public function getMname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMname', array());

        return parent::getMname();
    }

    /**
     * {@inheritDoc}
     */
    public function setSex($sex)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSex', array($sex));

        return parent::setSex($sex);
    }

    /**
     * {@inheritDoc}
     */
    public function getSex()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSex', array());

        return parent::getSex();
    }

    /**
     * {@inheritDoc}
     */
    public function setMobile1($mobile1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMobile1', array($mobile1));

        return parent::setMobile1($mobile1);
    }

    /**
     * {@inheritDoc}
     */
    public function getMobile1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMobile1', array());

        return parent::getMobile1();
    }

    /**
     * {@inheritDoc}
     */
    public function setMobile2($mobile2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMobile2', array($mobile2));

        return parent::setMobile2($mobile2);
    }

    /**
     * {@inheritDoc}
     */
    public function getMobile2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMobile2', array());

        return parent::getMobile2();
    }

    /**
     * {@inheritDoc}
     */
    public function setRaddress($raddress)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRaddress', array($raddress));

        return parent::setRaddress($raddress);
    }

    /**
     * {@inheritDoc}
     */
    public function getRaddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRaddress', array());

        return parent::getRaddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaddress($paddress)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaddress', array($paddress));

        return parent::setPaddress($paddress);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaddress', array());

        return parent::getPaddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setCountry(\Admin\Entity\Country $country)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCountry', array($country));

        return parent::setCountry($country);
    }

    /**
     * {@inheritDoc}
     */
    public function getCountry()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCountry', array());

        return parent::getCountry();
    }

    /**
     * {@inheritDoc}
     */
    public function setState(\Admin\Entity\State $state)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setState', array($state));

        return parent::setState($state);
    }

    /**
     * {@inheritDoc}
     */
    public function getState()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getState', array());

        return parent::getState();
    }

    /**
     * {@inheritDoc}
     */
    public function setLga(\Admin\Entity\Lga $lga)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLga', array($lga));

        return parent::setLga($lga);
    }

    /**
     * {@inheritDoc}
     */
    public function getLga()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLga', array());

        return parent::getLga();
    }

    /**
     * {@inheritDoc}
     */
    public function setNokRel($nokRel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNokRel', array($nokRel));

        return parent::setNokRel($nokRel);
    }

    /**
     * {@inheritDoc}
     */
    public function getNokRel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNokRel', array());

        return parent::getNokRel();
    }

    /**
     * {@inheritDoc}
     */
    public function setNokName($nokName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNokName', array($nokName));

        return parent::setNokName($nokName);
    }

    /**
     * {@inheritDoc}
     */
    public function getNokName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNokName', array());

        return parent::getNokName();
    }

    /**
     * {@inheritDoc}
     */
    public function setNokMobile($nokMobile)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNokMobile', array($nokMobile));

        return parent::setNokMobile($nokMobile);
    }

    /**
     * {@inheritDoc}
     */
    public function getNokMobile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNokMobile', array());

        return parent::getNokMobile();
    }

    /**
     * {@inheritDoc}
     */
    public function setYear(\Admin\Entity\year $year)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setYear', array($year));

        return parent::setYear($year);
    }

    /**
     * {@inheritDoc}
     */
    public function getYear()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getYear', array());

        return parent::getYear();
    }

    /**
     * {@inheritDoc}
     */
    public function setStaff(\Admin\Entity\Staff $staff)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStaff', array($staff));

        return parent::setStaff($staff);
    }

    /**
     * {@inheritDoc}
     */
    public function getStaff()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStaff', array());

        return parent::getStaff();
    }

    /**
     * {@inheritDoc}
     */
    public function setStaffType(\Admin\Entity\StaffType $stafftype = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStaffType', array($stafftype));

        return parent::setStaffType($stafftype);
    }

    /**
     * {@inheritDoc}
     */
    public function getStaffType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStaffType', array());

        return parent::getStaffType();
    }

    /**
     * {@inheritDoc}
     */
    public function setLevel(\Admin\Entity\Level $level)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLevel', array($level));

        return parent::setLevel($level);
    }

    /**
     * {@inheritDoc}
     */
    public function getLevel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLevel', array());

        return parent::getLevel();
    }

    /**
     * {@inheritDoc}
     */
    public function setStep(\Admin\Entity\Step $step)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStep', array($step));

        return parent::setStep($step);
    }

    /**
     * {@inheritDoc}
     */
    public function getStep()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStep', array());

        return parent::getStep();
    }

    /**
     * {@inheritDoc}
     */
    public function setQualification($qualification)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQualification', array($qualification));

        return parent::setQualification($qualification);
    }

    /**
     * {@inheritDoc}
     */
    public function getQualification()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQualification', array());

        return parent::getQualification();
    }

    /**
     * {@inheritDoc}
     */
    public function setStaffNo($staffno)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStaffNo', array($staffno));

        return parent::setStaffNo($staffno);
    }

    /**
     * {@inheritDoc}
     */
    public function getStaffNo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStaffNo', array());

        return parent::getStaffNo();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmployDate($employdate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmployDate', array($employdate));

        return parent::setEmployDate($employdate);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmployDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmployDate', array());

        return parent::getEmployDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setClevel(\Admin\Entity\Level $clevel = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClevel', array($clevel));

        return parent::setClevel($clevel);
    }

    /**
     * {@inheritDoc}
     */
    public function getClevel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClevel', array());

        return parent::getClevel();
    }

    /**
     * {@inheritDoc}
     */
    public function setCstep(\Admin\Entity\Step $cstep = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCstep', array($cstep));

        return parent::setCstep($cstep);
    }

    /**
     * {@inheritDoc}
     */
    public function getCstep()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCstep', array());

        return parent::getCstep();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage($image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage', array($image));

        return parent::setImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', array());

        return parent::getImage();
    }

    /**
     * {@inheritDoc}
     */
    public function getArrayCopy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArrayCopy', array());

        return parent::getArrayCopy();
    }

}
