<div class="row">
<div class="col-sm-12">


<div class="well well well-sm well-light">
    <div style="border-color:#B9CEEC; border-width:2px 0px 0px; margin-top:8px; margin-bottom:15px;">
        <div class="alert alert-info alert-block">
                                                <button class="close" data-dismiss="alert">
                                                    ×
                                                </button><i class="fa-fw fa fa-info"></i>
                                                <a  data-dismiss="modal" data-toggle="modal" data-target="#itemsx" href="<?php echo $this->url('grade',array('controller' => 'grade','action'=>'editgradeformat', 'id' => $this->id));?>"><button type="button" class="btn btn-xs btn-warning"><i class="fa fa-pencil-square-o"></i> <span class="hidden-mobile">Edit</span></button></a> 
                                            </div>
        </div>
 
        <div class="row">
            <div class="col col-sm-12">

                      <table class="table table-bordered">
                        
                            <tr>
                                <th>Grade</th>
                                <th>Start Range</th>
                                <th>End Range</th>
                                <th>Remark</th>
                           </tr>
                           <?php if($grades):?>
                       <?php foreach ($grades as $grade) : ?>
                        <tbody>
                            <tr>
                       <td><?php echo $grade->getGrade();?></td>
                       <td><?php echo $grade->getstartRange();?></td>
                       <td><?php echo $grade->getendRange();?></td>
                       <td><?php echo $grade->getDescription();?></td>                                          
                           </tr>
                    <?php endforeach; ?>
                  <?php endif;?>
                        </tbody>
                    </table>

            </div>

                                                 

        </div>
</div>
</div>
</div>