<article class="col-md-9">							
							<!-- Widget ID (each widget will need unique ID)-->
		

							<!-- Widget ID (each widget will need unique ID)-->
							<div class="jarviswidget" id="wid-id-18" >
								<!-- widget options:
									usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">
									
									data-widget-colorbutton="false"	
									data-widget-editbutton="false"
									data-widget-togglebutton="false"
									data-widget-deletebutton="false"
									data-widget-fullscreenbutton="false"
									data-widget-custombutton="false"
									data-widget-collapsed="true" 
									data-widget-sortable="false"
									
								-->
								<header style="color:#fff; background:#274A80;">
									<span class="widget-icon"><i class="glyphicon glyphicon-tasks"></i></span><h2><strong>Grading Configuration</strong></h2>			
									
								</header>

								<!-- widget div-->
								<div>
									
									<!-- widget edit box -->
									<div class="jarviswidget-editbox">
										<!-- This area used as dropdown edit box -->
										<input class="form-control" type="text">
										<span class="note"><i class="fa fa-check text-success"></i> Change title to update and save instantly!</span>
										
									</div>
									<!-- end widget edit box -->
									
									<!-- widget content -->
									<div class="widget-body">

										<div class="row">
				
											<div class="col-md-12">
										<div class="widget-body-toolbar">
											
											<div class="row">
												
												<div class="col-xs-9 col-sm-5 col-md-5 col-lg-5">
													
                    
        												<div class="input-group">
														<span class="input-group-addon"><i class="fa fa-search"></i></span>
														<input class="form-control" id="searchTerm" value="" placeholder="Filter" type="text" name="searchTerm"/>
													</div>
												</div>
												<div class="col-xs-3 col-sm-7 col-md-7 col-lg-7 text-right">
													
													<button data-toggle="modal" data-target="#Fee" class="btn btn-success">
														<i class="fa fa-plus"></i> <span class="hidden-mobile">New Setup</span>
													</button>

													
													
												</div>
												
											</div>
											
												

										</div>
										
										<div class="custom-scroll table-responsive" style="height:200px; overflow-y: scroll;">
											

																	<table class="table table-bordered">
													<thead> 
							<tr>
								<th>Name</th>
								<th>Description</th>
								<th>Action </th>
							</tr>
						</thead>
						<tbody><?php if($formats):?>
					<?php foreach ($formats as $format) : ?>
							<tr>
							<td><a data-dismiss="modal"  data-toggle="modal" data-target="#items" href="<?php echo $this->url('grade',array('controller' => 'grade','action'=>'grades', 'id' => $format->getid()));?>"><?php echo $this->escapeHtml($format->getName());?></a></td>
							<td><?php echo $this->escapeHtml($format->getDescription());?></td>
						    <td>
 <a  data-dismiss="modal" data-toggle="modal" data-target="#itemsx" href="<?php echo $this->url('grade',array('controller' => 'grade','action'=>'addgrades', 'id' => $format->getid()));?>"><button type="button" class="btn btn-xs btn-info"><i class="fa fa-plus"></i> <span class="hidden-mobile">Add grades</span></button></a>  

 <a  data-dismiss="modal" data-toggle="modal" data-target="#itemsx" href="<?php echo $this->url('grade',array('controller' => 'grade','action'=>'editgradeformat', 'id' => $format->getid()));?>"><button type="button" class="btn btn-xs btn-warning"><i class="fa fa-pencil-square-o"></i> <span class="hidden-mobile">Edit format</span></button></a>  

					 

<a id="conf" href="<?php echo $this->url('grade',array('controller' => 'grade','action'=>'deletegradeformat', 'id' => $format->getid()));?>"onclick="return confirm('Deleting this format will delete grades defines in it ?')"><button type="button" class="btn btn-xs btn-danger">
  <i class="glyphicon glyphicon-trash"></i> <span class="hidden-mobile">Delete format</span></button></a>
							</td>
							</tr>
							
						<?php endforeach; ?>
													
								<?php endif;?>					
					
												</tbody>
											</table>
										</div>
										
										
									
									</div>
									
	
									</div>

									
									
								</div>
								<!-- end widget div -->
								
							</div>
							<!-- end widget -->

						</article>
<div class="modal fade" id="itemsx" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content" style="width:900px;">
            
           
                        </div><!-- /.modal-content -->
                    </div><!-- /.modal-dialog -->
                </div><!-- /.modal -->

<div class="modal fade" id="items" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content" style="width:400px;">
            
           
                        </div><!-- /.modal-content -->
                    </div><!-- /.modal-dialog -->
                </div><!-- /.modal -->
						<!-- MODAL FOR EDITING ACADEMIC SESSION -->
<div class="modal fade" id="edit" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content" style="width:900px;">
            
           
                        </div><!-- /.modal-content -->
                    </div><!-- /.modal-dialog -->
                </div><!-- /.modal -->


<!-- END OF MODAL FOR EDITING ACADEMIC SESSION-->
						<!-- end widget div -->
<!-- MODAL FOR EDITING ACADEMIC SESSION -->
<div class="modal fade" id="Fee" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
									&times;
				</button>
				<h4 class="modal-title" id="myModalLabel">Grade Setup Definition</h4>
			</div>
				<div class="modal-body">
				<?php $form = $this->form;
				$form->setAttribute('action', $this->url('grade',array('action'=> 'gradeformat','controller' => 'grade')));
				$form->prepare(); ?>
				<?php echo $this->form()->openTag($form); ?>
					
				

					<div class="row">
						<section class="col col-4">
							<label class="select">
			<?php echo $this->formInput($form->get('name')); ?>
							</label>
						</section>
					
						<section class="col col-8"><label class="input">
			<?php echo $this->formInput($form->get('description')); ?></label>
						</section>
				
							

					</div>
												  									  				
			   </div>

			<div class="modal-footer">
			<button type="button" class="btn btn-default" data-dismiss="modal">
									Cancel
			</button>
			<?php echo $this->formRow($form->get('submit')); ?>
								<?php echo $this->form()->closeTag(); ?>
			</div>
						</div><!-- /.modal-content -->
					</div><!-- /.modal-dialog -->
				</div><!-- /.modal -->
<!-- END OF MODAL FOR EDITING ACADEMIC SESSION-->

 <script>
  /* DO NOT REMOVE : GLOBAL FUNCTIONS!
     *
     * pageSetUp(); WILL CALL THE FOLLOWING FUNCTIONS
     *
     * // activate tooltips
     * $("[rel=tooltip]").tooltip();
     *
     * // activate popovers
     * $("[rel=popover]").popover();
     *
     * // activate popovers with hover states
     * $("[rel=popover-hover]").popover({ trigger: "hover" });
     *
     * // activate inline charts
     * runAllCharts();
     *
     * // setup widgets
     * setup_widgets_desktop();
     *
     * // run form elements
     * runAllForms();
     *
     ********************************
     *
     * pageSetUp() is needed whenever you load a page.
     * It initializes and checks for all basic elements of the page
     * and makes rendering easier.
     *
     */

    pageSetUp();
    
    /*
     * ALL PAGE RELATED SCRIPTS CAN GO BELOW HERE
     * eg alert("my home function");
     * 
     * var pagefunction = function() {
     *   ...
     * }
     * loadScript("js/plugin/_PLUGIN_NAME_.js", pagefunction);
     * 
     * TO LOAD A SCRIPT:
     * var pagefunction = function (){ 
     *  loadScript(".../plugin.js", run_after_loaded);  
     * }
     * 
     * OR you can load chain scripts by doing
     * 
     * loadScript(".../plugin.js", function(){
     *   loadScript("../plugin.js", function(){
     *     ...
     *   })
     * });
     */
    
    // pagefunction
    
    var pagefunction = function() {
        // clears the variable if left blank
    };
    
    // end pagefunction

    // destroy generated instances 
    // pagedestroy is called automatically before loading a new page
    // only usable in AJAX version!

    var pagedestroy = function(){
        
        /*
        Example below:

        $("#calednar").fullCalendar( 'destroy' );
        if (debugState){
            root.console.log("✔ Calendar destroyed");
        } 

        For common instances, such as Jarviswidgets, Google maps, and Datatables, are automatically destroyed through the app.js loadURL mechanic

        */
    }

    // end destroy
    
    // run pagefunction
    pagefunction();

</script>
