<article>
                                        
                          <?php
if (!$this->enableRegistration) {
    print "Registration is disabled";
    return;
}
$form = $this->registerForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/register'));
$form->setAttribute('method', 'post');
$form->setAttribute('class', 'lockscreen animated flipInY smart-form client-form');
$form->setAttribute('id', 'smart-form-register');
?>

<?php echo $this->form()->openTag($form) ?>
<div class="logo">
                    <h1 class="semi-bold"><img src="<?php echo $this->basePath('../img/edlogo.png') ?>" /> </strong>Edusoft</strong> School Management System</h1>
                </div>
                <div>
                    <img src="<?php echo $this->basePath('../img/brn.png') ?>" alt="" width="120" height="120" />
                    <div>
                        <div><h1>Registration Form</h1></div> 
                               
                                    <section class="col-12">
                                        <label class="input"> <i class="icon-append fa fa-envelope"></i>
                                            <?php echo $this->formInput($form->get('email'));?>
                                              <?php echo $this->formElementErrors($form->get('email'))."\n";?>
                                            <b class="tooltip tooltip-bottom-right">Needed to verify your account</b> </label>
                                    </section>

                                     <section class="col-12">
                                        <label class="input"> <i class="icon-append fa fa-envelope"></i>
                                            <?php echo $this->formInput($form->get('username'));?>
                                              <?php echo $this->formElementErrors($form->get('username'))."\n";?>
                                            <b class="tooltip tooltip-bottom-right">Needed to verify your account</b> </label>
                                    </section>

                                    <section class="col-12">
                                        <label class="input"> <i class="icon-append fa fa-lock"></i>
                                            <?php echo $this->formInput($form->get('password'));?>
                                              <?php echo $this->formElementErrors($form->get('password'))."\n";?>
                                            <b class="tooltip tooltip-bottom-right">Don't forget your password</b> </label>
                                    </section>

                                    <section class="col-12">
                                        <label class="input"> <i class="icon-append fa fa-lock"></i>
                                            <?php echo $this->formInput($form->get('passwordVerify'));?>
                                              <?php echo $this->formElementErrors($form->get('passwordVerify'))."\n";?>
                                            <b class="tooltip tooltip-bottom-right">Don't forget your password</b> </label>
                                    </section>

                                <section>
                                    <?php echo $this->formButton($form->get('submit'));?> or <a href="<?php echo $this->url('zfcuser/login');?>">Sign in</a>
                                </section>

                                                          
         </div>

                </div>
                <p class="font-xs margin-top-5">
                    Copyright Edusoft 2014-2020.

                </p>
     <?php echo $this->form()->closeTag(); ?>
</article>
                <!-- Modal -->
        <script type="text/javascript">
            runAllForms();
            
            // Model i agree button
            
            
            // Validation
            $(function() {
                // Validation
                $("#smart-form-register").validate({

                    // Rules for form validation
                    rules : {
                        
                        email : {
                            required : true,
                            email : true
                        },
                        password : {
                            required : true,
                            minlength : 6,
                            maxlength : 20
                        },
                        passwordVerify : {
                            required : true,
                            minlength : 6,
                            maxlength : 20,
                            equalTo : '#password'
                        },
                        
                    },

                    // Messages for form validation
                    messages : {
                        
                        email : {
                            required : 'Please enter your email address',
                            email : 'Please enter a VALID email address'
                        },
                        password : {
                            required : 'Please enter your password'
                        },
                        passwordVerify : {
                            required : 'Please enter your password one more time',
                            equalTo : 'Please enter the same password as above'
                        },
                        
                    },

                    

                    // Do not change code below
                    errorPlacement : function(error, element) {
                        error.insertAfter(element.parent());
                    }
                });

            });
        </script>