<?php /* @var $user \ZfcUserCrud\Entity\User */?>
<article class="col-md-12">                         
                            <!-- Widget ID (each widget will need unique ID)-->
              <!-- Widget ID (each widget will need unique ID)-->
                            <div class="jarviswidget" id="wid-id-18" >
                            
                            
                                <header style="color:#fff; background:#274A80;">
                                    <span class="widget-icon"><i class="glyphicon glyphicon-tasks"></i></span><h2><strong>System Users</strong></h2>           
                                    
                                </header>

                                <!-- widget div-->
                                <div>
                                    
                                    <!-- widget edit box -->
                                    <div class="jarviswidget-editbox">
                                        <!-- This area used as dropdown edit box -->
                                        <input class="form-control" type="text">
                                        <span class="note"><i class="fa fa-check text-success"></i> Change title to update and save instantly!</span>
                                        
                                    </div>
                                    <!-- end widget edit box -->
                                    
                                    <!-- widget content -->
                                    <div class="widget-body">

                                        <div class="row">
                
                                            <div class="col-md-12">
                                        <div class="widget-body-toolbar">
                                            
                                            <div class="row">
                                                
                                                <div class="col-xs-9 col-sm-5 col-md-5 col-lg-5">
                                                       <form class="form-inline" role="form" method="post">
                                                          <div class="form-group">
                                                            <div class="input-group">
                                                            <input type="text" class="form-control" id="searchTerm" 
                                                                   value="<?php echo $searchTerm; ?>"
                                                                   placeholder="<?php echo $this->translate('Name');?>" 
                                                                   name="searchTerm"/>
                                                            <div class="input-group-btn">
                                                                <button type="submit" class="btn btn-primary">
                                                                    <i class="glyphicon glyphicon-search"></i>
                                                                 </button>
                                                            </div>
                                                        </div>
                                                        </div>

                                                    </form>
                                                </div>
                                                <div class="col-xs-3 col-sm-7 col-md-7 col-lg-7 text-right">
                                                    
                                                    <a data-toggle="modal" data-target="#edit" href="<?php echo $this->url('zfc-user-crud', array('action' => 'new')); ?>"class="btn btn-info">
                                                        <i class="fa fa-plus"></i> <span class="hidden-mobile">New User</span>
                                                    </a>

                                                    
                                                </div>
                                                
                                            </div>
                                            
                                                

                                        </div>
                                        
                                        <div class="custom-scroll table-responsive">
                                            

                                            <table class="table table-bordered table-hover table-responsive table-striped">
                                                    <thead> 
                            <tr>
                                <th>Name</th>
                                <th>Username</th>
                                <th>Email</th>
                                <th>Edit</th>
                                <th>Remove</th>
                               
                            </tr>
                        </thead>
                        <tbody><?php if($users):?>
                    <?php foreach ($users as $user) : ?>
                        <tr>
                            <td> <?php echo $user->getDisplayName();?></td>
                            <td><?php echo $user->getUsername();?></td>
                            <td><?php echo $user->getEmail();?></td>
                           
                            <td>
 <a  data-toggle="modal" data-target="#edit" href="<?php echo $this->url('zfc-user-crud', array('action' => 'edit','id' => $user->getId()));?>"><button type="button" class="btn btn-xs btn-info"><i class="fa fa-pencil-square-o"></i> Edit</button></a>  
                            </td>
                            <td>
<a id="conf" href="<?php echo $this->url('zfc-user-crud', array('action' => 'remove','id' => $user->getId()));?>" onclick="return confirm('<?php echo $this->translate('Confirm to remove this item');?>')"><button type="button" class="btn btn-xs btn-danger">
  <i class="glyphicon glyphicon-trash"></i> Remove</button></a>
                            </td>
                        </tr>
                            
                        <?php endforeach; ?>
                        <?php endif;?>                              
                                                </tbody>
                                            </table>
                                        </div>
                                        
                                        
                                    
                                    </div>
                                    
    
                                    </div>

                                    
 <?php echo $this->paginationControl($users, 'Sliding', 'partial/paginator', array('route' => 'zfc-user-crud'));?>   
                                </div>
                                <!-- end widget div -->
                                
                            </div>
                            <!-- end widget -->

                        </article>
<div class="modal fade" id="itemsx" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content" style="width:900px;">
            
           
                        </div><!-- /.modal-content -->
                    </div><!-- /.modal-dialog -->
                </div><!-- /.modal -->

<div class="modal fade" id="items" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content" style="width:400px;">
            
           
                        </div><!-- /.modal-content -->
                    </div><!-- /.modal-dialog -->
                </div><!-- /.modal -->
                        <!-- MODAL FOR EDITING ACADEMIC SESSION -->
<div class="modal fade" id="edit" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content" style="width:900px;">
            
           
                        </div><!-- /.modal-content -->
                    </div><!-- /.modal-dialog -->
                </div><!-- /.modal -->



<script>
  /* DO NOT REMOVE : GLOBAL FUNCTIONS!
     *
     * pageSetUp(); WILL CALL THE FOLLOWING FUNCTIONS
     *
     * // activate tooltips
     * $("[rel=tooltip]").tooltip();
     *
     * // activate popovers
     * $("[rel=popover]").popover();
     *
     * // activate popovers with hover states
     * $("[rel=popover-hover]").popover({ trigger: "hover" });
     *
     * // activate inline charts
     * runAllCharts();
     *
     * // setup widgets
     * setup_widgets_desktop();
     *
     * // run form elements
     * runAllForms();
     *
     ********************************
     *
     * pageSetUp() is needed whenever you load a page.
     * It initializes and checks for all basic elements of the page
     * and makes rendering easier.
     *
     */

    pageSetUp();
    
    /*
     * ALL PAGE RELATED SCRIPTS CAN GO BELOW HERE
     * eg alert("my home function");
     * 
     * var pagefunction = function() {
     *   ...
     * }
     * loadScript("js/plugin/_PLUGIN_NAME_.js", pagefunction);
     * 
     * TO LOAD A SCRIPT:
     * var pagefunction = function (){ 
     *  loadScript(".../plugin.js", run_after_loaded);  
     * }
     * 
     * OR you can load chain scripts by doing
     * 
     * loadScript(".../plugin.js", function(){
     *   loadScript("../plugin.js", function(){
     *     ...
     *   })
     * });
     */
    
    // pagefunction
    
    var pagefunction = function() {
        // clears the variable if left blank
    };
    
    // end pagefunction

    // destroy generated instances 
    // pagedestroy is called automatically before loading a new page
    // only usable in AJAX version!

    var pagedestroy = function(){
        
        /*
        Example below:

        $("#calednar").fullCalendar( 'destroy' );
        if (debugState){
            root.console.log("✔ Calendar destroyed");
        } 

        For common instances, such as Jarviswidgets, Google maps, and Datatables, are automatically destroyed through the app.js loadURL mechanic

        */
    }

    // end destroy
    
    // run pagefunction
    pagefunction();

</script>