<?php echo $this->headScript()
            
            ->appendFile($this->basePath() . '/js/jquery-2.1.1.min.js')
            ->appendFile($this->basePath() . '/js/jquery-ui-1.10.3.min.js')
            ->appendFile($this->basePath() . '/js/app.config.js')
            ->appendFile($this->basePath() . '/js/bootstrap.min.js')
            ->appendFile($this->basePath() . '/js/notification/SmartNotification.min.js')
           // ->prependFile($this->basePath() . '/js/plugin/jquery-touch/jquery.ui.touch-punch.min.js')
            ->appendFile($this->basePath() . '/js/smartwidgets/jarvis.widget.min.js')
            ->appendFile($this->basePath() . '/js/plugin/masked-input/jquery.maskedinput.min.js')
            ->appendFile($this->basePath() . '/js/plugin/select2/select2.min.js')
            ->appendFile($this->basePath() . '/js/plugin/bootstrap-slider/bootstrap-slider.min.js')
            
            ->appendFile($this->basePath() . '/js/plugin/msie-fix/jquery.mb.browser.min.js')
            ->appendFile($this->basePath() . '/js/plugin/msie-fix/jquery.mb.browser.min.js')
            ->appendFile($this->basePath() . '/js/plugin/pace/pace.min.js')
           
        	->appendFile($this->basePath() . '/js/demo.min.js')
        	 ->appendFile($this->basePath() . '/js/app.min.js')
            ->appendFile($this->basePath() . '/js/academicsession/formedit.js')

         //  ->prependFile('http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js', 'text/javascript')
         //        ->prependFile('http://ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js', 'text/javascript')
                //    ->appendFile('/jqGrid/js/i18n/grid.locale-en.js', 'text/javascript')
                //    ->appendFile('/jqGrid/plugins/ui.multiselect.js', 'text/javascript')
                  ->appendFile($this->basePath() .'/js/plugin/jquery-validate/jquery.validate.min.js');?>


	<article class="col-xs-12 col-sm-12 col-md-8 col-lg-6">
			

							<!-- Widget ID (each widget will need unique ID)-->
							<div class="jarviswidget" id="wid-id-0">
								<!-- widget options:
									usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">
									
									data-widget-colorbutton="false"	
									data-widget-editbutton="false"
									data-widget-togglebutton="false"
									data-widget-deletebutton="false"
									data-widget-fullscreenbutton="false"
									data-widget-custombutton="false"
									data-widget-collapsed="true" 
									data-widget-sortable="false"
									
								-->
								<header>
									<h2>Add class</h2>				
									
								</header>

								<!-- widget div-->
								<div>
									
									<!-- widget edit box -->
									<div class="jarviswidget-editbox">
										<!-- This area used as dropdown edit box -->
										
										
									</div>
									<!-- end widget edit box -->
									
									<!-- widget content -->
									<div class="widget-body">
										<?php $formclasses = $this->formclasses;
				$formclasses->setAttribute('action', $this->url('admin/default',array('action'=> 'addclasses','controller' => 'section')));
				 $formclasses->setAttribute('role', 'form-horizontal');
        		$formclasses->setAttribute('class', 'form-inline');
        		$formclasses->setAttribute('id', 'classes');
				$formclasses->prepare(); ?>
				<?php echo $this->form()->openTag($formclasses);?>

										<div class="row"> 
				                        	<div class="col-xs-5 col-sm-5 col-md-5 col-lg-5">
				                            <?php echo $this->formElementErrors($formclasses->get('name')); ?>
				                            <?php echo $this->formInput($formclasses->get('name')); ?>  
				                        	</div>

				                       		 <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
				                        	<?php echo $this->formElementErrors($formclasses->get('section')); ?>
				                        	<?php echo $this->formSelect($formclasses->get('section')); ?>    
				                        	</div>
				                        	<div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 text-right">  
				                        	<?php echo $this->formRow($formclasses->get('submit')); ?>           
                        					</div>
				                        	 <?php echo $this->form()->closeTag(); ?>
				                        </div>
									</div>
									<!-- end widget content -->	
								</div>
								<!-- end widget div -->
								
							</div>
							<!-- end widget -->
</article>



 <script>
$(function() {
$( "#datepicker" ).datepicker();
			
		


				// Validation
				$("#classes").validate({

					// Rules for form validation
					rules : {
						name: {
							required : true
						},
						section : {
							required : true
							
						},
						
					},

					// Messages for form validation
					messages : {
						name : {
							required : 'Please input class name'
						},
						section: {
							required : 'Please select a section'
						},
					},

					// Do not change code below
					errorPlacement : function(error, element) {
						error.insertAfter(element.parent());
					},

				});


});
</script>