
        <?php echo $this->headScript()
            
            ->appendFile($this->basePath() . '/js/jquery-2.1.1.min.js')
            ->appendFile($this->basePath() . '/js/jquery-ui-1.10.3.min.js')
            ->appendFile($this->basePath() . '/js/app.config.js')
            ->appendFile($this->basePath() . '/js/smartwidgets/jarvis.widget.min.js')
            ->appendFile($this->basePath() . '/js/bootstrap.min.js')
            ->appendFile($this->basePath() . '/js/plugin/pace/pace.min.js')
            ->appendFile($this->basePath() . '/js/app.min.js')
            ->appendFile($this->basePath() . '/js/demo.min.js')
            ->prependFile($this->basePath() . '/js/plugin/jquery-touch/jquery.ui.touch-punch.min.js')
            ->appendFile($this->basePath() . '/js/smartwidgets/jarvis.widget.min.js')
            ->appendFile($this->basePath() . '/js/plugin/select2/select2.min.js')
           ->appendFile($this->basePath() . '/js/ajaxform.js')
           ->appendFile($this->basePath() . '/js/edit.js')
           ->appendFile($this->basePath() . '/js/editterm.js')
             //  $this->headScript()->prependFile('http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js', 'text/javascript')
              //      ->prependFile('http://ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js', 'text/javascript')
                //    ->appendFile('/jqGrid/js/i18n/grid.locale-en.js', 'text/javascript')
                //    ->appendFile('/jqGrid/plugins/ui.multiselect.js', 'text/javascript')
                //    ->appendFile('/jqGrid/js/jquery.jqGrid.min.js', 'text/javascript') 
        ; ?>

<article class="col-xs-12 col-sm-6 col-md-12 col-lg-6">
<div class="jarviswidget jarviswidget-color-Darken" id="wid-id-18" data-widget-colorbutton="false" data-widget-editbutton="false">
        <!-- widget options:
        usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">
        data-widget-colorbutton="false" 
        data-widget-editbutton="false"
        data-widget-togglebutton="false"
        data-widget-deletebutton="false"
        data-widget-fullscreenbutton="false"
        data-widget-custombutton="false"
        data-widget-collapsed="true" 
        data-widget-sortable="false"   
                                -->
             <header>
                <h2><strong>MANAGE SECTION</strong></h2>               
             </header>
                <!-- widget div-->
    <div>       
       <!-- widget edit box -->
         <div class="jarviswidget-editbox">
            <!-- This area used as dropdown edit box -->
            <input class="form-control" type="text">
            <span class="note"><i class="fa fa-check text-success"></i> Change title to update and save instantly!</span>      
          </div>
                <!-- end widget edit box -->
                <!-- widget content -->
            <div class="widget-body no-padding">
                <div class="widget-body-toolbar"> 
                    
                    <div class="row alert alert-info no-margin fade in"> 
                        
                        <?php $formsection = $this->formsection;
                        $formsection->setAttribute('action', $this->url('admin/default',array('action'=> 'addsection','controller' => 'section')));
                        $formsection->setAttribute('role', 'form-horizontal');
                        $formsection->setAttribute('class', 'form-inline');
                        $formsection->setAttribute('id', 'section');
                        $formsection->prepare(); ?>
                        <?php echo $this->form()->openTag($formsection); ?>
                
                                       
                        <div class="row"> 
                        <div class="col-xs-5 col-sm-5 col-md-5 col-lg-5">
                            <?php echo $this->formElementErrors($formsection->get('name')); ?>
                            <?php echo $this->formInput($formsection->get('name')); ?>    
                        </div>

                        <div class="col-xs-7 col-sm-7 col-md-7 col-lg-7">
                        <?php echo $this->formElementErrors($formsection->get('description')); ?>
                        <?php echo $this->formInput($formsection->get('description')); ?>      
                         <?php echo $this->formRow($formsection->get('submit')); ?>
                        </div>
                        </div>
                        
                        <div class="row">
                        <div class="col-xs-3 col-sm-7 col-md-7 col-lg-7 text-right">             
                        </div>
                        </div>
                              <?php echo $this->form()->closeTag(); ?>
                    </div>
                
                </div>
                                        
                <div class="custom-scroll table-responsive" style="height:290px; overflow-y: scroll;">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Description</th>
                                <th>Subject count</th>
                                <th>Action</th>
                            </tr>
                        </thead><?php foreach ($sections as $section) : ?>
                        <tbody>
                            <tr>
                    <td><?php echo $this->escapeHtml($section->getName());?></td>
                    <td><?php echo $this->escapeHtml($section->getDescription());?></td>
                    <td><?php echo (count($this->escapeHtml($section->getDescription())));?></td>
                    <td>
<a id="editterm" href="<?php echo $this->url('admin/default',array('controller' => 'section','action'=>'editsection', 'id' => $section->getid()));?>"><button class="btn btn-xs btn-default"><i class='fa fa-pencil'></i></button></a>

<a id="conf" href="<?php echo $this->url('admin/default',array('controller' => 'section','action'=>'deletesection', 'id' => $section->getid()));?>"onclick="return confirm('Do you rely want to delete this section?')"><button class="btn btn-xs btn-default"><i class='fa fa-times'></i></button></a>
                    </td>                                                        
                        </tr><?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
        
          </div>
                                    <!-- end widget content --> 
        </div>
        <!-- end widget div -->   
    </div>
    <!-- end widget -->
</article>

<article class="col-xs-12 col-sm-6 col-md-12 col-lg-6">
<div class="jarviswidget jarviswidget-color-blueDark" id="wid-id-18" data-widget-colorbutton="false" data-widget-editbutton="false">
        <!-- widget options:
        usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">
        data-widget-colorbutton="false" 
        data-widget-editbutton="false"
        data-widget-togglebutton="false"
        data-widget-deletebutton="false"
        data-widget-fullscreenbutton="false"
        data-widget-custombutton="false"
        data-widget-collapsed="true" 
        data-widget-sortable="false"   
                                -->
             <header>
                <h2><strong>MANAGE CLASSES</strong></h2>               
             </header>
                <!-- widget div-->
    <div>       
       <!-- widget edit box -->
         <div class="jarviswidget-editbox">
            <!-- This area used as dropdown edit box -->
            <input class="form-control" type="text">
            <span class="note"><i class="fa fa-check text-success"></i> Change title to update and save instantly!</span>      
          </div>
                <!-- end widget edit box -->
                <!-- widget content -->
            <div class="widget-body no-padding">
                <div class="widget-body-toolbar"> 
                    
                    <div class="row alert alert-info no-margin fade in">    
                         <?php $formclasses = $this->formclasses;
                        $formclasses->setAttribute('action', $this->url('admin/default',array('action'=> 'addclasses','controller' => 'section')));
                         $formclasses->setAttribute('role', 'form-horizontal');
                         $formclasses->setAttribute('class', 'form-inline');
                         $formclasses->setAttribute('id', 'classes');
                        $formclasses->prepare(); ?>
                        <?php echo $this->form()->openTag($formclasses); ?>
                
                                       
                       <div class="rows"> 
                                            <div class="col-xs-5 col-sm-5 col-md-5 col-lg-5">
                                            <?php echo $this->formElementErrors($formclasses->get('name')); ?>
                                            <?php echo $this->formInput($formclasses->get('name')); ?>  
                                            </div>

                                             <div class="col-xs-4 col-sm-5 col-md-5 col-lg-4">
                                            <?php echo $this->formElementErrors($formclasses->get('section')); ?>
                                            <?php echo $this->formSelect($formclasses->get('section')); ?>    
                                            </div>
                                            <div class="col-xs-1 col-sm-1 col-md-1 col-lg-1">  
                                            <?php echo $this->formRow($formclasses->get('submit')); ?>           
                                            </div>
                                             <?php echo $this->form()->closeTag(); ?>
                                        </div>
                              <?php echo $this->form()->closeTag(); ?>
                    </div>
                
                </div>
                                        
                <div class="custom-scroll table-responsive" style="height:290px; overflow-y: scroll;">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Section</i></th>
                                <th>Action</th>
                            </tr>
                        </thead><?php foreach ($classes as $class) : ?>
                        <tbody>
                            <tr>
                    <td><?php echo $this->escapeHtml($class->getName());?></td>
                    <td><?php echo $this->escapeHtml($class->getSection()->getName());?></td>
                    <td>
<a id="editterm" href="<?php echo $this->url('admin/default',array('controller' => 'section','action'=>'editclasses', 'id' => $class->getid()));?>"><button class="btn btn-xs btn-default"><i class='fa fa-pencil'></i></button></a>

<a id="conf" href="<?php echo $this->url('admin/default',array('controller' => 'section','action'=>'deleteclasses', 'id' => $class->getid()));?>"onclick="return confirm('Do you rely want to delete this class?')"><button class="btn btn-xs btn-default"><i class='fa fa-times'></i></button></a>
                    </td>                                                        
                        </tr><?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
        
          </div>
                                    <!-- end widget content --> 
        </div>
        <!-- end widget div -->   
    </div>
    <!-- end widget -->
</article>






 </article>
                        <!-- WIDGET END -->



 <script>
$(function() {
$( "#datepicker" ).datepicker();
            
        


                // Validation
                $("#section").validate({

                    // Rules for form validation
                    rules : {
                        name: {
                            required : true
                        },
                        description : {
                            required : false
                            
                        },
                        
                    },

                    // Messages for form validation
                    messages : {
                        name : {
                            required : 'Please enter section name'
                        },
                        description: {
                            required : 'Please select a section'
                        },
                    },

                    // Validation
                $("#classes").validate({

                    // Rules for form validation
                    rules : {
                        name: {
                            required : true
                        },
                        section : {
                            required : true
                            
                        },
                        
                    },

                    // Messages for form validation
                    messages : {
                        name : {
                            required : 'Please enter section name'
                        },
                        section: {
                            required : 'Please select a section'
                        },
                    },

                    // Do not change code below
                    errorPlacement : function(error, element) {
                        error.insertAfter(element.parent());
                    },

                });


});
</script>