<article class="col-md-8">                         
                            <!-- Widget ID (each widget will need unique ID)-->
        

                            <!-- Widget ID (each widget will need unique ID)-->
                            <div class="jarviswidget" id="wid-id-18543" >
                                <!-- widget options:
                                    usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">
                                    
                                    data-widget-colorbutton="false" 
                                    data-widget-editbutton="false"
                                    data-widget-togglebutton="false"
                                    data-widget-deletebutton="false"
                                    data-widget-fullscreenbutton="false"
                                    data-widget-custombutton="false"
                                    data-widget-collapsed="true" 
                                    data-widget-sortable="false"
                                    
                                -->
                                <header style="color:#fff; background:#274A80;">
                                    <span class="widget-icon"><i class="glyphicon glyphicon-tasks"></i></span><h2><strong>Student process history</strong></h2>         
                                    
                                </header>

                                <!-- widget div-->
                                <div>
                                    
                                    <!-- widget edit box -->
                                    <div class="jarviswidget-editbox">
                                        <!-- This area used as dropdown edit box -->
                                        <input class="form-control" type="text">
                                        <span class="note"><i class="fa fa-check text-success"></i> Change title to update and save instantly!</span>
                                        
                                    </div>
                                    <!-- end widget edit box -->
                                    
                                    <!-- widget content -->
                                    <div class="widget-body">

                                        <div class="row">
                
                                            <div class="col-md-12">
                                        <div class="widget-body-toolbar">
                                            
                                            <div class="row">
                                                
                                                <div class="col-xs-9 col-sm-5 col-md-5 col-lg-5">
                                                    
                    
                                                        <div class="input-group">
                                                        <span class="input-group-addon"><i class="fa fa-search"></i></span>
                                                        <input class="form-control" id="searchTerm" value="" placeholder="Filter" type="text" name="searchTerm"/>
                                                    </div>
                                                </div>
                                                
                                            </div>
                                            
                                                

                                        </div>
                                        
                                        <div class="custom-scroll table-responsive">
                                            

                                            <table class="table table-bordered">
                                                    <thead> 
                            <tr>
                                <th><label class="font-sm label label-success">#School Year</label></th>
                                <th><label class="font-sm label label-info"># Position</label></th>
                            </tr>
                        </thead>
                        <tbody><?php if($positions):?>
                    <?php foreach ($positions as $position) : ?>
                            <tr>
                            <td><?php echo $this->escapeHtml($position->getYear()->getName());?></td>
                            <td><?php echo $this->escapeHtml($position->getPosition()->getName());?></td>
                       
                            </tr>
                            
                        <?php endforeach; ?>
                                                    
                                <?php endif;?>                  
                    
                                                </tbody>
                                            </table>
                                        </form>
                                        </div>
                                        
                                        
                                    
                                    </div>
                                    
    
                                    </div>

                                    
                                    
                                </div>
                                <!-- end widget div -->
                                
                            </div>
                            <!-- end widget -->
                

                        </article>


                        <!-- MODAL FOR EDITING ACADEMIC SESSION -->

                        <!-- end widget div -->
<div class="modal fade" id="items" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content" style="width:900px;">
            
           
                        </div><!-- /.modal-content -->
                    </div><!-- /.modal-dialog -->
                </div><!-- /.modal -->
<!-- END OF MODAL FOR EDITING ACADEMIC SESSION-->
                        <!-- end widget div -->
<div class="modal fade" id="edit" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content" style="width:900px;">
            
           
                        </div><!-- /.modal-content -->
                    </div><!-- /.modal-dialog -->
                </div><!-- /.modal -->
<!-- END OF MODAL FOR EDITING ACADEMIC SESSION-->