	<article class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
			

							<!-- Widget ID (each widget will need unique ID)-->
							<div class="jarviswidget" id="wid-id-0" data-widget-colorbutton="true"	>
								<!-- widget options:
									usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">
									
									data-widget-colorbutton="false"	
									data-widget-editbutton="false"
									data-widget-togglebutton="false"
									data-widget-deletebutton="false"
									data-widget-fullscreenbutton="false"
									data-widget-custombutton="false"
									data-widget-collapsed="true" 
									data-widget-sortable="false"
									
								-->
								<header>
									<h2>Add School Term</h2>				
									
								</header>

								<!-- widget div-->
								<div>
									
									<!-- widget edit box -->
									<div class="jarviswidget-editbox">
										<!-- This area used as dropdown edit box -->
										
										
									</div>
									<!-- end widget edit box -->
									
									<!-- widget content -->
									<div class="widget-body no-padding">
									<?php $form = $this->form;
				$form->setAttribute('action', $this->url('term',array('action'=> 'add','controller' => 'term')));

             $form->setAttribute('class', 'smart-form');
             $form->setAttribute('role', 'form');
				$form->prepare(); ?>
				<?php echo $this->form()->openTag($form); ?>

				<fieldset>
				          	<div clas="row"> 
									<section class="col col-12">
										<label class="input"> <i class="icon-append fa fa-user"></i>
											<?php echo $this->formInput($form->get('name')); ?>
										</label>
										 <?php echo $this->formElementErrors($form->get('name')); ?>
									</section>
							</div>
					</fieldset>							
												
				
							<footer>
								<?php echo $this->formRow($form->get('submit')); ?>
							</footer>
							<?php echo $this->form()->closeTag(); ?>
				
									</div>
									<!-- end widget content -->
									
								</div>
								<!-- end widget div -->
								
							</div>
							<!-- end widget -->
</article>
