<div class="row">
<div class="col-sm-12">


<div class="well well well-sm well-light">
    <div style="border-color:#B9CEEC; border-width:2px 0px 0px; margin-top:8px; margin-bottom:15px;">
        <div class="alert alert-info alert-block">
                                                <button class="close" data-dismiss="alert">
                                                    ×
                                                </button><i class="fa-fw fa fa-info"></i>
                                                <a  data-dismiss="modal" data-toggle="modal" data-target="#itemsx" href="<?php echo $this->url('assessment',array('controller' => 'assessment','action'=>'editassessment', 'id' => $this->id));?>"><button type="button" class="btn btn-xs btn-warning"><i class="fa fa-pencil-square-o"></i> <span class="hidden-mobile">Edit</span></button></a> 
                                            </div>
        </div>
 
        <div class="row">
            <div class="col col-sm-12">

                      <table class="table table-bordered">
                        
                            <tr>
                                <th>Assessment Name</th>
                                <th>Short Name</th>
                                <th>Precentage</th>
                                
                           </tr>
                           <?php if($assess):?>
                       <?php foreach ($assess as $asses) : ?>
                        <tbody>
                            <tr>
                       <td><?php echo $asses->getAssessName();?></td>
                       <td><?php echo $asses->getShortName();?></td>
                       <td><?php echo $asses->getPercentage();?></td>                                        
                           </tr>
                    <?php endforeach; ?>
                  <?php endif;?>
                        </tbody>
                    </table>

            </div>

                                                 

        </div>
</div>
</div>
</div>