
	<article class="col-xs-12 col-sm-12 col-md-10 col-lg-10">
			

							<!-- Widget ID (each widget will need unique ID)-->
							<div class="jarviswidget" id="wid-id-0">
								<!-- widget options:
									usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">
									
									data-widget-colorbutton="false"	
									data-widget-editbutton="false"
									data-widget-togglebutton="false"
									data-widget-deletebutton="false"
									data-widget-fullscreenbutton="false"
									data-widget-custombutton="false"
									data-widget-collapsed="true" 
									data-widget-sortable="false"
									
								-->
								<header>
									<h2>Add Assessment Items</h2>				
									
								</header>

								<!-- widget div-->
								<div>
									
									<!-- widget edit box -->
									<div class="jarviswidget-editbox">
										<!-- This area used as dropdown edit box -->
										
										
									</div>
									<!-- end widget edit box -->
									
									<!-- widget content -->
							<div class="widget-body no-padding">

									<div class="widget-body-toolbar">
                    						<div class="row">
                       

		                                         <div class="col-md-4">                       
		                                            <a id="add" class="btn btn-sm btn-primary"><i class="glyphicon glyphicon-cloud-download"></i> New Row item</a>
		                                        </div>
		                                         <div class="col-md-4">                       
		                                            <a id="remove" class="btn btn-sm btn-danger"><i class="glyphicon glyphicon-trash"></i> Remove last Row item</a>
		                                        </div>
		                                         <div class="col-md-4 text-right">                       
		                                            <button onclick="document.getElementById('assessment').submit();" class="btn btn-sm btn-success"><i class="glyphicon glyphicon-floppy-saved"></i> Save Assessment </button>
		                                        </div>                                   
			                           	 </div>
			               			 </div> 
               	 <div class="row">
               	 	<div class="col-md-12">
                        <form id="assessment" name="assessment" class="smart-form"  action="/assessment/editassessment/<?php echo $this->id;?>" method="post">
                              
                                    <table class="table" id="table-assessment">

                                        <tbody><?php foreach ($assessments as $assess):?>
                                        <tr class="set">
                                        <td>
                                         <section class=""><label class="input"><i></i>
                                         <input class="" value="<?php echo $assess->getAssessName();?>" id="assessName" name="assessName[]" placeholder="Enter Assessment Name" required="required">
                                             </label>
                                        </section>
                                         </td>
                                        <td style="display:none;">
                                         
                                         <input class="" value="<?php echo $assess->getId();?>" id="id" name="id[]">
                                            
                                         </td>
                                         <td>
                                         <section class=""><label class="input"><i></i>
                                         <input class="" value="<?php echo $assess->getShortName();?>" id="shortName" name="shortName[]" placeholder="Enter Short Name" required="required">
                                             </label>
                                        </section>
                                         </td>
                                         <td>
                                         <section class=""><label class="input"><i></i>
                                         <input class="" value="<?php echo $assess->getPercentage();?>" id="percentage" name="percentage[]" placeholder="Enter Percentage Mark" required="required">
                                             </label>
                                        </section>
                                         </td>
                                                                                
                                     </tr><?php endforeach;?>
                                 </tbody>
                                    </table>
                               
                                                                     
                                </form>
                           </div>
                                   
                     </div>



									</div>
									<!-- end widget content -->	
									
								</div>
								<!-- end widget div -->
								
							</div>
							<!-- end widget -->
</article>
<script>
  /* DO NOT REMOVE : GLOBAL FUNCTIONS!
     *
     * pageSetUp(); WILL CALL THE FOLLOWING FUNCTIONS
     *
     * // activate tooltips
     * $("[rel=tooltip]").tooltip();
     *
     * // activate popovers
     * $("[rel=popover]").popover();
     *
     * // activate popovers with hover states
     * $("[rel=popover-hover]").popover({ trigger: "hover" });
     *
     * // activate inline charts
     * runAllCharts();
     *
     * // setup widgets
     * setup_widgets_desktop();
     *
     * // run form elements
     * runAllForms();
     *
     ********************************
     *
     * pageSetUp() is needed whenever you load a page.
     * It initializes and checks for all basic elements of the page
     * and makes rendering easier.
     *
     */

    pageSetUp();
    
    /*
     * ALL PAGE RELATED SCRIPTS CAN GO BELOW HERE
     * eg alert("my home function");
     * 
     * var pagefunction = function() {
     *   ...
     * }
     * loadScript("js/plugin/_PLUGIN_NAME_.js", pagefunction);
     * 
     * TO LOAD A SCRIPT:
     * var pagefunction = function (){ 
     *  loadScript(".../plugin.js", run_after_loaded);  
     * }
     * 
     * OR you can load chain scripts by doing
     * 
     * loadScript(".../plugin.js", function(){
     *   loadScript("../plugin.js", function(){
     *     ...
     *   })
     * });
     */
    
    // pagefunction
    
    var pagefunction = function() {
        // clears the variable if left blank
         $("#add").click(function() {
 $('#table-assessment tbody>tr:last')
    .clone(true)
    .insertAfter('#table-assessment tbody>tr:last').hide().fadeIn().find('input').each(function(){
        $(this).val('');
    });
});


  $("#remove").click(function() {
 $('#table-assessment tbody>tr:last-child')
    .remove()
  
    });


    };
    
    // end pagefunction

    // destroy generated instances 
    // pagedestroy is called automatically before loading a new page
    // only usable in AJAX version!

    var pagedestroy = function(){
        
        /*
        Example below:

        $("#calednar").fullCalendar( 'destroy' );
        if (debugState){
            root.console.log("✔ Calendar destroyed");
        } 

        For common instances, such as Jarviswidgets, Google maps, and Datatables, are automatically destroyed through the app.js loadURL mechanic

        */
    }

    // end destroy
    
    // run pagefunction
    pagefunction();

</script>	


