	









<article class="col-sm-12 col-md-12 col-lg-6">
				
							<!-- Widget ID (each widget will need unique ID)-->
							<div class="jarviswidget" id="wid-id-4" data-widget-colorbutton="false" data-widget-editbutton="false" data-widget-custombutton="false">
								<!-- widget options:
								usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">
				
								data-widget-colorbutton="false"
								data-widget-editbutton="false"
								data-widget-togglebutton="false"
								data-widget-deletebutton="false"
								data-widget-fullscreenbutton="false"
								data-widget-custombutton="false"
								data-widget-collapsed="true"
								data-widget-sortable="false"
				
								-->
								<header>
									<span class="widget-icon"> <i class="fa fa-edit"></i> </span>
									<h2>Add Subjects</h2>
				
								</header>
				
								<!-- widget div-->
								<div>
				
									<!-- widget edit box -->
									<div class="jarviswidget-editbox">
										<!-- This area used as dropdown edit box -->
				
									</div>
									<!-- end widget edit box -->
				
									<!-- widget content -->
									<div class="widget-body">
										
				
									<?php $formterm = $this->formterm;
									$form->setAttribute('action', $this->url('admin/default',array('action'=> 'add','controller' => 'subject')));
									$form->prepare(); ?>
									<?php echo $this->form()->openTag($form); ?>
				
											<fieldset>
												
				
												<section class="col-6">
													<label>Subject Name</label>
													<div class="input-group">
														<?php echo $this->formInput($form->get('subName')); ?>
														<span class="input-group-addon"><i class="fa fa-file-text-o "></i></span>
													</div>
												</section>
												
												<section class="col-6">
													<label>Subject Code</label>
													<div class="input-group">
														<?php echo $this->formInput($form->get('code')); ?>
														<span class="input-group-addon"><i class="fa fa-file-text-o "></i></span>
													</div>
												</section>
				
												<section class="col-12">
													<label>Subject Code</label>
													<div class="input-group">
														<?php echo $this->formTextarea($form->get('description')); ?>
														<span class="input-group-addon"><i class="fa fa-file-text-o "></i></span>
													</div>
												</section>
				
				
												<div class="form-actions">
													<div class="row">
														<div class="col-md-12">
															
															<?php echo $this->formRow($form->get('submit')); ?>
														</div>
													</div>
												</div>
				
											</fieldset>
										
								<?php echo $this->form()->closeTag(); ?>
				
									</div>
									<!-- end widget content -->
				
								</div>
								<!-- end widget div -->
				
							</div>
	</article>