<?php echo $this->doctype(); ?>

<html lang="en" >
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('sclogic '. $this->translate('School Logic'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/font-awesome.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                        ->prependStylesheet($this->basePath() . '/css/erp-production-plugins.min.css')
                        ->prependStylesheet($this->basePath() . '/css/erp-production.min.css')
                        ->prependStylesheet($this->basePath() . '/css/erp-skins.min.css') 
                        ->prependStylesheet($this->basePath() . '/css/erp-rtl.min.css') 
                        ->prependStylesheet($this->basePath() . '/css/demo.min.css')?>
        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>


<body class="smart-style-5">

    <!-- #HEADER -->
    <header id="header">
      <div id="logo-group">

        <!-- PLACE YOUR LOGO HERE -->
        <span id="logo"> <img src="img/logo.png" alt="SmartAdmin"> </span>
        <!-- END LOGO PLACEHOLDER -->

        <!-- Note: The activity badge color changes when clicked and resets the number to 0
           Suggestion: You may want to set a flag when this happens to tick off all checked messages / notifications -->
        <span id="activity" class="activity-dropdown"> <i class="fa fa-user"></i> <b class="badge"> 21 </b> </span>

        <!-- AJAX-DROPDOWN : control this dropdown height, look and feel from the LESS variable file -->
        <div class="ajax-dropdown">

          <!-- the ID links are fetched via AJAX to the ajax container "ajax-notifications" -->
          <div class="btn-group btn-group-justified" data-toggle="buttons">
            <label class="btn btn-default">
              <input type="radio" name="activity" id="ajax/notify/mail.html">
              Msgs (14) </label>
            <label class="btn btn-default">
              <input type="radio" name="activity" id="ajax/notify/notifications.html">
              notify (3) </label>
            <label class="btn btn-default">
              <input type="radio" name="activity" id="ajax/notify/tasks.html">
              Tasks (4) </label>
          </div>

          <!-- notification content -->
          <div class="ajax-notifications custom-scroll">

            <div class="alert alert-transparent">
              <h4>Click a button to show messages here</h4>
              This blank page message helps protect your privacy, or you can show the first message here automatically.
            </div>

            <i class="fa fa-lock fa-4x fa-border"></i>

          </div>
          <!-- end notification content -->

          <!-- footer: refresh area -->
          <span> Last updated on: 12/12/2013 9:43AM
            <button type="button" data-loading-text="<i class='fa fa-refresh fa-spin'></i> Loading..." class="btn btn-xs btn-default pull-right">
              <i class="fa fa-refresh"></i>
            </button> </span>
          <!-- end footer -->

        </div>
        <!-- END AJAX-DROPDOWN -->
      </div>

      <!-- #PROJECTS: projects dropdown -->
      <div class="project-context hidden-xs">

        <span class="label">Projects:</span>
        <span class="project-selector dropdown-toggle" data-toggle="dropdown">Recent projects <i class="fa fa-angle-down"></i></span>

        <!-- Suggestion: populate this list with fetch and push technique -->
        <ul class="dropdown-menu">
          <li>
            <a href="javascript:void(0);">Online e-merchant management system - attaching integration with the iOS</a>
          </li>
          <li>
            <a href="javascript:void(0);">Notes on pipeline upgradee</a>
          </li>
          <li>
            <a href="javascript:void(0);">Assesment Report for merchant account</a>
          </li>
          <li class="divider"></li>
          <li>
            <a href="javascript:void(0);"><i class="fa fa-power-off"></i> Clear</a>
          </li>
        </ul>
        <!-- end dropdown-menu-->

      </div>
      <!-- end projects dropdown -->

      <!-- #TOGGLE LAYOUT BUTTONS -->
      <!-- pulled right: nav area -->
      <div class="pull-right">
        
        <!-- collapse menu button -->
        <div id="hide-menu" class="btn-header pull-right">
          <span> <a href="javascript:void(0);" data-action="toggleMenu" title="Collapse Menu"><i class="fa fa-reorder"></i></a> </span>
        </div>
        <!-- end collapse menu -->
        
        <!-- #MOBILE -->
        <!-- Top menu profile link : this shows only when top menu is active -->
       

        <!-- logout button -->
        <div id="logout" class="btn-header transparent pull-right">
          <span> <a href="login.html" title="Sign Out" data-action="userLogout" data-logout-msg="You can improve your security further after logging out by closing this opened browser"><i class="fa fa-sign-out"></i></a> </span>
        </div>
        <!-- end logout button -->

        <!-- search mobile button (this is hidden till mobile view port) -->
        <div id="search-mobile" class="btn-header transparent pull-right">
          <span> <a href="javascript:void(0)" title="Search"><i class="fa fa-search"></i></a> </span>
        </div>
        <!-- end search mobile button -->
        
        <!-- #SEARCH -->
        <!-- input: search field -->
        <form action="search.html" class="header-search pull-right">
          <input id="search-fld" type="text" name="param" placeholder="Find reports and more">
          <button type="submit">
            <i class="fa fa-search"></i>
          </button>
          <a href="javascript:void(0);" id="cancel-search-js" title="Cancel Search"><i class="fa fa-times"></i></a>
        </form>
        <!-- end input: search field -->

        <!-- fullscreen button -->
        <div id="fullscreen" class="btn-header transparent pull-right">
          <span> <a href="javascript:void(0);" data-action="launchFullscreen" title="Full Screen"><i class="fa fa-arrows-alt"></i></a> </span>
        </div>
        <!-- end fullscreen button -->
        
        <!-- #Voice Command: Start Speech -->
        <div id="speech-btn" class="btn-header transparent pull-right hidden-sm hidden-xs">
          <div> 
            <a href="javascript:void(0)" title="Voice Command" data-action="voiceCommand"><i class="fa fa-microphone"></i></a> 
            <div class="popover bottom"><div class="arrow"></div>
              <div class="popover-content">
                <h4 class="vc-title">Voice command activated <br><small>Please speak clearly into the mic</small></h4>
                <h4 class="vc-title-error text-center">
                  <i class="fa fa-microphone-slash"></i> Voice command failed
                  <br><small class="txt-color-red">Must <strong>"Allow"</strong> Microphone</small>
                  <br><small class="txt-color-red">Must have <strong>Internet Connection</strong></small>
                </h4>
                <a href="javascript:void(0);" class="btn btn-success" onclick="commands.help()">See Commands</a> 
                <a href="javascript:void(0);" class="btn bg-color-purple txt-color-white" onclick="$('#speech-btn .popover').fadeOut(50);">Close Popup</a> 
              </div>
            </div>
          </div>
        </div>
        <!-- end voice command -->

      </div>
      <!-- end pulled right: nav area -->

    </header>
    <!-- END HEADER -->

    <!-- #NAVIGATION -->
    <!-- Left panel : Navigation area -->
    <!-- Note: This width of the aside area can be adjusted through LESS variables -->
    <aside id="left-panel">

      <!-- User info -->
      <div class="login-info">
        <span> <!-- User image size is adjusted inside CSS, it should stay as it --> 
          
          <a href="javascript:void(0);" id="show-shortcut" data-action="toggleShortcut">
            <img src="img/avatars/sunny.png" alt="me" class="online" /> 
            <span>
              john.doe 
            </span>
            <i class="fa fa-angle-down"></i>
          </a> 
          
        </span>
      </div>
      <!-- end user info -->

      <!-- NAVIGATION : This navigation is also responsive-->
      <nav>
        <ul>
          <li>
            <a href="index.html" title="Dashboard"><i class="fa fa-lg fa-fw fa-home"></i> <span class="menu-item-parent">Dashboard</span></a>
          </li>
          <li>
            <a href="#"><i class="fa fa-lg fa-fw fa-user" ></i> <span class="menu-item-parent">Profile</span></a>
            <ul>
              <li>
                <a href="flot.html">View</a>
              </li>
              <li>
                <a href="morris.html">Edit</a>
              </li>
              
            </ul>
          </li>
          <li>
            <a href="#"><i class="fa fa-lg fa-fw fa-file-text-o "></i> <span class="menu-item-parent">Apply</span></a>
          </li>
          <li>
            <a href="#"><i class="fa fa-lg fa-fw fa-gavel"></i> <span class="menu-item-parent">Application status</span></a>
          </li>
          <li>
            <a href="#"><i class="fa fa-lg fa-fw fa-info-circle "></i> <span class="menu-item-parent">Application guidelines</span></a>
          </li>           
        </ul>
      </nav>
      <span class="minifyme" data-action="minifyMenu"> 
        <i class="fa fa-arrow-circle-left hit"></i> 
      </span>

    </aside>
    <!-- END NAVIGATION -->

    <!-- MAIN PANEL -->
    <div id="main" role="main">

      <!-- RIBBON -->
      <div id="ribbon">

        <span class="ribbon-button-alignment"> 
          <span id="refresh" class="btn btn-ribbon" data-action="resetWidgets" data-title="refresh"  rel="tooltip" data-placement="bottom" data-original-title="<i class='text-warning fa fa-warning'></i> Warning! This will reset all your widget settings." data-html="true">
            <i class="fa fa-refresh"></i>
          </span> 
        </span>

        <!-- breadcrumb -->
        <ol class="breadcrumb">
         <?php echo $this->navigation()->breadcrumbs(); ?>
        </ol>
        <!-- end breadcrumb -->

        <!-- You can also add more buttons to the
        ribbon for further usability

        Example below:

        <span class="ribbon-button-alignment pull-right">
        <span id="search" class="btn btn-ribbon hidden-xs" data-title="search"><i class="fa-grid"></i> Change Grid</span>
        <span id="add" class="btn btn-ribbon hidden-xs" data-title="add"><i class="fa-plus"></i> Add</span>
        <span id="search" class="btn btn-ribbon" data-title="search"><i class="fa-search"></i> <span class="hidden-mobile">Search</span></span>
        </span> -->

      </div>
      <!-- END RIBBON -->
      
      

      <!-- MAIN CONTENT -->
      <div id="content">

        <!-- row -->
        <div class="row">
          
          <!-- col -->
          <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
            
          </div>
          <!-- end col -->
          
        </div>
        <!-- end row -->
        
        <!--
          The ID "widget-grid" will start to initialize all widgets below 
          You do not need to use widgets if you dont want to. Simply remove 
          the <section></section> and you can use wells or panels instead 
          -->
        
        <!-- widget grid -->
        <section id="widget-grid" class="">
        
          <!-- row -->
          <div class="row">
            
            <!-- NEW WIDGET START -->
            <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><?php $this->NotificationsHelper();?>
              <?php echo $this->content; ?>
        
            </article>
            <!-- WIDGET END -->
            
          </div>
        
          <!-- end row -->
        
        
        </section>
        <!-- end widget grid -->

      </div>
      <!-- END MAIN CONTENT -->

    </div>
    <!-- END MAIN PANEL -->

    <!-- PAGE FOOTER -->
    <div class="page-footer">
      <div class="row">
        <div class="col-xs-12 col-sm-6">
          <span class="txt-color-white">SmartAdmin 1.5 <span class="hidden-xs"> - Web Application Framework</span> © 2014-2015</span>
        </div>
      </div>
    </div>
    <!-- END PAGE FOOTER -->

    <!-- SHORTCUT AREA : With large tiles (activated via clicking user name tag)
    Note: These tiles are completely responsive,
    you can add as many as you like
    -->
    
    </div>
    <!-- END SHORTCUT AREA -->

    <!--================================================== -->

    <!-- PACE LOADER - turn this on if you want ajax loading to show (caution: uses lots of memory on iDevices)-->
  

     <?php echo $this->headScript()
     //->prependFile($this->basePath() . 'http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js')
    // ->prependFile($this->basePath() . 'http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js')
    ->prependFile($this->basePath() . '/js/bootstrap/bootstrap.min.js')
        ; ?>


          <?php echo $this->inlineScript() ?>
    <!-- Demo purpose only -->
   

    <!-- PAGE RELATED PLUGIN(S) 
    <script src="..."></script>-->

   
  </body>

</html>