<div class="custom-scroll table-responsive" style="height:290px; overflow-y: scroll;">
                        <?php if($students):?>
                    <table class="table table-bordered table-hover">
                        <thead>
                            <tr>
                                <th>Photo</th>
                                <th>Admission No</th>
                                <th>Name</th>
                                <th>Action</th>
                            </tr>
                        
                        </thead><?php foreach($students as $student) : ?>
                        <tbody>
                            <tr>
                    
                    <td><img src="<?php echo $this->basePath?>/data/uploads/students/<?php echo $student['student']['image'];?>" alt="staff pic" style="max-width:50px; border:5px solid #FFF;"></td>
                    <td><?php echo $this->escapeHtml($student['student']['admNo']);?></td>
                    <td><?php echo $this->escapeHtml($student['student']['person']['fname'].' '.$student['student']['person']['lname']);?></td>
                    <td>

<a id="conf" href="<?php echo $this->url('classes',array('controller' => 'class','action'=>'delete', 'id' => $student['student']['id']));?>"onclick="return confirm('Do you rely want to delete this class?')"><button class="btn btn-xs btn-danger"><i class='glyphicon glyphicon-trash'></i></button></a>
                    </td>                                                        
                        </tr><?php endforeach; ?>
                   
                        </tbody>
                    </table>
                </div>
        
        <?php endif;?>