
	<article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
			

							<!-- Widget ID (each widget will need unique ID)-->
							<div class="jarviswidget" id="wid-id-0">
								<!-- widget options:
									usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">
									
									data-widget-colorbutton="false"	
									data-widget-editbutton="false"
									data-widget-togglebutton="false"
									data-widget-deletebutton="false"
									data-widget-fullscreenbutton="false"
									data-widget-custombutton="false"
									data-widget-collapsed="true" 
									data-widget-sortable="false"
									
								-->
								<header>
									<h2>Edit academic session</h2>				
									
								</header>

								<!-- widget div-->
								<div>
									
									<!-- widget edit box -->
									<div class="jarviswidget-editbox">
										<!-- This area used as dropdown edit box -->
										
										
									</div>
									<!-- end widget edit box -->
									
									<!-- widget content -->
									<div class="widget-body no-padding">
										<?php $formsession = $this->form;
				$formsession->setAttribute('action', $this->url('academic-year',array('action'=> 'edit','controller' => 'session', 'id'=>$this->id)));
				$formsession->setAttribute('class', 'smart-form');
                $formsession->setAttribute('role', 'form');
				$formsession->prepare(); ?>
				<?php echo $this->form()->openTag($formsession);
				$startdate = $formsession->get('startDate');
				$enddate = $formsession->get('endDate');?>

				<fieldset>


										      <div class="row">
                                    <section class="col col-6">
                                        <label class="select">
                                        <?php echo $this->formSelect($formsession->get('year')); ?>
                                        <i></i></label>
                                    </section>

                                    <section class="col col-6">
                                        <label class="select">
                                        <?php echo $this->formSelect($formsession->get('semester')); ?>
                                        <i></i></label>
                                    </section>
                            </div>
                    
                            <div class="row">
                                <section class="col col-6">
                                    <label class="input"><i class="icon-append fa fa-calendar"></i>
                                     <?php echo $this->formDate($formsession->get('startDate')); ?>
                                    </label>
                                </section>
                                            
                                <section class="col col-6">
                                    <label class="input"> <i class="icon-append fa fa-calendar"></i>
                                    <?php echo $this->formDate($formsession->get('endDate')); ?>
                                    </label>
                                </section>
                            </div>

                </fieldset>
                                                                                                    
							<footer>
                            
                                <?php echo $this->formRow($formsession->get('submit')); ?>
                                <?php echo $this->form()->closeTag(); ?>
							</footer>
									</div>
									<!-- end widget content -->
									
								</div>
								<!-- end widget div -->
								
							</div>
							<!-- end widget -->
</article>



 <script>
$(function() {
$( "#datepicker" ).datepicker();
			
			$('#startdate').datepicker({
				dateFormat : 'dd/mm/yy',
				changeMonth: true,
				changeYear: true,
				prevText : '<i class="fa fa-chevron-left"></i>',
				nextText : '<i class="fa fa-chevron-right"></i>',
				onSelect : function(selectedDate) {
					$('#enddate').datepicker('option', 'minDate', selectedDate);
				}
			});
			
			$('#enddate').datepicker({
				dateFormat : 'dd/mm/yy',
				changeMonth: true,
				changeYear: true,
				prevText : '<i class="fa fa-chevron-left"></i>',
				nextText : '<i class="fa fa-chevron-right"></i>',
				onSelect : function(selectedDate) {
					$('#startdate').datepicker('option', 'maxDate', selectedDate);
				}
			});



});
</script>