					  									  				

	<article class="col-xs-12 col-sm-12 col-md-8 col-lg-6">
			

							<!-- Widget ID (each widget will need unique ID)-->
							<div class="jarviswidget" id="wid-id-70" data-widget-deletebutton="false">
								<!-- widget options:
									usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">
									
									data-widget-colorbutton="false"	
									data-widget-editbutton="false"
									data-widget-togglebutton="false"
									data-widget-deletebutton="false"
									data-widget-fullscreenbutton="false"
									data-widget-custombutton="false"
									data-widget-collapsed="true" 
									data-widget-sortable="false"
									
								-->
								<header>
									<h2>Edit year</h2>				
									
								</header>

								<!-- widget div-->
								<div>
									
									<!-- widget edit box -->
									<div class="jarviswidget-editbox">
										<!-- This area used as dropdown edit box -->
										
										
									</div>
									<!-- end widget edit box -->
									
									<!-- widget content -->
									<div class="widget-body">
										<?php $form = $this->form;
				$form->setAttribute('action', $this->url('year',array('action'=> 'edityear','controller' => 'year', 'id'=>$this->id)));
				$form->prepare(); ?>
				<?php echo $this->form()->openTag($form); ?>

												<section class="col-6">
													<label>Year Name</label>
													<div class="input-group">
														<?php echo $this->formInput($form->get('name')); ?>
													</div>
												</section>

											<section class="col-6">
													<label>Year Name</label>
													<div class="input-group">
														<?php echo $this->formSelect($form->get('status')); ?>	
													</div>
												</section>
														
				
												
				
												<div class="form-actions">
													<div class="row">
														<div class="col-md-12">
															
															<?php echo $this->formRow($form->get('submit')); ?>
														</div>
													</div>
												</div>
				
				
									<!-- end widget content -->	
								</div>
								<!-- end widget div -->
								
							</div>
							<!-- end widget -->
</article>



 <script>
$(function() {
$( "#datepicker" ).datepicker();
			
		


				// Validation
				$("#section").validate({

					// Rules for form validation
					rules : {
						name: {
							required : true
						},
						description: {
							required : false
							
						},
						
					},

					// Messages for form validation
					messages : {
						name : {
							required : 'Please enter section name'
						},
						description: {
							required : 'Please select a section'
						},
					},

					// Do not change code below
					errorPlacement : function(error, element) {
						error.insertAfter(element.parent());
					},

				});


});
</script>