<article class="col-sm-12 col-md-12 col-lg-6">
				
							<!-- Widget ID (each widget will need unique ID)-->
							<div class="jarviswidget" id="wid-id-4" data-widget-deletebutton="false">
								<!-- widget options:
								usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">
				
								data-widget-colorbutton="false"
								data-widget-editbutton="false"
								data-widget-togglebutton="false"
								data-widget-deletebutton="false"
								data-widget-fullscreenbutton="false"
								data-widget-custombutton="false"
								data-widget-collapsed="true"
								data-widget-sortable="false"
				
								-->
								<header>
									<span class="widget-icon"> <i class="fa fa-edit"></i> </span>
									<h2>New Salary Defination</h2>
				
								</header>
				
								<!-- widget div-->
								<div>
				
									<!-- widget edit box -->
									<div class="jarviswidget-editbox">
										<!-- This area used as dropdown edit box -->
				
									</div>
									<!-- end widget edit box -->
				
									<!-- widget content -->
									<div class="widget-body">
										
				
				<?php $form = $this->form;
				$form->setAttribute('action', $this->url('formmaster',array('action'=> 'add','controller' => 'formmaster')));
				$form->prepare(); ?>
				<?php echo $this->form()->openTag($form); ?>
				<?php $mas = $form->get('formmaster');?>

									
								<div class="row">
					
												<section class="col-6">
													<div class="input-group">
														 <?php echo $this->formElementErrors($mas->get('staff')); ?>
														<?php echo $this->formSelect($mas->get('staff')); ?>
													</div>
												</section>
												
												<section class="col-6">
													<div class="input-group">
														 <?php echo $this->formElementErrors($mas->get('class')); ?>
														<?php echo $this->formSelect($mas->get('class')); ?>
													</div>
												</section>
				

				
													<div class="row">
														<div class="col-md-12 text-right">
															
															<?php echo $this->formRow($form->get('submit')); ?>
															<?php echo $this->form()->closeTag(); ?>
														</div>
													</div>
									</div>
								
				
									</div>
									<!-- end widget content -->
				
								</div>
								<!-- end widget div -->
				
							</div>
	</article>