<article class="col-md-8" id="article">							
							<!-- Widget ID (each widget will need unique ID)-->
		

							<!-- Widget ID (each widget will need unique ID)-->
							<div class="jarviswidget" id="wid-id-18" >
								<!-- widget options:
									usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">
									
									data-widget-colorbutton="false"	
									data-widget-editbutton="false"
									data-widget-togglebutton="false"
									data-widget-deletebutton="false"
									data-widget-fullscreenbutton="false"
									data-widget-custombutton="false"
									data-widget-collapsed="true" 
									data-widget-sortable="false"
									
								-->
								<header style="color:#fff; background:#274A80;">
									<span class="widget-icon"><i class="glyphicon glyphicon-tasks"></i></span><h2><strong>Form-Master Configuration</strong></h2>			
									
								</header>

								<!-- widget div-->
								<div>
									
									<!-- widget edit box -->
									<div class="jarviswidget-editbox">
										<!-- This area used as dropdown edit box -->
										<input class="form-control" type="text">
										<span class="note"><i class="fa fa-check text-success"></i> Change title to update and save instantly!</span>
										
									</div>
									<!-- end widget edit box -->
									
									<!-- widget content -->
									<div class="widget-body">
										<div class="widget-body-toolbar">
											
											<div class="row">
												
												<div class="col-xs-9 col-sm-5 col-md-5 col-lg-5">
													
                    
        												<div class="input-group">
														<span class="input-group-addon"><i class="fa fa-search"></i></span>
														<input class="form-control" id="searchTerm" value="" placeholder="Filter" type="text" name="searchTerm"/>
													</div>
												</div>
												<div class="col-xs-3 col-sm-7 col-md-7 col-lg-7 text-right">
													
													<button data-toggle="modal" data-target="#Salary" class="btn btn-success">
														<i class="fa fa-plus"></i> <span class="hidden-mobile">Add New Form-Master</span>
													</button>

													
													
												</div>
												
											</div>
											
												

										</div>
										
										<div class="custom-scroll table-responsive">
											

											<table class="table table-bordered">
													<thead> 
							<tr>
								<th>Photo</th>
								<th>Full Name</th>
								<th>Class</th>
								<th>Action </th>
							</tr>
						</thead>
						<tbody>
					<?php foreach ($masters as $master) : ?>
							<tr>
							<td>
									<a rel="lightbox" href="<?php echo $this->basePath?>/data/uploads/students/<?php echo $this->escapeHtml($master->getStaff()->getImage());?>">
								<img src="<?php echo $this->basePath?>/data/uploads/students/<?php echo $this->escapeHtml($master->getStaff()->getImage());?>" alt="teacher pic" style="max-width:35px;"></a>
							</td>
							<td><?php echo $this->escapeHtml($master->getStaff()->getFname());?></td>
						    <td><?php echo $this->escapeHtml($master->getClass()->getName());?></td>
						    <td>
 <a  data-toggle="modal" data-target="#edit" href="<?php echo $this->url('formmaster',array('controller' => 'formmaster','action'=>'edit', 'id' => $master->getid()));?>"><button type="button" class="btn btn-xs btn-info"><i class="fa fa-pencil-square-o"></i></button></a>  

 
					 

<a id="smart" data-action="userLogout" data-logout-msg="Do you really want to delete this form master?"
href="<?php echo $this->url('formmaster',array('controller' => 'formmaster','action'=>'delete', 'id' => $master->getid()));?>"><button type="button" class="btn btn-xs btn-danger">
  <i class="glyphicon glyphicon-trash"></i></button></a>
							</td>
							</tr>
							
						<?php endforeach; ?>
													
													
												</tbody>
											</table>
										
										</div>
										
										
									
									</div>
									<!-- end widget content -->
									<div class="widget-footer">
				<?php echo $this->paginationControl($masters, 'Sliding', 'partial/paginator', array('route' => 'formmaster'));?>
										</div>
									
								</div>
								<!-- end widget div -->
								
							</div>
							<!-- end widget -->

						</article>

						<!-- MODAL FOR EDITING ACADEMIC SESSION -->
<div class="modal fade" id="edit" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            
           
                        </div><!-- /.modal-content -->
                    </div><!-- /.modal-dialog -->
                </div><!-- /.modal -->
<!-- END OF MODAL FOR EDITING ACADEMIC SESSION-->
						<!-- end widget div -->
<!-- MODAL FOR EDITING ACADEMIC SESSION -->
<div class="modal fade" id="Salary" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
									&times;
				</button>
				<h4 class="modal-title" id="myModalLabel">New Form-Master</h4>
			</div>
				<div class="modal-body">
				<?php $form = $this->form;
				$form->setAttribute('action', $this->url('formmaster',array('action'=> 'add','controller' => 'formmaster')));
				$form->prepare(); ?>
				<?php echo $this->form()->openTag($form); ?>
				<?php $mas = $form->get('formmaster');?>
					
				

					<div class="row">
						<div class="col col-4">
							<label class="select">
			<?php echo $this->formSelect($mas->get('staff')); ?>
							</label>
						</div>
					<div class="col col-4">
			<?php echo $this->formSelect($mas->get('class')); ?>
						</div>
						<div class="col col-4">
			<?php echo $this->formSelect($mas->get('year')->setAttribute('readonly', 'true')); ?>
						</div>
						
				  				
			   </div>

			<div class="modal-footer">
			<button type="button" class="btn btn-default" data-dismiss="modal">
									Cancel
			</button>
			<?php echo $this->formRow($form->get('submit')); ?>
								<?php echo $this->form()->closeTag(); ?>
			</div>
						</div><!-- /.modal-content -->
					</div><!-- /.modal-dialog -->
				</div><!-- /.modal -->
<!-- END OF MODAL FOR EDITING ACADEMIC SESSION-->

<script>
  /* DO NOT REMOVE : GLOBAL FUNCTIONS!
     *
     * pageSetUp(); WILL CALL THE FOLLOWING FUNCTIONS
     *
     * // activate tooltips
     * $("[rel=tooltip]").tooltip();
     *
     * // activate popovers
     * $("[rel=popover]").popover();
     *
     * // activate popovers with hover states
     * $("[rel=popover-hover]").popover({ trigger: "hover" });
     *
     * // activate inline charts
     * runAllCharts();
     *
     * // setup widgets
     * setup_widgets_desktop();
     *
     * // run form elements
     * runAllForms();
     *
     ********************************
     *
     * pageSetUp() is needed whenever you load a page.
     * It initializes and checks for all basic elements of the page
     * and makes rendering easier.
     *
     */

    pageSetUp();
    
    /*
     * ALL PAGE RELATED SCRIPTS CAN GO BELOW HERE
     * eg alert("my home function");
     * 
     * var pagefunction = function() {
     *   ...
     * }
     * loadScript("js/plugin/_PLUGIN_NAME_.js", pagefunction);
     * 
     * TO LOAD A SCRIPT:
     * var pagefunction = function (){ 
     *  loadScript(".../plugin.js", run_after_loaded);  
     * }
     * 
     * OR you can load chain scripts by doing
     * 
     * loadScript(".../plugin.js", function(){
     *   loadScript("../plugin.js", function(){
     *     ...
     *   })
     * });
     */
    
    // pagefunction
    
    var pagefunction = function() {
        // clears the variable if left blank
    };
    
    // end pagefunction

    // destroy generated instances 
    // pagedestroy is called automatically before loading a new page
    // only usable in AJAX version!

    var pagedestroy = function(){
        
        /*
        Example below:

        $("#calednar").fullCalendar( 'destroy' );
        if (debugState){
            root.console.log("✔ Calendar destroyed");
        } 

        For common instances, such as Jarviswidgets, Google maps, and Datatables, are automatically destroyed through the app.js loadURL mechanic

        */
    }

    // end destroy
    
    // run pagefunction
    pagefunction();

</script>