 <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

    <div class="jarviswidget" id="wid-id-98554">

        <header>
            <h2>View Attendance</h2>
        </header><!-- widget div-->

        <div>
            <!-- widget edit box -->
            <div class="jarviswidget-editbox">
                <!-- This area used as dropdown edit box -->
                <input class="form-control" type="text">
            </div><!-- end widget edit box -->

            <!-- widget content -->
            <div class="widget-body">
                <div class="widget-body-toolbar">
                    <div class="row">
                        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                      <form  class="smart-form"  action="/students/attendance" method="post">


                                         <section class="col col-sm-3"><label class="select"><i></i>
                                         <select class="select2" id="session" name="session">
                                            <option value="">select session</option>
                                                <?php if($sessions): ?>
                                                            <option value="<?php echo $sessions->getId(); ?>"><?php echo $sessions->getYear()->getName(). ' - '.$sessions->getTerm()->getName(); ?></option>
                                                     <?php endif; ?>
                                             </select> </label>
                                        </section>
                                                                                
                                         <section class="col col-sm-2">                       
                                            <button type="submit" class="btn btn-sm btn-primary"><i class="glyphicon glyphicon-cloud-download"></i> View</button>
                                        </section>
                                       </form> 
                                                                 
                                     
                                </div>
                                </div>

                </div> 



    <table id="attendtable"  data-show-export="true" data-pagination="true" data-click-to-select="true" data-show-refresh="true" data-show-toggle="true" data-show-columns="true" data-search="true" data-select-item-name="toolbar1" class="table table-bordered table-hover">
                        <thead> 
                            <tr>
                                
                                <th>Session</th>
                                 <th>Class</th>
                                <th>Date</th>
                                <th>Status</th>
                                <th>Reason</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php if($attends):?>         
                    <?php foreach ($attends as $attend) : ?>
                            <tr>    
         <td><?php echo $attend['y_name'] .' ' .$attend['t_name'];?></td>
         <td style="width:15%;"><?php echo $attend['c_name'];?></td>
         <td style="width:15%;"><?php echo $attend['a_date']->format("d/m/Y");?></td>                            
         <td style="width:15%;"><?php echo $attend['a_status'];?></td>
         <td style="width:15%;"><?php echo $attend['a_reason'];?></td>
 
                            </tr> 
                           <?php endforeach; ?><?php endif;?>
                        </tbody>
                    </table>
                                        
                                       
</form>








     </div><!-- end widget content -->
        </div><!-- end widget div -->
    </div><!-- end widget -->
</article>

<div class="modal fade" id="items" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content" style="width:900px;">
            
           
                        </div><!-- /.modal-content -->
                    </div><!-- /.modal-dialog -->
                </div><!-- /.modal -->

                <script>
  /* DO NOT REMOVE : GLOBAL FUNCTIONS!
     *
     * pageSetUp(); WILL CALL THE FOLLOWING FUNCTIONS
     *
     * // activate tooltips
     * $("[rel=tooltip]").tooltip();
     *
     * // activate popovers
     * $("[rel=popover]").popover();
     *
     * // activate popovers with hover states
     * $("[rel=popover-hover]").popover({ trigger: "hover" });
     *
     * // activate inline charts
     * runAllCharts();
     *
     * // setup widgets
     * setup_widgets_desktop();
     *
     * // run form elements
     * runAllForms();
     *
     ********************************
     *
     * pageSetUp() is needed whenever you load a page.
     * It initializes and checks for all basic elements of the page
     * and makes rendering easier.
     *
     */

    pageSetUp();
    
    /*
     * ALL PAGE RELATED SCRIPTS CAN GO BELOW HERE
     * eg alert("my home function");
     * 
     * var pagefunction = function() {
     *   ...
     * }
     * loadScript("js/plugin/_PLUGIN_NAME_.js", pagefunction);
     * 
     * TO LOAD A SCRIPT:
     * var pagefunction = function (){ 
     *  loadScript(".../plugin.js", run_after_loaded);  
     * }
     * 
     * OR you can load chain scripts by doing
     * 
     * loadScript(".../plugin.js", function(){
     *   loadScript("../plugin.js", function(){
     *     ...
     *   })
     * });
     */
    
    // pagefunction
    
    var pagefunction = function() {

          $("#sectionx").change(function(){
    var state = $("#sectionx").val();
    var myData = {state: state};
    //The post using ajax
      $.ajax({
              type:"POST",
              url:"/result/class",
              data:myData,
              success: function(data){
                                 
                             var st=""
             for(i in data){
                st+="<option id='"+data[i].id+"'>"+data[i].name+"</option>"
              }
               $("#classx").html(st);

              },
         
             });
  });


         $("#classx").change(function(){
    var state = $("#classx").val();
    var myData = {state: state};
    //The post using ajax
      $.ajax({
              type:"POST",
              url:"/result/student",
              data:myData,
              success: function(data){
                                 
                             var st=""
             for(i in data){
                st+="<option id='"+data[i].id+"'>"+data[i].admNo+"</option>"
              }
               $("#studentx").html(st);

              },
         
             });
  });

                $('#startdate').datepicker({
            dateFormat : 'dd.mm.yy',
            prevText : '<i class="fa fa-chevron-left"></i>',
            nextText : '<i class="fa fa-chevron-right"></i>',
        });

      // clears the variable if left blank
        $('#attendtable').bootstrapTable({

            });
    };
     loadScript("/bot/bootstrap-table.js");
    // end pagefunction

    // destroy generated instances 
    // pagedestroy is called automatically before loading a new page
    // only usable in AJAX version!

    var pagedestroy = function(){
        
        /*
        Example below:

        $("#calednar").fullCalendar( 'destroy' );
        if (debugState){
            root.console.log("✔ Calendar destroyed");
        } 

        For common instances, such as Jarviswidgets, Google maps, and Datatables, are automatically destroyed through the app.js loadURL mechanic

        */
    }

    // end destroy
    
    // run pagefunction
    pagefunction();

</script>