 <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

    <div class="jarviswidget" id="wid-id-92434">

        <header>
            <span class="widget-icon"> <i class="fa fa-road"></i> </span><h2>Transportation Allotment</h2>
        </header><!-- widget div-->

        <div>
            <!-- widget edit box -->
            <div class="jarviswidget-editbox">
                <!-- This area used as dropdown edit box -->
                <input class="form-control" type="text">
            </div><!-- end widget edit box -->

            <!-- widget content -->
            <div class="widget-body">
                <div class="widget-body-toolbar">
                    <div class="row">
                        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                                                   
                                     
                                </div>
                                </div>

                </div> 



    <table id="allottable" data-show-export="true" data-pagination="true" data-click-to-select="true" data-show-refresh="true" data-show-toggle="true" data-show-columns="true" data-search="true" data-select-item-name="toolbar1" class="table table-bordered">
                        <thead> 
                            <tr>
                                <th>Session</th>
                                <th>Route</th>
                                <th>Vehicle</th>
                                <th>Driver</th>
                                <th>Fare</th>
                                <th>Amount Paid</th>
                               
                            </tr>
                        </thead>
                        <tbody>
                            <?php if($allots):?>         
                    <?php foreach ($allots as $allot) : ?>
                            <tr> 
       
         <td><?php echo$allot['y_name']. '-' .$allot['t_name'];?></td>
        <td><?php echo $allot['r_name'];?></td>
        <td><?php echo $allot['v_name'];?></td>
        <td><?php echo $allot['d_fname'];?></td>
        <td><?php echo $allot['sr_fare'];?></td>
        <td><?php echo $allot['s_fare'];?></td>
      
                            </tr> 
                           <?php endforeach; ?><?php endif;?>
                        </tbody>
                    </table>
                                        


     </div><!-- end widget content -->
        </div><!-- end widget div -->
    </div><!-- end widget -->
</article>

<div class="modal fade" id="edit" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content" style="width:900px;">
            
           
                        </div><!-- /.modal-content -->
                    </div><!-- /.modal-dialog -->
                </div><!-- /.modal -->

                <script>
  /* DO NOT REMOVE : GLOBAL FUNCTIONS!
     *
     * pageSetUp(); WILL CALL THE FOLLOWING FUNCTIONS
     *
     * // activate tooltips
     * $("[rel=tooltip]").tooltip();
     *
     * // activate popovers
     * $("[rel=popover]").popover();
     *
     * // activate popovers with hover states
     * $("[rel=popover-hover]").popover({ trigger: "hover" });
     *
     * // activate inline charts
     * runAllCharts();
     *
     * // setup widgets
     * setup_widgets_desktop();
     *
     * // run form elements
     * runAllForms();
     *
     ********************************
     *
     * pageSetUp() is needed whenever you load a page.
     * It initializes and checks for all basic elements of the page
     * and makes rendering easier.
     *
     */

    pageSetUp();
    
    /*
     * ALL PAGE RELATED SCRIPTS CAN GO BELOW HERE
     * eg alert("my home function");
     * 
     * var pagefunction = function() {
     *   ...
     * }
     * loadScript("js/plugin/_PLUGIN_NAME_.js", pagefunction);
     * 
     * TO LOAD A SCRIPT:
     * var pagefunction = function (){ 
     *  loadScript(".../plugin.js", run_after_loaded);  
     * }
     * 
     * OR you can load chain scripts by doing
     * 
     * loadScript(".../plugin.js", function(){
     *   loadScript("../plugin.js", function(){
     *     ...
     *   })
     * });
     */
    
    // pagefunction
    
    var pagefunction = function() {
         $('#allottable').bootstrapTable({

            });
    };
     loadScript("/bot/bootstrap-table.js", pagefunction);


    
    //loadScript("js/edusoft.js", pagefunction);
    // end pagefunction

    // destroy generated instances 
    // pagedestroy is called automatically before loading a new page
    // only usable in AJAX version!

    var pagedestroy = function(){
        
        /*
        Example below:

        $("#calednar").fullCalendar( 'destroy' );
        if (debugState){
            root.console.log("✔ Calendar destroyed");
        } 

        For common instances, such as Jarviswidgets, Google maps, and Datatables, are automatically destroyed through the app.js loadURL mechanic

        */
    }

    // end destroy
    
    // run pagefunction
    pagefunction();

</script>