<?php echo $this->doctype(); ?>

<html lang="en-us" id="lock-page">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Edusoft '. $this->translate('Cloud Base School Management System'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0') 
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))       
                        ->prependStylesheet($this->basePath() . '/css/lockscreen.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/font-awesome.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                        ->prependStylesheet($this->basePath() . '/css/erp-production-plugins.min.css')
                        ->prependStylesheet($this->basePath() . '/css/erp-production.min.css')
                        ->prependStylesheet($this->basePath() . '/css/erp-skins.min.css') 
                        ->prependStylesheet($this->basePath() . '/css/erp-rtl.min.css') 
                        ->prependStylesheet($this->basePath() . '/css/demo.min.css')?>
        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>


<body>

    <div id="main" role="main">
<?php echo $this->content; ?>
    </div>

    <!-- END SHORTCUT AREA -->

    <!--================================================== -->

    <!-- PACE LOADER - turn this on if you want ajax loading to show (caution: uses lots of memory on iDevices)-->
  

     <?php echo $this->headScript()  
             ->prependFile($this->basePath() . '/js/editterm.js')
           
            ->prependFile($this->basePath() . '/js/smartwidgets/jarvis.widget.min.js')
            ->prependFile($this->basePath() . 'js/notification/SmartNotification.min.js')
            ->prependFile($this->basePath() . 'js/plugin/jquery-validate/jquery.validate.min.js')
            ->prependFile($this->basePath() . '/js/plugin/pace/pace.min.js')
            ->prependFile($this->basePath() . '/js/plugin/jquery-touch/jquery.ui.touch-punch.min.js')
            ->prependFile($this->basePath() . '/js/smartwidgets/jarvis.widget.min.js')
            ->prependFile($this->basePath() . '/js/plugin/select2/select2.min.js')
           // ->prependFile($this->basePath() . '/js/demo.min.js')
            ->prependFile($this->basePath() . '/js/app.min.js')
            ->prependFile($this->basePath() . '/js/app.config.js')
            ->prependFile($this->basePath() . '/js/bootstrap/bootstrap.min.js')
            //->prependFile($this->basePath() . 'http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js')
           // ->prependFile($this->basePath() . 'http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js')
             ->prependFile($this->basePath() . '/js/imagelightbox.js')
            ->prependFile($this->basePath() . '/js/jquery-ui-1.10.3.min.js')
            ->prependFile($this->basePath() . '/js/jquery-2.1.1.min.js')
        ; ?>


          <?php echo $this->inlineScript() ?>
    <!-- Demo purpose only -->
   

    <!-- PAGE RELATED PLUGIN(S) -->
    <script>
  $(document).ready(function() {
      
      pageSetUp();
    
    });
    </script>

   
  </body>

</html>