<?php echo $this->doctype(); ?>

<html lang="en" style='background-image: url("<?php echo $this->basePath('../img/pattern/graphy.png') ?>");'>
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Edusoft '. $this->translate('Cloud Base School Management System'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0') 
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                     ->prependStylesheet($this->basePath() . '/css/style.css')
                     ->prependStylesheet($this->basePath() . '/bot/bootstrap-table.css')
                     ->prependStylesheet($this->basePath() . '/css/demo.min.css')
                       //->prependStylesheet($this->basePath() . '/css/jquery.dynatable.css') 
                     ->prependStylesheet($this->basePath() . '/css/erp-rtl.min.css') 
                     ->prependStylesheet($this->basePath() . '/css/erp-skins.min.css') 
                     ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                     ->prependStylesheet($this->basePath() . '/css/erp-production.min.css')
                     ->prependStylesheet($this->basePath() . '/css/erp-production-plugins.min.css')
                     ->prependStylesheet($this->basePath() . '/css/font-awesome.min.css')
                       ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>


<body class="smart-style-1 container fixed-footer">

    <!-- #HEADER -->
    <header id="header">
      <div id="logo-group">

        <!-- PLACE YOUR LOGO HERE -->
        <span id="logo"> <img src="<?php echo $this->basePath('../img/brain.png') ?>" alt="Edusoft" style="width:auto; height:39px;"> </span>
        <!-- END LOGO PLACEHOLDER -->

      </div>

      <div class="project-context">

        <span class="label"><strong><?php echo $this->translate('Welcome'); ?>, <?php echo $this->zfcUserDisplayName() ?>! </strong></span>
        <span class="project-selector dropdown-toggle" >     
         <?php $sessions=$this->myHelper();
         if(!empty($sessions)){
          $year=$sessions->getYear()->getName();
          $term=$sessions->getTerm()->getName();
       echo '      Academic Session :' .$year.' - '.$term;}?></span>

        <!-- Suggestion: populate this list with fetch and push technique -->
        

      </div>
     
     

      <!-- #TOGGLE LAYOUT BUTTONS -->
      <!-- pulled right: nav area -->
      <div class="pull-right">
        
        <!-- collapse menu button -->
        <div id="hide-menu" class="btn-header pull-right">
          <span> <a href="javascript:void(0);" data-action="toggleMenu" title="Collapse Menu"><i class="fa fa-reorder"></i></a> </span>
        </div>
        <!-- end collapse menu -->
        
        <!-- #MOBILE -->
        <!-- Top menu profile link : this shows only when top menu is active -->
       

        <!-- logout button -->
        <div id="logout" class="btn-header transparent pull-right">
          <span> 
            <a href="<?php echo $this->url('zfcuser/logout') ?>"  rel="popover-hover" data-placement="bottom" data-original-title="Logout" data-content="Click on this button if you want to logout."  title="Sign Out" data-action="userLogout" data-logout-msg="You can improve your security further after logging out by closing this opened browser"><i class="fa fa-power-off"></i></a> </span>
        </div>
        <!-- end logout button -->
       

        <!-- fullscreen button -->
        <div id="fullscreen" class="btn-header transparent pull-right">
          <span> <a href="javascript:void(0);" data-action="launchFullscreen" title="Full Screen"><i class="fa fa-arrows-alt"></i></a> </span>
        </div>
        <!-- end fullscreen button -->

         <!-- Welcome -->
        
        <!-- end welcom -->

      </div>
      <!-- end pulled right: nav area -->

    </header>
    <!-- END HEADER -->

    <!-- #NAVIGATION -->
    <!-- Left panel : Navigation area -->
    <!-- Note: This width of the aside area can be adjusted through LESS variables -->
    <aside id="left-panel">

      <!-- User info -->
      <div class="login-info">
        <span> <!-- User image size is adjusted inside CSS, it should stay as it --> 
         
          <img src="<?php echo $this->basePath?>/data/uploads/staffs/<?php if($this->picHelper()){ echo $this->picHelper();}else{echo 'avatar.jpg';};?>" style="max-width:100%; heigth:auto;"/>
            
         
          
        </span>
      </div>
      <!-- end user info -->

      <!-- NAVIGATION : This navigation is also responsive-->
      <nav>
        <ul>
          <li>
            <a href="<?php echo $this->url('admin') ?>" title="Dashboard"><i class="fa fa-lg fa-fw fa-home"></i> <span class="menu-item-parent">Dashboard</span></a>
          </li>

           <li>
            <a href="#"><i class="fa fa-lg fa-fw fa-desktop" ></i> <span class="menu-item-parent">Online Admission</span></a>
            <ul>
              <li><a href="#">Review Admission</a></li>
              <li><a href="#">View students detail</a></li>
            </ul>
          </li> 
 <li>
            <a href="<?php echo $this->url('messages', array('action'=> 'inbox','controller' => 'messages')) ?>"><i class="fa fa-lg fa-fw fa-desktop" ></i> <span class="menu-item-parent">Messages </span><span class="badge pull-right inbox-badge"><?php if($this->MessageHelper){echo $this->MessageHelper();}else{echo 0;};?></span></a>
          </li> 
          <li>
            <a href="#"><i class="fa fa-lg fa-fw fa-graduation-cap" ></i> <span class="menu-item-parent">Student Management</span></a>
            <ul>
              <li><a href="<?php echo $this->url('student', array('action'=> 'add','controller' => 'student')) ?>">New student</a></li>
              <li><a href="<?php echo $this->url('student', array('action'=> 'index','controller' => 'student')) ?>">Students  detail</a></li>
              <li><a href="<?php echo $this->url('position', array('action'=> 'student','controller' => 'position')) ?>">Students  posts</a></li>
            </ul>
          </li>

           <li>
            <a href="#"><i class="fa fa-lg fa-fw fa-group" ></i> <span class="menu-item-parent">Guardian Management</span></a>
            <ul>
              <li><a href="<?php echo $this->url('guardian', array('action'=> 'index','controller' => 'guardian')) ?>">guardians detail</a></li>
            </ul>
          </li>

           <li>
            <a href="#"><i class="fa fa-lg fa-fw fa-user" ></i> <span class="menu-item-parent">Staff Management</span></a>
            <ul>
              <li><a href="<?php echo $this->url('staff', array('action'=> 'add','controller' => 'staff')) ?>">New Staff</a></li>
              <li><a href="<?php echo $this->url('staff', array('action'=> 'index','controller' => 'staff')) ?>">Staff details</a></li>
              <li><a href="<?php echo $this->url('position', array('action'=> 'staff','controller' => 'position')) ?>">Staff posts</a></li>
            </ul>
          </li>

          <li>
            <a href="#"><i class="fa fa-lg fa-fw fa-sitemap "></i> <span class="menu-item-parent">Class Management</span></a>
             <ul>
              <li><a href="<?php echo $this->url('section') ?>">Class sections</a></li>
              <li><a href="<?php echo $this->url('classes') ?>">Class operations </a></li>
              <li><a href="<?php echo $this->url('formmaster') ?>">Class masters </a></li>
                 <li><a href="<?php echo $this->url('classes', array('action'=> 'csearch','controller' => 'class')) ?>">Class search </a></li>
            </ul>
          </li>
         
          <li>
            <a href="#"><i class="fa fa-lg fa-fw fa-book"></i> <span class="menu-item-parent">Subject Management</span></a>
             <ul> <li><a href="<?php echo $this->url('subjectcategory') ?>">Subject category</a></li>
              <li><a href="<?php echo $this->url('subject') ?>">Subject operations</a></li>
              <li><a href="<?php echo $this->url('subject',  array('action'=> 'addteacher','controller' => 'subject'));?>">Subject allocation</a></li>
              <li><a href="<?php echo $this->url('subject',  array('action'=> 'teachers','controller' => 'subject'));?>">Subject teachers</a></li></ul>
          </li>

          <li>
            <a href="#"><i class="fa fa-lg fa-fw fa-calendar-o" ></i> <span class="menu-item-parent">Session Management</span></a>
            <ul>
              <li><a href="<?php echo $this->url('year') ?>">Year and Term</a></li>
              <li><a href="<?php echo $this->url('academic') ?>">Academic session</a></li>
            </ul>
          </li>
          
           <li>
           <a href="#"><i class="fa fa-lg fa-fw fa-hospital-o" ></i> <span class="menu-item-parent">Result Management</span></a>
             <ul>
              <li><a href="<?php echo $this->url('result', array('action'=> 'input','controller' => 'result')) ?>">Input grades</a></li>
              <li><a href="<?php echo $this->url('result', array('action'=> 'single','controller' => 'result')) ?>">View grades</a></li>
            </ul>
          </li>

           <li>
           <a href="<?php echo $this->url('collection')?>"><i class="fa fa-lg fa-fw fa-money" ></i> <span class="menu-item-parent">Fees Management</span></a>
         
            
          </li>

          <li>
           <a href="#"><i class="fa fa-lg fa-fw fa-calendar" ></i> <span class="menu-item-parent">Roll call Management</span></a>
           <ul>
              <li><a href="<?php echo $this->url('attendance', array('contoller' => 'attendance','action' => 'rollcall')); ?>"><stong>Roll call</stong></a></li>
              <li><a href="<?php echo $this->url('attendance', array('controller'=>'attendance','action' => 'index')); ?>"><stong>attendance </stong></a></li>
            </ul>
          </li>

          <li>
           <a href="#"><i class="fa fa-lg fa-fw fa-car" ></i> <span class="menu-item-parent">Transport Management</span></a>
           <ul>
              <li><a href="<?php echo $this->url('transport', array('action'=> 'allotview','controller' => 'transport')); ?>"><stong>Allot transport</stong></a></li>
              <li><a href="<?php echo $this->url('transport', array('action'=> 'route','controller' => 'transport')); ?>">Route</stong></a></li>
              <li><a href="<?php echo $this->url('transport', array('action'=> 'vehicle','controller' => 'transport')); ?>"><stong>Vehicle</stong></a></li>
              <li><a href="<?php echo $this->url('transport', array('action'=> 'settings','controller' => 'transport')); ?>"><stong>Route setting</stong></a></li>
            </ul>
          </li>

            <li>
           <a href="#"><i class="fa fa-lg fa-fw fa-barcode" ></i> <span class="menu-item-parent">Pin Management</span></a>
           <ul>
              <li><a href="#"><stong>Application pin</stong></a></li>
              <li><a href="<?php echo $this->url('resultpins'); ?>"><stong>Result pin</stong></a></li>
            </ul>
          </li>

              <li>
           <a href="#"><i class="fa fa-lg fa-fw fa-lock" ></i> <span class="menu-item-parent">Users Management</span></a>
           <ul>
              <li><a href="<?php echo $this->url('crud'); ?>"><stong>User list</stong></a></li>
            </ul>
          </li>


           <li>
            <a href="#"><i class="fa fa-lg fa-fw fa-wrench" ></i> <span class="menu-item-parent">Settings</span></a>
            <ul>
              <li><a href="<?php echo $this->url('settings') ?>"><stong>Academic setting</stong></a></li>
              <li><a href="<?php echo $this->url('fee') ?>"><stong>Sms settings</stong></a></li>
              <li><a href="<?php echo $this->url('settings', array('action'=> 'addinfo','controller' => 'settings')) ?>"><stong>School setting</stong></a></li>
              <li><a href="<?php echo $this->url('position', array('action'=> 'index','controller' => 'position')) ?>">School  positions</a></li>
            </ul>
          </li>

           <li>
            <a href="#"><i class="fa fa-lg fa-fw fa-cogs" ></i> <span class="menu-item-parent">Configurations</span></a>
            <ul>
              <li><a href="<?php echo $this->url('salary') ?>"><stong>Salary configuration</stong></a></li>
              <li><a href="<?php echo $this->url('fee') ?>"><stong>Fees configuration</stong></a></li>
               <li><a href="<?php echo $this->url('trait') ?>"><stong>Trait configuration</stong></a></li>
              <li><a href="<?php echo $this->url('assessment') ?>"><stong>Assessment configuration</stong></a></li>
              <li><a href="<?php echo $this->url('grade') ?>"><stong>Grading configuration</stong></a></li>
            </ul>
          </li>

          <li>
            <a href="#"><i class="fa fa-lg fa-fw fa-info-circle "></i> <span class="menu-item-parent">Application guidelines</span></a>
          </li>           
        </ul>
      </nav>
      <span class="minifyme" data-action="minifyMenu"> 
        <i class="fa fa-arrow-circle-left hit"></i> 
      </span>


    </aside>
    <!-- END NAVIGATION -->

    <!-- MAIN PANEL -->
    <div id="main" role="main" style="min-height: 1150px">

      <!-- RIBBON -->
      <div id="ribbon">

        <span class="ribbon-button-alignment"> 
          <span id="refresh" class="btn btn-ribbon" data-action="resetWidgets" data-title="refresh"  rel="tooltip" data-placement="bottom" data-original-title="<i class='text-warning fa fa-warning'></i> Warning! This will reset all your widget settings." data-html="true">
            <i class="fa fa-refresh"></i>
          </span> 
        </span>

        <!-- breadcrumb -->
        <ol class="breadcrumb">
         <?php echo $this->navigation()->breadcrumbs()->setMinDepth(0); // <-- Add this!! ?> 

          



      
        </ol>
        <!-- end breadcrumb -->

        <!-- You can also add more buttons to the
        ribbon for further usability

        Example below:

        <span class="ribbon-button-alignment pull-right">
        <span id="search" class="btn btn-ribbon hidden-xs" data-title="search"><i class="fa-grid"></i> Change Grid</span>
        <span id="add" class="btn btn-ribbon hidden-xs" data-title="add"><i class="fa-plus"></i> Add</span>
        <span id="search" class="btn btn-ribbon" data-title="search"><i class="fa-search"></i> <span class="hidden-mobile">Search</span></span>
        </span> -->

      </div>
      <!-- END RIBBON -->
      
      

      <!-- MAIN CONTENT -->
      <div id="content">

        <!-- row -->
        <div class="row">
          
          <!-- col -->
          <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
            
          </div>
          <!-- end col -->
          
        </div>
        <!-- end row -->
        
        <!--
          The ID "widget-grid" will start to initialize all widgets below 
          You do not need to use widgets if you dont want to. Simply remove 
          the <section></section> and you can use wells or panels instead 
          -->
        
        <!-- widget grid -->
        <section id="widget-grid" class="">
        
          <!-- row -->
          <div class="row">
            
            <!-- NEW WIDGET START -->
            <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
             <div class="row"><div class="col-lg-12"><?php $this->NotificationsHelper();?></div></div>
             <div class="row"><?php echo $this->content; ?></div>
        
            </article>
            <!-- WIDGET END -->
            
          </div>
        
          <!-- end row -->
        
        
        </section>
        <!-- end widget grid -->

      </div>
      <!-- END MAIN CONTENT -->

    </div>
    <!-- END MAIN PANEL -->

    <!-- PAGE FOOTER -->
    <div class="page-footer">
      <div class="row">
        <div class="col-xs-12 col-sm-6">
          <span class="txt-color-white">Edusoft 1.5 <span class="hidden-xs"> - School Management System</span> © 2014-2015</span>
        </div>
      </div>
    </div>
    <!-- END PAGE FOOTER -->

    <!-- SHORTCUT AREA : With large tiles (activated via clicking user name tag)
    Note: These tiles are completely responsive,
    you can add as many as you like
    -->
    
    </div>
    <!-- END SHORTCUT AREA -->

    <!--================================================== -->

    <!-- PACE LOADER - turn this on if you want ajax loading to show (caution: uses lots of memory on iDevices)-->
  

     <?php echo $this->headScript()  
                        
            ->prependFile($this->basePath() . '/js/smartwidgets/jarvis.widget.min.js')
            //->prependFile($this->basePath() . 'js/notification/SmartNotification.min.js')
            ->prependFile($this->basePath() . 'js/plugin/jquery-validate/jquery.validate.min.js')
            ->prependFile($this->basePath() . '/js/plugin/pace/pace.min.js')
            ->prependFile($this->basePath() . '/js/plugin/jquery-touch/jquery.ui.touch-punch.min.js')
            ->prependFile($this->basePath() . '/js/smartwidgets/jarvis.widget.min.js')
          
            ->prependFile($this->basePath() . '/js/plugin/select2/select2.min.js')
            ->prependFile($this->basePath() . '/js/demo.min.js')
            ->prependFile($this->basePath() . '/js/jquery.print.js')
         
           ->prependFile($this->basePath() . '/js/plugin/summernote/summernote.min.js')
            ->prependFile($this->basePath() . '/js/app.min.js')
            ->prependFile($this->basePath() . '/js/app.config.js')
               ->prependFile($this->basePath() . '/bot/bootstrap-table.js')
            ->prependFile($this->basePath() . '/js/bootstrap/bootstrap.min.js')
            //->prependFile($this->basePath() . 'http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js')
           // ->prependFile($this->basePath() . 'http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js')
            // ->prependFile($this->basePath() . '/js/imagelightbox.js')
           //   
            ->prependFile($this->basePath() . '/js/jquery-ui-1.10.3.min.js')
            ->prependFile($this->basePath() . '/js/jquery-2.1.1.min.js')
        ; ?>


          <?php echo $this->inlineScript() ?>
    <!-- Demo purpose only -->
   

    <!-- PAGE RELATED PLUGIN(S) -->
    <script>
    function showimagepreview(input) {
        if (input.files && input.files[0]) {
        var filerdr = new FileReader();
        filerdr.onload = function(e) {
        $('#imageupload').attr('src', e.target.result);
        }
        filerdr.readAsDataURL(input.files[0]);
        }
        }


         function showpreview(input) {
        if (input.files && input.files[0]) {
        var filerdr = new FileReader();
        filerdr.onload = function(e) {
        $('#imageuploads').attr('src', e.target.result);
        }
        filerdr.readAsDataURL(input.files[0]);
        }
        }
    
   $("#sectionx").change(function(){
    var state = $("#sectionx").val();
    var myData = {state: state};
    //The post using ajax
      $.ajax({
              type:"POST",
              url:"/result/class",
              data:myData,
              success: function(data){
                                 
                             var st=""
             for(i in data){
                st+="<option id='"+data[i].id+"'>"+data[i].name+"</option>"
              }
               $("#classx").html(st);

              },
         
             });
  });


         $("#classx").change(function(){
    var state = $("#classx").val();
    var myData = {state: state};
    //The post using ajax
      $.ajax({
              type:"POST",
              url:"/result/student",
              data:myData,
              success: function(data){
                                 
                             var st=""
             for(i in data){
                st+="<option id='"+data[i].id+"'>"+data[i].admNo+"</option>"
              }
               $("#studentx").html(st);

              },
         
             });
  });

           $("#add").click(function() {
 $('#table-settings tbody>tr:last')
    .clone(true)
    .insertAfter('#table-settings tbody>tr:last').hide().fadeIn().find('input').each(function(){
        $(this).val('');
    });
});


  $("#remove").click(function() {
 $('#table-settings tbody>tr:last-child')
    .remove()
  
    });

    // fix table height
    tableHeightSize();

    $(window).resize(function() {
      tableHeightSize()
    })
    function tableHeightSize() {

      if ($('body').hasClass('menu-on-top')) {
        var menuHeight = 68;
        // nav height

        var tableHeight = ($(window).height() - 224) - menuHeight;
        if (tableHeight < (320 - menuHeight)) {
          $('.table-wrap').css('height', (320 - menuHeight) + 'px');
        } else {
          $('.table-wrap').css('height', tableHeight + 'px');
        }

      } else {
        var tableHeight = $(window).height() - 224;
        if (tableHeight < 320) {
          $('.table-wrap').css('height', 320 + 'px');
        } else {
          $('.table-wrap').css('height', tableHeight + 'px');
        }

      }

    }

    /*
     * LOAD INBOX MESSAGES
     */
    loadInbox();
    function loadInbox() {
      loadURL("/messages/list", $('#inbox-content > .table-wrap'))
    }
  
    /*
     * Buttons (compose mail and inbox load)
     */
    $(".inbox-load").click(function() {
      loadInbox();
    });
  
    // compose email
    $("#compose-mail").click(function() {
      loadURL("/messages/compose", $('#inbox-content > .table-wrap'));
    });

    // compose email
    $("#students-mail").click(function() {
      loadURL("/messages/students", $('#inbox-content > .table-wrap'));
    });

    // compose email
    $("#parents-mail").click(function() {
      loadURL("/messages/parents", $('#inbox-content > .table-wrap'));
    });

    // compose email
    $("#staffs-mail").click(function() {
      loadURL("/messages/staffs", $('#inbox-content > .table-wrap'));
    });

       function iniEmailBody() {
        $('#emailbody').summernote({
            height: '100%',
            focus: false,
            tabsize: 2
        });
    }

     $("#print").click(function() {
// Print the DIV.
  $("#printdiv").print({
            globalStyles: true,
            mediaPrint: false,
            stylesheet: null,
            noPrintSelector: ".no-print",
            iframe: true,
            append: null,
            prepend: null,
            manuallyCopyFormValues: true,
            deferred: $.Deferred(),
            timeout: 250
    });
//return (false);
});
     //fee items controls
    $("#add").click(function() {
       $('#table-settingss tbody>tr:last')
        .clone(true)
        .insertAfter('#table-settingss tbody>tr:last').hide().fadeIn().find('input').each(function(){
        $(this).val('');
       });
    });

  $("#remove").click(function() {
    $('#table-settingss tbody>tr:last-child')
    .remove()
    });

    //assessment items controls
    $("#add").click(function() {
       $('#table-assessment tbody>tr:last')
        .clone(true)
        .insertAfter('#table-assessment tbody>tr:last').hide().fadeIn().find('input').each(function(){
        $(this).val('');
       });
    });

  $("#remove").click(function() {
    $('#table-assessment tbody>tr:last-child')
    .remove()
    });

      

      $('#studenttable').bootstrapTable({ });
      $('#session-table').bootstrapTable({ });
      $('#inbox-table').bootstrapTable({ });
      $('#allot-table').bootstrapTable({});
      $('#feess-table').bootstrapTable({});
      $('#class-table').bootstrapTable({});
      $('#position-table').bootstrapTable({ });
       $('#student-table').bootstrapTable({ });
      $('#subject-table').bootstrapTable({ });
      $('#postafftable').bootstrapTable({});
      $('#postudenttable').bootstrapTable({});
      $('#guardian-table').bootstrapTable({});
      $('#staff-table').bootstrapTable({});


    </script>
  
  </body>

</html>