<article class="col-sm-12 col-md-12 col-lg-12">
			
			<!-- Widget ID (each widget will need unique ID)-->
			<div class="jarviswidget" id="wid-id-1" data-widget-editbutton="false" data-widget-custombutton="false" style="margin-left:10%; margin-right:10%">
				<!-- widget options:
					usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">
					
					data-widget-colorbutton="false"	
					data-widget-editbutton="false"
					data-widget-togglebutton="false"
					data-widget-deletebutton="false"
					data-widget-fullscreenbutton="false"
					data-widget-custombutton="false"
					data-widget-collapsed="true" 
					data-widget-sortable="false"
					
				-->
				<header>
					<span class="widget-icon"> <i class="fa fa-graduation-cap"></i> </span>
					<h2>School Information </h2>				
					
				</header>

				<!-- widget div-->
				<div>
					
					<!-- widget edit box -->
					<div class="jarviswidget-editbox">
						<!-- This area used as dropdown edit box -->
						
					</div>
					<!-- end widget edit box -->
					
					<!-- widget content -->
					<div class="widget-body">
						<?php $form = $this->form;
			 $form->setAttribute('action', $this->url('settings',array('action'=> 'addinfo','controller' => 'settings')));
			// $form->setAttribute('class', 'form-horizontal');
			// $form->setAttribute('readonly', 'true');
									
			//	$form->setAttribute('style', 'pointer-events: none');
            //$form->setAttribute('class', 'form-inline');

			$form->prepare(); ?>
			<?php echo $this->form()->openTag($form); ?>
			<fieldset>
						
						<div class="row">
							<div class="col col-sm-6">
								<fieldset>

											<div class="form-group">
												<div class="input-group">
												 <?php echo $this->formInput($form->get('name')); ?><span class="input-group-addon"><i class="fa fa-user fa-xs"></i></span>
												 <?php echo $this->formElementErrors($form->get('name')); ?>
											 	</div>
											</div>
									
											<div class="form-group">
												<div class="input-group">
												 <?php echo $this->formInput($form->get('type')); ?><span class="input-group-addon"><i class="fa fa-chain fa-xs"></i></span>
												 <?php echo $this->formElementErrors($form->get('type')); ?>
											 	</div>
											</div>
										
											<div class="form-group">
												<div class="input-group">
												
												 <?php echo $this->formInput($form->get('motto')); ?><span class="input-group-addon"><i class="fa fa-asterisk fa-xs"></i></span>
												 <?php echo $this->formElementErrors($form->get('motto')); ?>
											 	</div>
											</div>

											<div class="form-group">
												<div class="input-group">
												
												 <?php echo $this->formInput($form->get('establish')); ?><span class="input-group-addon"><i class="fa fa-calendar fa-xs"></i></span>
												 <?php echo $this->formElementErrors($form->get('establish')); ?>
											 	</div>
											</div>
										
											<div class="form-group">
												<div class="input-group">
													
												 <?php echo $this->formInput($form->get('mobile')); ?><span class="input-group-addon"><i class="fa fa-phone fa-xs"></i></span>
												 <?php echo $this->formElementErrors($form->get('mobile')); ?>
											 	</div>
											</div>
										
											<div class="form-group">
												<div class="input-group">
													
												 <?php echo $this->formInput($form->get('email')); ?><span class="input-group-addon"><i class="fa fa-envelope fa-xs"></i></span>
												 <?php echo $this->formElementErrors($form->get('email')); ?>
											 	</div>
											</div>
									
											<div class="form-group">
												<div class="input-group">
													
												 <?php echo $this->formInput($form->get('address')); ?><span class="input-group-addon"><i class="fa fa-comment fa-xs"></i></span>
												 <?php echo $this->formElementErrors($form->get('address')); ?>
											 	</div>
											</div>
										
											<div class="form-group">
												<div class="input-group">
													
												 <?php echo $this->formInput($form->get('website')); ?><span class="input-group-addon"><i class="fa fa-globe fa-xs"></i></span>
												 <?php echo $this->formElementErrors($form->get('website')); ?>
											 	</div>
											</div>
								
								</fieldset>
							</div>
							<div class="col col-sm-6">
								<fieldset>
									<div class="row">
										<div class="col col-sm-6">
											
										<img id="imageupload" src="<?php echo $this->basePath('img/images.png') ?>"style="width:115px; height:115px;" alt="me" /> 
											<div class="input input-file">
										 <?php echo $this->formFile($form->get('logo')); ?>
										 <?php echo $this->formElementErrors($form->get('logo')); ?>
										</div>
										
										</div>
										<div class="col col-sm-6">
											<img id="imageuploads" src="<?php echo $this->basePath('img/images.png') ?>"style="width:115px; height:115px;" alt="me" /> 
											<div class="input input-file">
										 <?php echo $this->formFile($form->get('signature')); ?>
										 <?php echo $this->formElementErrors($form->get('signature')); ?>
										</div>
										
										</div>
									</div>
									<div class="row">
										<div class="col col-sm-12">
								<div class="form-group">
									<div class="input-group">
										
									 <?php echo $this->formInput($form->get('waecCode')); ?><span class="input-group-addon"><i class="fa fa-th-large fa-xs"></i></span>
									 <?php echo $this->formElementErrors($form->get('waecCode')); ?>
								 	</div>
								</div>

								<div class="form-group">
									<div class="input-group">
										
									 <?php echo $this->formInput($form->get('jambCode')); ?><span class="input-group-addon"><i class="fa fa-th-large fa-xs"></i></span>
									 <?php echo $this->formElementErrors($form->get('jambCode')); ?>
								 	</div>
								</div>
							
							
								<div class="form-group">
									<div class="input-group">
										
									 <?php echo $this->formInput($form->get('necoCode')); ?><span class="input-group-addon"><i class="fa fa-th-large fa-xs"></i></span>
									 <?php echo $this->formElementErrors($form->get('necoCode')); ?>
								 	</div>
								</div>
								<div class="form-group">
									<div class="input-group">
										
									 <?php echo $this->formInput($form->get('waecCode')); ?><span class="input-group-addon"><i class="fa fa-th-large fa-xs"></i></span>
									 <?php echo $this->formElementErrors($form->get('waecCode')); ?>
								 	</div>
								</div>
							
								<div class="form-group">
									<div class="input-group">
										
									 <?php echo $this->formInput($form->get('nabtedCode')); ?><span class="input-group-addon"><i class="fa fa-th-large fa-xs"></i></span>
									 <?php echo $this->formElementErrors($form->get('nabtedCode')); ?>
								 	</div>
								 </div>
								</div>
							</div>

								</fieldset>
							</div>		
						</div>
					</fieldset>
					<fieldset>
						
							<div class="form-actions">
													<div class="row">
														<div class="col-md-12">
															
															<?php echo $this->formRow($form->get('submit')); ?>
																
															
														</div>
													</div>
												
						
						</fieldset>
							<?php echo $this->form()->closeTag(); ?>
					</div>
					<!-- end widget content -->
					
				</div>
				<!-- end widget div -->
				
			</div>
			<!-- end widget -->


				
</article> 
<script>
  /* DO NOT REMOVE : GLOBAL FUNCTIONS!
     *
     * pageSetUp(); WILL CALL THE FOLLOWING FUNCTIONS
     *
     * // activate tooltips
     * $("[rel=tooltip]").tooltip();
     *
     * // activate popovers
     * $("[rel=popover]").popover();
     *
     * // activate popovers with hover states
     * $("[rel=popover-hover]").popover({ trigger: "hover" });
     *
     * // activate inline charts
     * runAllCharts();
     *
     * // setup widgets
     * setup_widgets_desktop();
     *
     * // run form elements
     * runAllForms();
     *
     ********************************
     *
     * pageSetUp() is needed whenever you load a page.
     * It initializes and checks for all basic elements of the page
     * and makes rendering easier.
     *
     */

    pageSetUp();
    
    /*
     * ALL PAGE RELATED SCRIPTS CAN GO BELOW HERE
     * eg alert("my home function");
     * 
     * var pagefunction = function() {
     *   ...
     * }
     * loadScript("js/plugin/_PLUGIN_NAME_.js", pagefunction);
     * 
     * TO LOAD A SCRIPT:
     * var pagefunction = function (){ 
     *  loadScript(".../plugin.js", run_after_loaded);  
     * }
     * 
     * OR you can load chain scripts by doing
     * 
     * loadScript(".../plugin.js", function(){
     *   loadScript("../plugin.js", function(){
     *     ...
     *   })
     * });
     */
    
    // pagefunction
    
    var pagefunction = function() {
        // clears the variable if left blank

             
    };
     loadScript("js/edusoft.js", pagefunction);
    // end pagefunction

    // destroy generated instances 
    // pagedestroy is called automatically before loading a new page
    // only usable in AJAX version!

    var pagedestroy = function(){
        
        /*
        Example below:

        $("#calednar").fullCalendar( 'destroy' );
        if (debugState){
            root.console.log("✔ Calendar destroyed");
        } 

        For common instances, such as Jarviswidgets, Google maps, and Datatables, are automatically destroyed through the app.js loadURL mechanic

        */
    }

    // end destroy
    
    // run pagefunction
    pagefunction();

</script>





