
	<article class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
			

							<!-- Widget ID (each widget will need unique ID)-->
							<div class="jarviswidget" id="wid-id-0">
								<!-- widget options:
									usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">
									
									data-widget-colorbutton="false"	
									data-widget-editbutton="false"
									data-widget-togglebutton="false"
									data-widget-deletebutton="false"
									data-widget-fullscreenbutton="false"
									data-widget-custombutton="false"
									data-widget-collapsed="true" 
									data-widget-sortable="false"
									
								-->
								<header>
									<h2>Add fee setup</h2>				
									
								</header>

								<!-- widget div-->
								<div>
									
									<!-- widget edit box -->
									<div class="jarviswidget-editbox">
										<!-- This area used as dropdown edit box -->
										
										
									</div>
									<!-- end widget edit box -->
									
									<!-- widget content -->
										<div class="widget-body no-padding">
										<?php $form = $this->form;
				 $form->setAttribute('action', $this->url('fee',array('action'=> 'editfeesection','controller' => 'fee', 'id' => $this->id)));
        		 $form->setAttribute('class', 'smart-form');
        		  $form->setAttribute('role', 'form');
				 $form->prepare(); ?>
				<?php echo $this->form()->openTag($form);?>
				<?php  $fee=$form->get('feesection');?>
						
							<div class="col-12">
										<fieldset><div class="row"> 
				                        	<section class="col col-5">
				                        		 <label class="select"><i><i>
				                            <?php echo $this->formSelect($fee->get('year')); ?> </label> 
				                            <?php echo $this->formElementErrors($fee->get('year')); ?>
				                        	</section>
				                        
				                        </div>
				                        	<?php echo $this->formElementErrors($fee->get('items')); ?>
				                        	<?php echo $this->formCollection($fee->get('items')); ?> 
				          				 
				                    </fieldset>
				                       
				                        	
				                        
				           		
				            	</div>
				            
				            <footer >  
				                        	<?php echo $this->formRow($form->get('submit')); ?>           
                        			</footer>
				                        	 <?php echo $this->form()->closeTag(); ?>
									</div>
									<!-- end widget content -->	
								</div>
								<!-- end widget div -->
								
							</div>
							<!-- end widget -->
</article>
<script type="text/javascript">
     function add_field() {
         var currentCount = $('form fieldset fieldset').length;
         var template = $('form fieldset > span').data('template');
         template = template.replace(/__index__/g, currentCount);
         $('form fieldset').last().append(template);
 
         return false;
     }
    function remove_field(e)
{
    $(e).parent().remove();
    return false;
}

 </script>



 