
	<article class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
			

							<!-- Widget ID (each widget will need unique ID)-->
							<div class="jarviswidget" id="wid-id-0">
								<!-- widget options:
									usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">
									
									data-widget-colorbutton="false"	
									data-widget-editbutton="false"
									data-widget-togglebutton="false"
									data-widget-deletebutton="false"
									data-widget-fullscreenbutton="false"
									data-widget-custombutton="false"
									data-widget-collapsed="true" 
									data-widget-sortable="false"
									
								-->
								<header>
									<h2>Add Trait Format</h2>				
									
								</header>

								<!-- widget div-->
								<div>
									
									<!-- widget edit box -->
									<div class="jarviswidget-editbox">
										<!-- This area used as dropdown edit box -->
										
										
									</div>
									<!-- end widget edit box -->
									
									<!-- widget content -->
									<div class="widget-body">
										<?php $form = $this->form;
				 $form->setAttribute('action', $this->url('trait',array('action'=> 'addtrait','controller' => 'trait','id'=>$this->id)));
        		 $form->setAttribute('class', 'smart-form');
				 $form->prepare(); ?>
				<?php echo $this->form()->openTag($form);?>
				<?php  $grade=$form->get('traitname');?>
							<fieldset>
										<div class="row"> 
				                        	<section class="col col-4">
				                        		 <label class="input">
				                            <?php echo $this->formElementErrors($grade->get('name')); ?>
				                            <?php echo $this->formInput($grade->get('name')); ?> </label> 
				                        	</section>

				                       		 <section class="col col-5">
				                       		 	 <label class="input">
				                        	<?php echo $this->formElementErrors($grade->get('description')); ?>
				                        	<?php echo $this->formInput($grade->get('description')); ?> </label>   
				                        	</section>
				                        	<section class="col col-3">  
				                        	<?php echo $this->formRow($form->get('submit')); ?>           
                        					</section>
				                        	 <?php echo $this->form()->closeTag(); ?>
				                        </div>
				            </fieldset>
									</div>
									<!-- end widget content -->	
								</div>
								<!-- end widget div -->
								
							</div>
							<!-- end widget -->
</article>



 


  <script>
  /* DO NOT REMOVE : GLOBAL FUNCTIONS!
     *
     * pageSetUp(); WILL CALL THE FOLLOWING FUNCTIONS
     *
     * // activate tooltips
     * $("[rel=tooltip]").tooltip();
     *
     * // activate popovers
     * $("[rel=popover]").popover();
     *
     * // activate popovers with hover states
     * $("[rel=popover-hover]").popover({ trigger: "hover" });
     *
     * // activate inline charts
     * runAllCharts();
     *
     * // setup widgets
     * setup_widgets_desktop();
     *
     * // run form elements
     * runAllForms();
     *
     ********************************
     *
     * pageSetUp() is needed whenever you load a page.
     * It initializes and checks for all basic elements of the page
     * and makes rendering easier.
     *
     */

    pageSetUp();
    
    /*
     * ALL PAGE RELATED SCRIPTS CAN GO BELOW HERE
     * eg alert("my home function");
     * 
     * var pagefunction = function() {
     *   ...
     * }
     * loadScript("js/plugin/_PLUGIN_NAME_.js", pagefunction);
     * 
     * TO LOAD A SCRIPT:
     * var pagefunction = function (){ 
     *  loadScript(".../plugin.js", run_after_loaded);  
     * }
     * 
     * OR you can load chain scripts by doing
     * 
     * loadScript(".../plugin.js", function(){
     *   loadScript("../plugin.js", function(){
     *     ...
     *   })
     * });
     */
    
    // pagefunction
    
    var pagefunction = function() {
        // clears the variable if left blank
    };
    
    // end pagefunction

    // destroy generated instances 
    // pagedestroy is called automatically before loading a new page
    // only usable in AJAX version!

    var pagedestroy = function(){
        
        /*
        Example below:

        $("#calednar").fullCalendar( 'destroy' );
        if (debugState){
            root.console.log("✔ Calendar destroyed");
        } 

        For common instances, such as Jarviswidgets, Google maps, and Datatables, are automatically destroyed through the app.js loadURL mechanic

        */
    }

    // end destroy
    
    // run pagefunction
    pagefunction();

</script>