

	<article class="col-xs-12 col-sm-12 col-md-8 col-lg-6">
			

							<!-- Widget ID (each widget will need unique ID)-->
							<div class="jarviswidget" id="wid-id-0">
								<!-- widget options:
									usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">
									
									data-widget-colorbutton="false"	
									data-widget-editbutton="false"
									data-widget-togglebutton="false"
									data-widget-deletebutton="false"
									data-widget-fullscreenbutton="false"
									data-widget-custombutton="false"
									data-widget-collapsed="true" 
									data-widget-sortable="false"
									
								-->
								<header>
									<h2>Add class</h2>				
									
								</header>

								<!-- widget div-->
								<div>
									
									<!-- widget edit box -->
									<div class="jarviswidget-editbox">
										<!-- This area used as dropdown edit box -->
										
										
									</div>
									<!-- end widget edit box -->
									
									<!-- widget content -->
									<div class="widget-body">
										<?php $form = $this->form;
				$form->setAttribute('action', $this->url('class',array('action'=> 'add','controller' => 'class')));
				 $form->setAttribute('role', 'form-horizontal');
        		$form->setAttribute('class', 'form-inline');
        		$form->setAttribute('id', 'classes');
				$form->prepare(); ?>
				<?php echo $this->form()->openTag($form);?>

										<div class="row"> 
											<?php echo $this->formElementErrors($form->get('section')); ?>
                                            <?php echo $this->formSelect($form->get('section')); ?>    
                                            

                                            
                                            <?php echo $this->formElementErrors($form->get('initial')); ?>
                                            <?php echo $this->formSelect($form->get('initial')); ?>  
                                           

                                            
                                            <?php echo $this->formElementErrors($form->get('arm')); ?>
                                            <?php echo $this->formSelect($form->get('arm')); ?>  
                                            

                                            
                                            <?php echo $this->formRow($form->get('submit')); ?>           
                                      
                                             <?php echo $this->form()->closeTag(); ?>
                                        
				                        </div>
									</div>
									<!-- end widget content -->	
								</div>
								<!-- end widget div -->
								
							</div>
							<!-- end widget -->
</article>

