 <div class="col-sm-9">
                                    <!-- well -->
                                    <div class="well well well-light">
                                        <div class="row">
                                            <div class="alert alert-info alert-block">
                                                <button class="close" data-dismiss="alert">
                                                    ×
                                                </button><i class="fa-fw fa fa-info"></i>
                                               Use the form below to search and view the detail of a class in a given year

                                            </div>
                                        </div>




                                        <div class="row">
                                               <form  class="smart-form"  action="/classes/student" method="post">
                                
                                         <section class="col col-4">
                                         <select class="select2" id="year" name="year">
                                            <option value="">Please select a session</option>
                                                <?php if($sessions): ?>
                                                         <?php foreach($sessions as $session): ?>
                                                            <option value="<?php echo $session['id']; ?>"><?php echo $session['name']; ?></option>
                                                        <?php endforeach; ?>
                                                     <?php endif; ?>
                                             </select>
                                        </section>
                                        <section class="col col-4">
                                         <select class="select2" id="class" name="class">
                                            <option value="">Please select a class</option>
                                                <?php if($sections): ?>
                                                         <?php foreach($sections as $section): ?>
                                                            <option value="<?php echo $section['id']; ?>"><?php echo $section['name']; ?></option>
                                                        <?php endforeach; ?>
                                                     <?php endif; ?>
                                             </select>
                                         </section>
                                         <section class="col col-2">                       

                                            <button type="submit" class="btn  btn-primary">Search</button>
                                        </section>
                               
                                    </form> 
                                </div>
                </div>
            </div>

            <script>
  /* DO NOT REMOVE : GLOBAL FUNCTIONS!
     *
     * pageSetUp(); WILL CALL THE FOLLOWING FUNCTIONS
     *
     * // activate tooltips
     * $("[rel=tooltip]").tooltip();
     *
     * // activate popovers
     * $("[rel=popover]").popover();
     *
     * // activate popovers with hover states
     * $("[rel=popover-hover]").popover({ trigger: "hover" });
     *
     * // activate inline charts
     * runAllCharts();
     *
     * // setup widgets
     * setup_widgets_desktop();
     *
     * // run form elements
     * runAllForms();
     *
     ********************************
     *
     * pageSetUp() is needed whenever you load a page.
     * It initializes and checks for all basic elements of the page
     * and makes rendering easier.
     *
     */

    pageSetUp();
    
    /*
     * ALL PAGE RELATED SCRIPTS CAN GO BELOW HERE
     * eg alert("my home function");
     * 
     * var pagefunction = function() {
     *   ...
     * }
     * loadScript("js/plugin/_PLUGIN_NAME_.js", pagefunction);
     * 
     * TO LOAD A SCRIPT:
     * var pagefunction = function (){ 
     *  loadScript(".../plugin.js", run_after_loaded);  
     * }
     * 
     * OR you can load chain scripts by doing
     * 
     * loadScript(".../plugin.js", function(){
     *   loadScript("../plugin.js", function(){
     *     ...
     *   })
     * });
     */
    
    // pagefunction
    
    var pagefunction = function() {
        // clears the variable if left blank
    };
    
    // end pagefunction

    // destroy generated instances 
    // pagedestroy is called automatically before loading a new page
    // only usable in AJAX version!

    var pagedestroy = function(){
        
        /*
        Example below:

        $("#calednar").fullCalendar( 'destroy' );
        if (debugState){
            root.console.log("✔ Calendar destroyed");
        } 

        For common instances, such as Jarviswidgets, Google maps, and Datatables, are automatically destroyed through the app.js loadURL mechanic

        */
    }

    // end destroy
    
    // run pagefunction
    pagefunction();

</script>