 <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

    <div class="jarviswidget" id="wid-id-456">

        <header>
            <h2>Add Subject Teachers</h2>
        </header><!-- widget div-->

        <div>
            <!-- widget edit box -->
            <div class="jarviswidget-editbox">
                <!-- This area used as dropdown edit box -->
                <input class="form-control" type="text">
            </div><!-- end widget edit box -->

            <!-- widget content -->
            <div class="widget-body">
                  <form id="teacher" name="teacher" class="smart-form"  action="/subject/process" method="post">
                <div class="widget-body-toolbar">
                    <div class="row">
                       
                                
                                         <section class="col col-md-5">                       
                                            <a id="dynamic" class="btn btn-sm btn-primary"><i class="glyphicon glyphicon-cloud-download"></i> New Row </a>
                                        </section>
                                         <section class="col col-md-5">                       
                                            <a id="redynamic" class="btn btn-sm btn-danger"><i class="glyphicon glyphicon-trash"></i> Remove last Row </a>
                                        </section>
                                         <section class="col col-md-2 text-right">                       
                                            <button onclick="document.getElementById('teacher').submit();" class="btn btn-sm btn-success"><i class="glyphicon glyphicon-floppy-saved"></i> Save Teachers</button>
                                        </section>
                               
                                   
                                </div>
                        
                </div> 
                    <div class="row">

                      
                               
                                    <table class="table" id="table-teacher">
                                        <tbody>
                                        <tr class="set">
                                         <td>
                                        <section class=""><label class="select"><i></i>
                                        <select class="" id="teacherx" name="teacher[]" required="required">
                                            <option value="">select teacher</option>
                                                <?php if($teachers): ?>
                                                         <?php foreach($teachers as $teacher): ?>
                                                            <option value="<?php echo $teacher['id']; ?>"><?php echo $teacher['staffno']; ?></option>
                                                        <?php endforeach; ?>
                                                     <?php endif; ?>
                                             </select> </label>
                                         </section>
                                         </td>
                                         <td>
                                         <section class="select2"> <label class="select"><i></i>
                                             <select class="" id="class" name="class[]" required="required">
                                                  <option value="">select teacher</option>
                                               <?php if($classs): ?>
                                                         <?php foreach($classs as $class): ?>
                                                        <option data-cat="<?php echo $class['s_id']; ?>"value="<?php echo $class['c_id']; ?>"><?php echo $class['c_name']; ?></option>
                                                        <?php endforeach; ?>
                                                     <?php endif; ?>
                                                 </select> </label>
                                                </section>
                                         </section>
                                         </td>
                                         <td>
                                           <section class="select2"><label class="select"><i></i>
                                             <select class="" id="subject" name="subject[]" required="required">
                                            <option value="">select subject</option>
                                                <?php if($subjects): ?>
                                                         <?php foreach($subjects as $subject): ?>
                                                            <option value="<?php echo $subject['id']; ?>"><?php echo $subject['code']; ?></option>
                                                        <?php endforeach; ?>
                                                     <?php endif; ?>
                                             </select> </label>
                                         </section>
                                         </td>                                         
                                     </tr>
                                 </tbody>
                                    </table>
                                                                        
                                </form>
                                   
                     </div>











     </div><!-- end widget content -->
        </div><!-- end widget div -->
    </div><!-- end widget -->
</article>

<script>
  /* DO NOT REMOVE : GLOBAL FUNCTIONS!
     *
     * pageSetUp(); WILL CALL THE FOLLOWING FUNCTIONS
     *
     * // activate tooltips
     * $("[rel=tooltip]").tooltip();
     *
     * // activate popovers
     * $("[rel=popover]").popover();
     *
     * // activate popovers with hover states
     * $("[rel=popover-hover]").popover({ trigger: "hover" });
     *
     * // activate inline charts
     * runAllCharts();
     *
     * // setup widgets
     * setup_widgets_desktop();
     *
     * // run form elements
     * runAllForms();
     *
     ********************************
     *
     * pageSetUp() is needed whenever you load a page.
     * It initializes and checks for all basic elements of the page
     * and makes rendering easier.
     *
     */

    pageSetUp();
    
    /*
     * ALL PAGE RELATED SCRIPTS CAN GO BELOW HERE
     * eg alert("my home function");
     * 
     * var pagefunction = function() {
     *   ...
     * }
     * loadScript("js/plugin/_PLUGIN_NAME_.js", pagefunction);
     * 
     * TO LOAD A SCRIPT:
     * var pagefunction = function (){ 
     *  loadScript(".../plugin.js", run_after_loaded);  
     * }
     * 
     * OR you can load chain scripts by doing
     * 
     * loadScript(".../plugin.js", function(){
     *   loadScript("../plugin.js", function(){
     *     ...
     *   })
     * });
     */
    
    // pagefunction
    
    var pagefunction = function() {
        // clears the variable if left blank

                            $("#dynamic").click(function() {
 $('#table-teacher tbody>tr:last')
    .clone(true)
    .insertAfter('#table-teacher tbody>tr:last').hide().fadeIn().find('input').each(function(){
        $(this).val('');
    });
});


  $("#redynamic").click(function() {
 $('#table-teacher tbody>tr:last-child')
    .remove()
  
    });  

    };
    
    // end pagefunction

    // destroy generated instances 
    // pagedestroy is called automatically before loading a new page
    // only usable in AJAX version!

    var pagedestroy = function(){
        
        /*
        Example below:

        $("#calednar").fullCalendar( 'destroy' );
        if (debugState){
            root.console.log("✔ Calendar destroyed");
        } 

        For common instances, such as Jarviswidgets, Google maps, and Datatables, are automatically destroyed through the app.js loadURL mechanic

        */
    }

    // end destroy
    
    // run pagefunction
    pagefunction();

</script>