
<article class="col-sm-12 col-md-12 col-lg-10">
				
							<!-- Widget ID (each widget will need unique ID)-->
							<div class="jarviswidget" id="wid-id-24" data-widget-deletebutton="false">
								<!-- widget options:
								usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">
				
								data-widget-colorbutton="false"
								data-widget-editbutton="false"
								data-widget-togglebutton="false"
								data-widget-deletebutton="false"
								data-widget-fullscreenbutton="false"
								data-widget-custombutton="false"
								data-widget-collapsed="true"
								data-widget-sortable="false"
				
								-->
								<header>
									<span class="widget-icon"> <i class="fa fa-edit"></i> </span>
									<h2>Subjects</h2>
				
								</header>
				
								<!-- widget div-->
								<div>
				
									<!-- widget edit box -->
									<div class="jarviswidget-editbox">
										<!-- This area used as dropdown edit box -->
				
									</div>
									<!-- end widget edit box -->
				
									<!-- widget content -->
									<div class="widget-body">
										<div class="widget-body-toolbar">
											
											<div class="row">
												
												<div class="col-xs-9 col-sm-5 col-md-5 col-lg-5">
													
                    
        												<div class="input-group">
														<span class="input-group-addon"><i class="fa fa-search"></i></span>
														<input class="form-control" id="searchTerm" value="" placeholder="Filter" type="text" name="searchTerm"/>
													</div>
												</div>
												<div class="col-xs-3 col-sm-7 col-md-7 col-lg-7 text-right">
													
													
													<a data-toggle="modal" data-target="#edit" href="<?php echo $this->url('subject',array('controller' => 'subject','action'=>'add'));?>" class="btn btn-primary">
                                                        <i class="fa fa-plus"></i> <span class="hidden-mobile">Add New Subject</span>
                                                    </a>

													
													
												</div>
												
											</div>
											
												

										</div>
										
											<table id="subject" data-show-export="true" data-pagination="true" data-click-to-select="true"  data-show-refresh="true" data-show-toggle="true" data-show-columns="true" data-search="true" data-select-item-name="toolbar1" class="table table-bordered table-hover">
                        						<thead>
                           						 <tr>
					                                <th data-sortable="true">Name</th>
					                                <th>Code</th>
					                                <th>Description</th>					                                
					                                <th>Action</th>
					                            </tr>
					                        </thead>
					                        
						                        <tbody><?php if($subjects):?>
						                        	<?php foreach ($subjects as $subject) : ?>
						                            <tr>
						                    <td><?php echo $this->escapeHtml($subject->getName());?></td>
						                    <td><?php echo $this->escapeHtml($subject->getCode());?></td>
						                    <td><?php echo $this->escapeHtml($subject->getDescription());?></td>
						                    
						                    <td>
 
 <a  data-toggle="modal"  data-target="#edit" href="<?php echo $this->url('subject',array('controller' => 'subject','action'=>'edit', 'id' => $subject->getid()));?>"><button type="button" class="btn btn-xs btn-info"><i class="fa fa-pencil-square-o"></i></button></a>  

<a id="conf" href="<?php echo $this->url('subject',array('controller' => 'subject','action'=>'delete', 'id' => $subject->getid()));?>"onclick="return confirm('Do you rely want to delete this subject?')"><button class="btn btn-xs btn-danger"><i class='glyphicon glyphicon-trash'></i></button></a>
                    						</td>                                                        
						                        </tr><?php endforeach; ?><?php endif;?>
						                        </tbody>
						                    </table>
									</div>
									<!-- end widget content -->
									
								</div>
								<!-- end widget div -->
				
							</div>

	</article>



<div class="modal fade" id="edit" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content" style="width:600px;">
            
           
                        </div><!-- /.modal-content -->
                    </div><!-- /.modal-dialog -->
                </div><!-- /.modal -->
<script>
  /* DO NOT REMOVE : GLOBAL FUNCTIONS!
     *
     * pageSetUp(); WILL CALL THE FOLLOWING FUNCTIONS
     *
     * // activate tooltips
     * $("[rel=tooltip]").tooltip();
     *
     * // activate popovers
     * $("[rel=popover]").popover();
     *
     * // activate popovers with hover states
     * $("[rel=popover-hover]").popover({ trigger: "hover" });
     *
     * // activate inline charts
     * runAllCharts();
     *
     * // setup widgets
     * setup_widgets_desktop();
     *
     * // run form elements
     * runAllForms();
     *
     ********************************
     *
     * pageSetUp() is needed whenever you load a page.
     * It initializes and checks for all basic elements of the page
     * and makes rendering easier.
     *
     */

    pageSetUp();
    
    /*
     * ALL PAGE RELATED SCRIPTS CAN GO BELOW HERE
     * eg alert("my home function");
     * 
     * var pagefunction = function() {
     *   ...
     * }
     * loadScript("js/plugin/_PLUGIN_NAME_.js", pagefunction);
     * 
     * TO LOAD A SCRIPT:
     * var pagefunction = function (){ 
     *  loadScript(".../plugin.js", run_after_loaded);  
     * }
     * 
     * OR you can load chain scripts by doing
     * 
     * loadScript(".../plugin.js", function(){
     *   loadScript("../plugin.js", function(){
     *     ...
     *   })
     * });
     */
    
    // pagefunction
    
   var pagefunction = function() {
        // clears the variable if left blank
        $('#subject').bootstrapTable({

            });
    };
     loadScript("/bot/bootstrap-table.js");
    // end pagefunction

    // destroy generated instances 
    // pagedestroy is called automatically before loading a new page
    // only usable in AJAX version!

    var pagedestroy = function(){
        
        /*
        Example below:

        $("#calednar").fullCalendar( 'destroy' );
        if (debugState){
            root.console.log("✔ Calendar destroyed");
        } 

        For common instances, such as Jarviswidgets, Google maps, and Datatables, are automatically destroyed through the app.js loadURL mechanic

        */
    }

    // end destroy
    
    // run pagefunction
    pagefunction();

</script>