<article class="col-xs-12 col-sm-6 col-md-10 col-lg-12">
<div class="jarviswidget jarviswidget-color-blueDark" id="wid-id-17659" data-widget-deletebutton="false" style="margin-left:10%; margin-right:10%">
        <!-- widget options:
        usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">
        data-widget-colorbutton="false" 
        data-widget-editbutton="false"
        data-widget-togglebutton="false"
        data-widget-deletebutton="false"
        data-widget-fullscreenbutton="false"
        data-widget-custombutton="false"
        data-widget-collapsed="true" 
        data-widget-sortable="false"   
                                -->
             <header>
                <h2><strong>Subject Teachers</strong></h2>               
             </header>
                <!-- widget div-->
    <div>       
       <!-- widget edit box -->
         <div class="jarviswidget-editbox">
            <!-- This area used as dropdown edit box -->
            <input class="form-control" type="text">
            <span class="note"><i class="fa fa-check text-success"></i> Change title to update and save instantly!</span>      
          </div>
                <!-- end widget edit box -->
                <!-- widget content -->
            <div class="widget-body ">
                <div class="widget-body-toolbar"> 
                    
                    
                
                </div>
                                        
               
    <table id="teacher-table" data-toggle="table" data-pagination="true" data-click-to-select="true"  data-show-refresh="true" data-show-toggle="true" data-show-columns="true" data-search="true" class="table table-bordered table-hover">
                        <thead>
                            <tr>
                                <th data-sortable="true">Session</th>
                                <th data-sortable="true">Class</th>
                                <th data-sortable="true">Subject</th>
                                <th data-sortable="true">Teacher</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php if($teachers):?>
                            <?php foreach ($teachers as $teacher) : ?>
                            <tr>
                    <td><?php echo $this->escapeHtml($teacher['y_name']. ' - ' .$teacher['te_name']);?></td>
                    <td><?php echo $this->escapeHtml($teacher['c_name']);?></td>
                    <td><?php echo $this->escapeHtml($teacher['sb_name']);?></td>
                    <td><?php echo $this->escapeHtml($teacher['s_fname'].'-'.$teacher['s_lname']);?></td>
                        </tr><?php endforeach; ?><?php endif;?>
                        </tbody>
                    </table>
                
        
          </div>
                                    <!-- end widget content --> 
        </div>
        <!-- end widget div -->   
    </div>
    <!-- end widget -->
</article>

<script type="text/javascript">
    
    /* DO NOT REMOVE : GLOBAL FUNCTIONS!
     *
     * pageSetUp(); WILL CALL THE FOLLOWING FUNCTIONS
     *
     * // activate tooltips
     * $("[rel=tooltip]").tooltip();
     *
     * // activate popovers
     * $("[rel=popover]").popover();
     *
     * // activate popovers with hover states
     * $("[rel=popover-hover]").popover({ trigger: "hover" });
     *
     * // activate inline charts
     * runAllCharts();
     *
     * // setup widgets
     * setup_widgets_desktop();
     *
     * // run form elements
     * runAllForms();
     *
     ********************************
     *
     * pageSetUp() is needed whenever you load a page.
     * It initializes and checks for all basic elements of the page
     * and makes rendering easier.
     *
     */

    pageSetUp();
    
    /*
     * ALL PAGE RELATED SCRIPTS CAN GO BELOW HERE
     * eg alert("my home function");
     * 
     * var pagefunction = function() {
     *   ...
     * }
     * loadScript("js/plugin/_PLUGIN_NAME_.js", pagefunction);
     * 
     * TO LOAD A SCRIPT:
     * var pagefunction = function (){ 
     *  loadScript(".../plugin.js", run_after_loaded);  
     * }
     * 
     * OR you can load chain scripts by doing
     * 
     * loadScript(".../plugin.js", function(){
     *   loadScript("../plugin.js", function(){
     *     ...
     *   })
     * });
     */
    
    // pagefunction
    
    var pagefunction = function() {
        // clears the variable if left blank
        $('#teacher-table').bootstrapTable({

            });
    };
     loadScript("/bot/bootstrap-table.js");
    
    // end pagefunction

    // destroy generated instances 
    // pagedestroy is called automatically before loading a new page
    // only usable in AJAX version!

    var pagedestroy = function(){
        
    }

    // end destroy
    
    // run pagefunction
    pagefunction();
    
</script>