 <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

    <div class="jarviswidget" id="wid-id-0">

        <header>
            <h2>Mark Attendance</h2>
        </header><!-- widget div-->

        <div>
            <!-- widget edit box -->
            <div class="jarviswidget-editbox">
                <!-- This area used as dropdown edit box -->
                <input class="form-control" type="text">
            </div><!-- end widget edit box -->

            <!-- widget content -->
            <div class="widget-body">
                <div class="widget-body-toolbar">
                    <div class="row">
                        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                      <form  class="smart-form"  action="/attendance/rollcall" method="post">
                                
                                         <section class="col col-sm-4"><label class="select"><i></i>
                                         <select class="select2" id="sectionx" name="sectionx">
                                            <option value="">select section</option>
                                                <?php if($sections): ?>
                                                         <?php foreach($sections as $section): ?>
                                                            <option value="<?php echo $section['id']; ?>"><?php echo $section['name']; ?></option>
                                                        <?php endforeach; ?>
                                                     <?php endif; ?>
                                             </select> </label>
                                        </section>
                                        <section class="col col-sm-4"><label class="select"><i></i>
                                         <select class="select2" id="classx" name="classx">
                                            <option value="">select class</option>
                                               
                                             </select> </label>
                                         </section>
                                         
                                         <section class="col col-sm-2">                       
                                            <button type="submit" class="btn btn-sm btn-primary"><i class="glyphicon glyphicon-cloud-download"></i> Load</button>
                                        </section>
                                       </form> 
                                         <section class="col col-sm-2">                       
                                            <button onclick="document.getElementById('attendform').submit();" class="btn btn-sm btn-success"><i class="glyphicon glyphicon-floppy-saved"></i> Save Roll Call</button>
                                        </section>
                               
                                     
                                </div>
                                </div>

                </div> 


<form id="attendform" action="/attendance/process" method="post" class="smart-form">

    <table  class="table table-bordered hideFullColumn">
                        <thead> 
                            <tr>
                                <th class="hidecol">Id</th>
                                 <th class="hidecol">Class</th>
                                 <th class="hidecol">Section</th>
                                <th>Photo</th>
                                <th>Admission No</th>
                                <th>Name</th>
                                <th>Class</th>
                                <th>Status</th>
                                <th>Reason</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php if($attends):?>         
                    <?php foreach ($attends as $attend) : ?>
                            <tr>
<td class="hidecol" ><label class="input"><input type="text" name="id[]" value="<?php if($attend['s_id']){echo $attend['s_id'];};?>"></label></td><td class="hidecol" ><label class="input"><input type="text" name="class[]" value="<?php if($attend['c_id']){echo $attend['c_id'];};?>"></label></td>
<td class="hidecol" ><label class="input"><input type="text" name="section[]" value="<?php if($attend['se_id']){echo $attend['se_id'];};?>"></label></td>
              

<td style="width:10%;"><img src="<?php echo $this->basePath?>/data/uploads/students/<?php if($attend['s_image']) {echo $attend['s_image'];};?>" alt="student pic" style="max-width:30px; border:2px solid #FFF;"></td>
          <td style="width:15%;"><?php if($attend['s_admNo']){echo $attend['s_admNo'];};?></td>
         <td><?php if($attend['p_fname'] && $attend['p_lname'] && $attend['p_mname']){echo $attend['p_fname'] .' ' .$attend['p_lname'] . ' ' .$attend['p_mname'] ;};?></td>
          <td style="width:15%;"><?php if($attend['c_name']){echo $attend['c_name'];};?></td>
                            
 <td style="width:15%;" ><label class="select"><i></i>
                                         <select class="select2"  name="status[]" required="required">
                                            <option value="present">present</option>
                                            <option value="absent">absent</option>
                                            <option value="late">late</option>
                                             </select> </label></td>
 <td style="width:15%;"><label class="input"><input type="text" name="reason[]" value=""></label></td>
 
                            </tr> 
                           <?php endforeach; ?><?php endif;?>
                        </tbody>
                    </table>
                                        
                                       
</form>








     </div><!-- end widget content -->
        </div><!-- end widget div -->
    </div><!-- end widget -->
</article>

<div class="modal fade" id="items" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content" style="width:900px;">
            
           
                        </div><!-- /.modal-content -->
                    </div><!-- /.modal-dialog -->
                </div><!-- /.modal -->

                <script>
  /* DO NOT REMOVE : GLOBAL FUNCTIONS!
     *
     * pageSetUp(); WILL CALL THE FOLLOWING FUNCTIONS
     *
     * // activate tooltips
     * $("[rel=tooltip]").tooltip();
     *
     * // activate popovers
     * $("[rel=popover]").popover();
     *
     * // activate popovers with hover states
     * $("[rel=popover-hover]").popover({ trigger: "hover" });
     *
     * // activate inline charts
     * runAllCharts();
     *
     * // setup widgets
     * setup_widgets_desktop();
     *
     * // run form elements
     * runAllForms();
     *
     ********************************
     *
     * pageSetUp() is needed whenever you load a page.
     * It initializes and checks for all basic elements of the page
     * and makes rendering easier.
     *
     */

    pageSetUp();
    
    /*
     * ALL PAGE RELATED SCRIPTS CAN GO BELOW HERE
     * eg alert("my home function");
     * 
     * var pagefunction = function() {
     *   ...
     * }
     * loadScript("js/plugin/_PLUGIN_NAME_.js", pagefunction);
     * 
     * TO LOAD A SCRIPT:
     * var pagefunction = function (){ 
     *  loadScript(".../plugin.js", run_after_loaded);  
     * }
     * 
     * OR you can load chain scripts by doing
     * 
     * loadScript(".../plugin.js", function(){
     *   loadScript("../plugin.js", function(){
     *     ...
     *   })
     * });
     */
    
    // pagefunction
    
    var pagefunction = function() {

          $("#sectionx").change(function(){
    var state = $("#sectionx").val();
    var myData = {state: state};
    //The post using ajax
      $.ajax({
              type:"POST",
              url:"/result/class",
              data:myData,
              success: function(data){
                                 
                             var st=""
             for(i in data){
                st+="<option id='"+data[i].id+"'>"+data[i].name+"</option>"
              }
               $("#classx").html(st);

              },
         
             });
  });


         $("#classx").change(function(){
    var state = $("#classx").val();
    var myData = {state: state};
    //The post using ajax
      $.ajax({
              type:"POST",
              url:"/result/student",
              data:myData,
              success: function(data){
                                 
                             var st=""
             for(i in data){
                st+="<option id='"+data[i].id+"'>"+data[i].admNo+"</option>"
              }
               $("#studentx").html(st);

              },
         
             });
  });

    };
    
    //loadScript("js/edusoft.js", pagefunction);
    // end pagefunction

    // destroy generated instances 
    // pagedestroy is called automatically before loading a new page
    // only usable in AJAX version!

    var pagedestroy = function(){
        
        /*
        Example below:

        $("#calednar").fullCalendar( 'destroy' );
        if (debugState){
            root.console.log("✔ Calendar destroyed");
        } 

        For common instances, such as Jarviswidgets, Google maps, and Datatables, are automatically destroyed through the app.js loadURL mechanic

        */
    }

    // end destroy
    
    // run pagefunction
    pagefunction();

</script>