<div class="row">
<div id="printdiv" class="col-sm-12">


<div class="well well well-sm well-light">
   
        <?php if($total):?>

            <div class="row">
                        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                        <p class="text-center font-xl"><strong>BRAINFIELD INTERNATIONAL SCHOOL</strong></p>
                         <p class="text-center font-xs"><strong>Address:</strong>Along Massallachi Idi Road, Onarikpa, Angwan Waje Shabu, Lafia Nasarawa State.</p>
                          <p class="text-center font-xs"><strong>Tel:</strong>08024939205, 08039151466.</p>
                          <p class="text-center font-xl"><strong>FEE RECEIPT</strong></p>
                        </div>
                </div>
                 <div class="row" style="margin-bottom:5px; padding:5px; ">
                                   
                         <div class="col col-sm-2">
                            <img src="<?php echo $this->basePath?>/data/uploads/students/<?php echo  $total->getFeeStudent()->getStudent()->getImage();?>" alt="staff pic" style="max-width:85px; border:5px solid #fff;"/>
                         </div>
                         <div class="col col-sm-10">
                            <table class="ptable">
                                <tbody>
                                    <tr>
                                <td style="background">Name:</td>
                                <td><?php echo $total->getFeeStudent()->getStudent()->getPerson()->getFname(). ' ' .$total->getFeeStudent()->getStudent()->getPerson()->getLname(). ' ' .$total->getFeeStudent()->getStudent()->getPerson()->getMname();?></td> 
                                <?php $sessions=$this->myHelper();
         if(!empty($sessions)){
            foreach ($sessions as $session):
           $year = $this->escapeHtml($session['year']['name']);
           $term = $this->escapeHtml($session['term']['name']);
           endforeach;}?>
                                <td>Year:</td>
                                <td><?php echo $year;?></td>                    
                                    </tr>
                                    <tr>
                                <td>Admission No:</td>
                                <td> <?php echo $total->getFeeStudent()->getStudent()->getAdmNo();?></td>
                                <td>Term:</td>
                                <td><?php echo $term;?></td>  
                                    </tr>
                                    <tr>
                                <td>Class:</td>
                                <td><?php echo $total->getFeeStudent()->getStudent()->getCurrentClass()->getName();?></td>
                                <td>Section:</td>
                                <td><?php echo$total->getFeeStudent()->getStudent()->getSection()->getName();?></td>
                                    </tr>
                                </tbody>
                            </table>
                         </div>
            </div>

        <div class="row">
           <div class="col col-sm-12">
            <span class="text-center font-md">TRANSACTION DETAILS</span>
           </div>
        </div>
 
        <div class="row">
            <div class="col col-sm-12">

                      <table class="table table-bordered">
                        
                            <tr>
                                <th>Method of Payment</th>
                                <th>Receipt No</th>
                                <th>Date of Payment</th>
                                <th>Amount</th>
                                <th style="display:none;">Action</th>
                           </tr>
                           <?php if($transactions):?>
                       <?php foreach ($transactions as $transaction) : ?>
                        <tbody>
                            <tr>
                    
                       <td><?php echo $transaction['p_method'];?></td>
                       <td><?php echo $transaction['p_receipt'];?></td>
                       <td><?php echo $transaction['p_dop'];?></td>
                       <td><?php echo $transaction['p_amount'];?></td>
                       <td style="display:none;">
 <a  data-toggle="modal" data-target="#edit" href="<?php echo $this->url('collection',array('controller' => 'feecollection','action'=>'edittransaction', 'id' =>$transaction['p_id']));?>"><button type="button" class="btn btn-xs btn-info"><i class="fa fa-pencil-square-o">Edit</i></button></a>


 <a  href="<?php echo $this->url('collection',array('controller' => 'feecollection','action'=>'deletetransaction', 'id' => $transaction['s_id']));?>"><button type="button" class="btn btn-xs btn-danger"><i class="glyphicon glyphicon-trash"></i>Delete</button></a> 

                       </td>                                                                                                                              
                           </tr>  <?php endforeach; ?>
                   <?php endif;?>
                    
                     <tr>
        
                       <td colspan="3"><strong>Total Payment</strong></td>
                       <td><strong><?php echo $total->getAmount();?></strong></td>                                          
                           </tr>
                        </tbody>
                   
                    </table>

            </div>                                                

        </div>
        <div class="row">
           <div class="col col-sm-4">
           <strong><label class="bg-color-blue txt-color-white">SECTION FEE:</label> <?php echo $total->getSectionFee();?></strong>
           </div>
           <div class="col col-sm-4">
             <strong><label class="bg-color-green txt-color-white">PAID:</label> <?php echo $total->getAmount();?></strong>
           </div>
           <div class="col col-sm-4">
             <strong><label class="bg-color-red txt-color-white">BALANCE:</label> <?php echo $bal=$total->getSectionFee()- $total->getAmount();?><strong>
           </div>
           <div class="col col-sm-4">
            <button id="print" class="btn btn-success"><i class="fa fa-print"></i> PRINT</button>
           </div>
        </div>
        <?php endif;?>
</div>
</div>
</div>

<script type="text/javascript">
    
    /* DO NOT REMOVE : GLOBAL FUNCTIONS!
     *
     * pageSetUp(); WILL CALL THE FOLLOWING FUNCTIONS
     *
     * // activate tooltips
     * $("[rel=tooltip]").tooltip();
     *
     * // activate popovers
     * $("[rel=popover]").popover();
     *
     * // activate popovers with hover states
     * $("[rel=popover-hover]").popover({ trigger: "hover" });
     *
     * // activate inline charts
     * runAllCharts();
     *
     * // setup widgets
     * setup_widgets_desktop();
     *
     * // run form elements
     * runAllForms();
     *
     ********************************
     *
     * pageSetUp() is needed whenever you load a page.
     * It initializes and checks for all basic elements of the page
     * and makes rendering easier.
     *
     */

    pageSetUp();
    
    /*
     * ALL PAGE RELATED SCRIPTS CAN GO BELOW HERE
     * eg alert("my home function");
     * 
     * var pagefunction = function() {
     *   ...
     * }
     * loadScript("js/plugin/_PLUGIN_NAME_.js", pagefunction);
     * 
     * TO LOAD A SCRIPT:
     * var pagefunction = function (){ 
     *  loadScript(".../plugin.js", run_after_loaded);  
     * }
     * 
     * OR you can load chain scripts by doing
     * 
     * loadScript(".../plugin.js", function(){
     *   loadScript("../plugin.js", function(){
     *     ...
     *   })
     * });
     */
    
    // pagefunction
    
    var pagefunction = function() {
       $("#print").click(function() {
// Print the DIV.
  $("#printdiv").print({
            globalStyles: true,
            mediaPrint: false,
            stylesheet: null,
            noPrintSelector: ".no-print",
            iframe: false,
            append: null,
            prepend: null,
            manuallyCopyFormValues: true,
            deferred: $.Deferred(),
            timeout: 250
    });
//return (false);
});
    };

        loadScript("/js/jquery.print.js");
   
    
    // end pagefunction

    // destroy generated instances 
    // pagedestroy is called automatically before loading a new page
    // only usable in AJAX version!

    var pagedestroy = function(){
        
  
    }

    // end destroy
    
    // run pagefunction
    pagefunction();
    
</script>
