<article class="col-sm-12">							
							<!-- Widget ID (each widget will need unique ID)-->
		

							<!-- Widget ID (each widget will need unique ID)-->
							<div class="jarviswidget" id="wid-id-18" >
								<!-- widget options:
									usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">
									
									data-widget-colorbutton="false"	
									data-widget-editbutton="false"
									data-widget-togglebutton="false"
									data-widget-deletebutton="false"
									data-widget-fullscreenbutton="false"
									data-widget-custombutton="false"
									data-widget-collapsed="true" 
									data-widget-sortable="false"
									
								-->
								<header style="color:#fff; background:#274A80;">
									<span class="widget-icon"><i class="glyphicon glyphicon-tasks"></i></span><h2><strong>Student payment history</strong></h2>			
									
								</header>

								<!-- widget div-->
								<div>
									
									<!-- widget edit box -->
									<div class="jarviswidget-editbox">
										<!-- This area used as dropdown edit box -->
										<input class="form-control" type="text">
										<span class="note"><i class="fa fa-check text-success"></i> Change title to update and save instantly!</span>
										
									</div>
									<!-- end widget edit box -->
									
									<!-- widget content -->
									<div class="widget-body">

										<div class="row">
				
											<div class="col-sm-12">
										<div class="widget-body-toolbar">
											
											<div class="row">
												
												<div class="col-xs-9 col-sm-5 col-md-5 col-lg-5">
													
                    
        												<div class="input-group">
														<span class="input-group-addon"><i class="fa fa-search"></i></span>
														<input class="form-control" id="searchTerm" value="" placeholder="Filter" type="text" name="searchTerm"/>
													</div>
												</div>
												
											</div>
											
												

										</div>
										
										<div class="custom-scroll table-responsive">
											

											<table class="table table-bordered">
													<thead> 
							<tr>
								<th>Session</th>
								<th><span class="font-sm label label-info"># Section Fee</span></th>
								<th><label class="font-sm label label-success"># Total Payment</label></th>
								<th><label class="font-sm label label-danger"># Balance</label></th>
								<th>Action </th>
							</tr>
						</thead>
						<tbody><?php if($feetotals):?>
					<?php foreach ($feetotals as $feetotal) : ?>
							<tr>
							<td><?php echo $this->escapeHtml($feetotal['y_name'].' - '.$feetotal['t_name']);?></td>
							<td><?php echo $this->escapeHtml($feetotal['fst_sectionFee']);?></td>
							<td><?php echo $this->escapeHtml($feetotal['fst_amount']);?></td>
							<td><?php $bal=$feetotal['fst_sectionFee'] - $feetotal['fst_amount']; echo $bal;?></td>
						    <td>

 <a  data-dismiss="modal" data-toggle="modal" data-target="#itemsx" href="<?php echo $this->url('collection',array('controller' => 'feecollection','action'=>'transaction', 'id' => $feetotal['fs_id']));?>"><button type="button" class="btn btn-xs btn-info">view transactions</button></a>

 <a  href="<?php echo $this->url('collection',array('controller' => 'feecollection','action'=>'delete', 'id' => $feetotal['fs_id']));?>"><button type="button" class="btn btn-xs btn-info">Delete</button></a>    

					 

							</td>
							</tr>
							
						<?php endforeach; ?>
													
								<?php endif;?>					
					
												</tbody>
											</table>
										</form>
										</div>
										
										
									
									</div>
									
	
									</div>

									
									
								</div>
								<!-- end widget div -->
								
							</div>
							<!-- end widget -->
				

						</article>


						<!-- MODAL FOR EDITING ACADEMIC SESSION -->

						<!-- end widget div -->
<div class="modal fade" id="items" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content" style="width:900px;">
            
           
                        </div><!-- /.modal-content -->
                    </div><!-- /.modal-dialog -->
                </div><!-- /.modal -->
<!-- END OF MODAL FOR EDITING ACADEMIC SESSION-->
						<!-- end widget div -->
<div class="modal fade" id="edit" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content" style="width:900px;">
            
           
                        </div><!-- /.modal-content -->
                    </div><!-- /.modal-dialog -->
                </div><!-- /.modal -->
<!-- END OF MODAL FOR EDITING ACADEMIC SESSION-->