	









<article class="col-sm-12 col-md-6 col-lg-4">
				
							<!-- Widget ID (each widget will need unique ID)-->
							<div class="jarviswidget" id="wid-id-4" data-widget-colorbutton="false" data-widget-editbutton="false" data-widget-custombutton="false">
								<!-- widget options:
								usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">
				
								data-widget-colorbutton="false"
								data-widget-editbutton="false"
								data-widget-togglebutton="false"
								data-widget-deletebutton="false"
								data-widget-fullscreenbutton="false"
								data-widget-custombutton="false"
								data-widget-collapsed="true"
								data-widget-sortable="false"
				
								-->
								<header>
									<span class="widget-icon"> <i class="fa fa-edit"></i> </span>
									<h2>Create pins</h2>
				
								</header>
				
								<!-- widget div-->
								<div>
				
									<!-- widget edit box -->
									<div class="jarviswidget-editbox">
										<!-- This area used as dropdown edit box -->
				
									</div>
									<!-- end widget edit box -->
				
									<!-- widget content -->
									<div class="widget-body">
										
				
									<?php $form = $this->form;
									$form->setAttribute('action', $this->url('applicationpins',array('action'=> 'create','controller' => 'applicationpins')));
									 $form->setAttribute('role', 'form-horizontal');
                        			//$form->setAttribute('class', 'form-inline');
									$form->prepare();?>
												<?php echo $this->form()->openTag($form); ?>		
				
												<section class="col-6">
													<label style="font-size:16px;">Quantity</label>
													<div class="input-group">
														<?php echo $this->formInput($form->get('quantity')); ?>
													</div>
												</section>
												
												<section class="col-6">
													<label style="font-size:16px;">Section</label>
													<div class="input-group">
														<?php echo $this->formSelect($form->get('section')); ?>
													</div>
												</section>
				
													<div class="row">
														<div style="padding:10px;" class="col-md-12 text-right">
															
															<?php echo $this->formRow($form->get('submit')); ?>
															<?php echo $this->form()->closeTag(); ?>
														</div>
													</div>
								
				
									</div>
									<!-- end widget content -->
				
								</div>
								<!-- end widget div -->
				
							</div>
	</article>