<div class="row">
<div class="col-sm-12">


<div class="well well well-sm well-light">
    <div style="border-color:#B9CEEC; border-width:2px 0px 0px; margin-top:8px; margin-bottom:15px;">
        <div class="alert alert-info alert-block">
                                                <button class="close" data-dismiss="alert">
                                                    ×
                                                </button><i class="fa-fw fa fa-info"></i>
                                             

                                            </div>
        </div>
 
        <div class="row">
            <div class="col col-sm-12">

                      <table class="table table-bordered">
                        
                            <tr>
                                <th>Method of Payment</th>
                                <th>Receipt No</th>
                                <th>Date of Payment</th>
                                <th>Amount</th>
                           </tr>
                           <?php if($transactions):?>
                       <?php foreach ($transactions as $transaction) : ?>
                        <tbody>
                            <tr>
                    
                       <td><?php echo $transaction['p_method'];?></td>
                       <td><?php echo $transaction['p_receipt'];?></td>
                       <td><?php echo $transaction['p_dop'];?></td>
                       <td><?php echo $transaction['p_amount'];?></td>
                                                                                                                                                   
                           </tr>  <?php endforeach; ?>
                   <?php endif;?>
                    <?php if($total):?>
                     <tr>
        
                       <td colspan="3"><strong>Total Payment</strong></td>
                       <td><strong><?php echo $total->getAmount();?></strong></td>                                          
                           </tr>
                        </tbody>
                   <?php endif;?>
                    </table>

            </div>

                                                 

        </div>
</div>
</div>
</div>