<?php /* @var $user \EduUser\Entity\User */?>
<article class="col-md-12">                         
                            <!-- Widget ID (each widget will need unique ID)-->
              <!-- Widget ID (each widget will need unique ID)-->
                            <div class="jarviswidget" id="wid-id-18" >
                            
                            
                                <header style="color:#fff; background:#274A80;">
                                    <span class="widget-icon"><i class="glyphicon glyphicon-tasks"></i></span><h2><strong>System Users</strong></h2>           
                                    
                                </header>

                                <!-- widget div-->
                                <div>
                                    
                                    <!-- widget edit box -->
                                    <div class="jarviswidget-editbox">
                                        <!-- This area used as dropdown edit box -->
                                        <input class="form-control" type="text">
                                        <span class="note"><i class="fa fa-check text-success"></i> Change title to update and save instantly!</span>
                                        
                                    </div>
                                    <!-- end widget edit box -->
                                    
                                    <!-- widget content -->
                                    <div class="widget-body">

                                        <div class="row">
                
                                            <div class="col-md-12">
                                        <div class="widget-body-toolbar">
                                            
                                            <div class="row">
                                                
                                                <div class="col-xs-9 col-sm-5 col-md-5 col-lg-5">
                                               
                                                </div>
                                                

                                            <div class="col-xs-3 col-sm-7 col-md-7 col-lg-7 text-right">
                                            <ul class="nav navbar-nav navbar-right">
                                           
                                            <li class="dropdown">
                                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">New Users<span class="caret"></span></a>
                                                <ul class="dropdown-menu" role="menu">
                                                     <li>
                                                        <a data-toggle="modal" data-target="#edit" href="<?php echo $this->url('crud', array('action' => 'addstudent')); ?>">
                                                        <i class="fa fa-plus"></i> <span class="hidden-mobile">New Student</span>
                                                        </a>
                                                    </li>
                                                    <li class="divider"></li>
                                                    <li>
                                                        <a data-toggle="modal" data-target="#edit" href="<?php echo $this->url('crud', array('action' => 'addguardian')); ?>">
                                                        <i class="fa fa-plus"></i> <span class="hidden-mobile">New Guardian</span>
                                                        </a>
                                                    </li>
                                                    <li class="divider"></li>
                                                    <li>
                                                        <a  <a data-toggle="modal" data-target="#edit" href="<?php echo $this->url('crud', array('action' => 'addstaff')); ?>">
                                                        <i class="fa fa-plus"></i> <span class="hidden-mobile">New Staff</span>
                                                        </a>
                                                    </li>
                                                    <li class="divider"></li>
                                                    <li>
                                                        <a data-toggle="modal" data-target="#edit" href="<?php echo $this->url('crud', array('action' => 'new')); ?>">
                                                        <i class="fa fa-plus"></i> <span class="hidden-mobile">New Admin</span>
                                                        </a>
                                                    </li>
                                                    
                                                </ul>
                                            </li>
                                        </ul>
                                           
                                                    
                                                </div>
                                                
                                            </div>
                                            
                                                

                                        </div>
                                        
                                        <div class="custom-scroll table-responsive">
                                            

                                            <table id="userstable"  data-show-export="true" data-pagination="true" data-click-to-select="true" data-show-refresh="true" data-show-toggle="true" data-show-columns="true" data-search="true" data-select-item-name="toolbar1" class="table table-bordered table-hover">
                                                    <thead> 
                            <tr>
                                <th>Name</th>
                                <th>Username</th>
                                <th>Email</th>
                                <th>Role</th>
                                <th>Edit</th>
                                <th>Remove</th>
                               
                            </tr>
                        </thead>
                        <tbody><?php if($users):?>
                    <?php foreach ($users as $user) : ?>
                        <tr>
                            <td> <?php echo $user['u_displayName'];?></td>
                            <td><?php echo $user['u_username'];?></td>
                            <td><?php echo $user['u_email'];?></td>
                             <td><?php echo $user['r_roleId'];?></td>
                           
                                   <td>
<button type="button" class="btn btn-xs btn-info"><i class="fa fa-pencil-square-o"></i> Edit</button>
                            </td>
                            <td>
<button type="button" class="btn btn-xs btn-danger">
  <i class="glyphicon glyphicon-trash"></i> Remove</button>
                            </td>
                        </tr>
                            
                        <?php endforeach; ?>
                        <?php endif;?>                              
                                                </tbody>
                                            </table>
                                        </div>
                                        
                                        
                                    
                                    </div>
                                    
    
                                    </div>


                                </div>
                                <!-- end widget div -->
                                
                            </div>
                            <!-- end widget -->

                        </article>
<div class="modal fade" id="itemsx" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content" style="width:900px;">
            
           
                        </div><!-- /.modal-content -->
                    </div><!-- /.modal-dialog -->
                </div><!-- /.modal -->

<div class="modal fade" id="items" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content" style="width:400px;">
            
           
                        </div><!-- /.modal-content -->
                    </div><!-- /.modal-dialog -->
                </div><!-- /.modal -->
                        <!-- MODAL FOR EDITING ACADEMIC SESSION -->
<div class="modal fade" id="edit" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content" style="width:900px;">
            
           
                        </div><!-- /.modal-content -->
                    </div><!-- /.modal-dialog -->
                </div><!-- /.modal -->



<script>
  /* DO NOT REMOVE : GLOBAL FUNCTIONS!
     *
     * pageSetUp(); WILL CALL THE FOLLOWING FUNCTIONS
     *
     * // activate tooltips
     * $("[rel=tooltip]").tooltip();
     *
     * // activate popovers
     * $("[rel=popover]").popover();
     *
     * // activate popovers with hover states
     * $("[rel=popover-hover]").popover({ trigger: "hover" });
     *
     * // activate inline charts
     * runAllCharts();
     *
     * // setup widgets
     * setup_widgets_desktop();
     *
     * // run form elements
     * runAllForms();
     *
     ********************************
     *
     * pageSetUp() is needed whenever you load a page.
     * It initializes and checks for all basic elements of the page
     * and makes rendering easier.
     *
     */

    pageSetUp();
    
    /*
     * ALL PAGE RELATED SCRIPTS CAN GO BELOW HERE
     * eg alert("my home function");
     * 
     * var pagefunction = function() {
     *   ...
     * }
     * loadScript("js/plugin/_PLUGIN_NAME_.js", pagefunction);
     * 
     * TO LOAD A SCRIPT:
     * var pagefunction = function (){ 
     *  loadScript(".../plugin.js", run_after_loaded);  
     * }
     * 
     * OR you can load chain scripts by doing
     * 
     * loadScript(".../plugin.js", function(){
     *   loadScript("../plugin.js", function(){
     *     ...
     *   })
     * });
     */
    
    // pagefunction
    
    var pagefunction = function() {
        // clears the variable if left blank
      $('#userstable').bootstrapTable({

            });
    };
     loadScript("/bot/bootstrap-table.js");
    // end pagefunction

    // destroy generated instances 
    // pagedestroy is called automatically before loading a new page
    // only usable in AJAX version!

    var pagedestroy = function(){
        
       

        $("#userstable").bootstrapTable( 'destroy' );
        if (debugState){
            root.console.log("✔ boot table destroyed");
        } 

    }

    // end destroy
    
    // run pagefunction
    pagefunction();

</script>