<article class="col-md-8"> 
<div class="jarviswidget" id="wid-id-3" data-widget-editbutton="false" data-widget-custombutton="false">
                <!-- widget options:
                    usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">
                    
                    data-widget-colorbutton="false" 
                    data-widget-editbutton="false"
                    data-widget-togglebutton="false"
                    data-widget-deletebutton="false"
                    data-widget-fullscreenbutton="false"
                    data-widget-custombutton="false"
                    data-widget-collapsed="true" 
                    data-widget-sortable="false"
                    
                -->
                <header>
                    <span class="widget-icon"> <i class="fa fa-edit"></i> </span>
                    <h2>New user form </h2>             
                    
                </header>

                <!-- widget div-->
                <div>
                    
                    <!-- widget edit box -->
                    <div class="jarviswidget-editbox">
                        <!-- This area used as dropdown edit box -->
                        
                    </div>
                    <!-- end widget edit box -->
                    
                    <!-- widget content -->
                    <div class="widget-body no-padding">
                        
                        <?php echo $this->form()->openTag($form); ?>
                            <?php foreach ($form as $element): ?>
                                <div class="form-group">
                                    <label for="<?php echo $element->getName(); ?>" class="col-sm-2 control-label">
                                        <?php echo $element->getLabel(); ?>
                                    </label>
                                    <div class="col-sm-10">
                                        <?php echo $this->formElement($element); ?>
                                        <?php if ($this->formElementErrors($element)): ?>
                                            <div class="alert alert-danger alert-dismissable">
                                                <button type='button' class='close' data-dismiss='alert' aria-hidden='true'>&times;</button>
                                                <?php echo $this->formElementErrors($element); ?>    
                                            </div>
                                        <?php endif; ?>

                                    </div>
                                </div>
                            <?php endforeach; ?>
                            <?php echo $this->form()->closeTag($form); ?>

                    </div>
                    <!-- end widget content -->
                    
                </div>
                <!-- end widget div -->
                
            </div>
            <!-- end widget -->             
</article>









