<article class="col-sm-12 col-md-12 col-lg-12">
			
			<!-- Widget ID (each widget will need unique ID)-->
			<div class="jarviswidget" id="wid-id-1" data-widget-editbutton="false" data-widget-custombutton="false" style="margin-left:10%; margin-right:10%">
				<!-- widget options:
					usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">
					
					data-widget-colorbutton="false"	
					data-widget-editbutton="false"
					data-widget-togglebutton="false"
					data-widget-deletebutton="false"
					data-widget-fullscreenbutton="false"
					data-widget-custombutton="false"
					data-widget-collapsed="true" 
					data-widget-sortable="false"
					
				-->
				<header>
					<span class="widget-icon"> <i class="fa fa-graduation-cap"></i> </span>
					<h2>Edit Student </h2>				
					
				</header>

				<!-- widget div-->
				<div>
					
					<!-- widget edit box -->
					<div class="jarviswidget-editbox">
						<!-- This area used as dropdown edit box -->
						
					</div>
					<!-- end widget edit box -->
					
					<!-- widget content -->
					<div class="widget-body no-padding">
						<?php $form = $this->form;
			 $form->setAttribute('action', $this->url('student',array('action'=> 'edit','controller' => 'student','id'=>$this->id)));
			// $form->setAttribute('class', 'form-horizontal');
			// $form->setAttribute('readonly', 'true');
									
			//	$form->setAttribute('style', 'pointer-events: none');
            //$form->setAttribute('class', 'form-inline');

			$form->prepare(); ?>
			<?php echo $this->form()->openTag($form); ?>
			<?php $person = $form->get('student')->get('person');?>
			<?php $student = $form->get('student');?>
			<?php $guardian = $form->get('student')->get('person')->get('guardian');?>
						
							<header>Basic Information</header>

							<fieldset>
								<div class="row">
									<section class="col col-4">
										<img id="imageupload" src="<?php echo $this->basePath('img/images.png') ?>" style="width:140px; height:140px;" alt="me" /> 
											<div class="input input-file">
										<?php echo $this->formFile($student->get('image')); ?>
											 <?php echo $this->formElementErrors($student->get('image')); ?>
										</div>
										</section>

										<section class="col col-4">
											<label class="textarea"> <i class="icon-append fa fa-comment"></i>
											<?php echo $this->formTextarea($person->get('address')); ?></label>
											 <?php echo $this->formElementErrors($person->get('address')); ?>
										</section>


								<section class="col col-4">
										<label class="input"> <i class="icon-append fa fa-user"></i>
											<?php echo $this->formInput($person->get('fname')); ?>
										</label>
										 <?php echo $this->formElementErrors($person->get('fname')); ?>
									</section>

									
									<section class="col col-4">
										<label class="input"> <i class="icon-append fa fa-user"></i>
											<?php echo $this->formInput($person->get('lname')); ?>
										</label>
										 <?php echo $this->formElementErrors($person->get('lname')); ?>
									</section>
									<section class="col col-4">
										<label class="input"> <i class="icon-append fa fa-phone"></i>
											<?php echo $this->formInput($person->get('mobile')); ?>
										</label>
										 <?php echo $this->formElementErrors($person->get('mobile')); ?>
									</section>
								

									
									<section class="col col-4">
										<label class="input"> <i class="icon-append fa fa-user"></i>
											<?php echo $this->formInput($person->get('mname')); ?>
										</label>
										 <?php echo $this->formElementErrors($person->get('mname')); ?>
									</section>
								</div>
							</fieldset>

							<fieldset>
								<div class="row">
									<section class="col col-4">
										<label class="select">
											<?php echo $this->formSelect($person->get('country')); ?></label>
											 <?php echo $this->formElementErrors($person->get('country')); ?>
									</section>

									<section class="col col-4">
										<label class="select">
											<?php echo $this->formSelect($person->get('state')); ?></label>
											 <?php echo $this->formElementErrors($person->get('state')); ?>
									</section>

									<section class="col col-4">
										<label class="select">
											<?php echo $this->formSelect($person->get('lga')); ?></label>
											 <?php echo $this->formElementErrors($person->get('lga')); ?>
									</section>

									<section class="col col-4">
										<label class="select">
											<?php echo $this->formSelect($person->get('sex')); ?>
										</label>
										 <?php echo $this->formElementErrors($person->get('sex')); ?>
									</section>

									<section class="col col-4">
										<label class="input"><i class="icon-append fa fa-calendar"></i>
											<?php echo $this->formDate($person->get('dob')); ?>
										</label>
										 <?php echo $this->formElementErrors($person->get('dob')); ?>
									</section>

									<section class="col col-4">
										<label class="select">
											<?php echo $this->formSelect($person->get('religion')); ?>
										</label>
										 <?php echo $this->formElementErrors($person->get('religion')); ?>
									</section>

									<section class="col col-4">
										<label class="input"><i class="icon-append fa fa-user"></i>
											<?php echo $this->formInput($person->get('nokName')); ?>
										</label>
										 <?php echo $this->formElementErrors($person->get('nokName')); ?>
									</section>

									<section class="col col-4">
										<label class="input"><i class="icon-append fa fa-chain"></i>
											<?php echo $this->formInput($person->get('nokRel')); ?>
										</label>
										 <?php echo $this->formElementErrors($person->get('nokRel')); ?>
									</section>


									<section class="col col-4">
										<label class="input"><i class="icon-append fa fa-mobile"></i>
											<?php echo $this->formInput($person->get('nokMobile')->setAttribute('data-mask','+99 (999) 999-9999')); ?>
										</label>
										 <?php echo $this->formElementErrors($person->get('nokMobile')); ?>
									</section>

								</div>
								
							</fieldset>
					<header>Guardian Information</header>
							<fieldset>

								<div class="row">
									<section class="col col-4">
										<label class="select">
											<?php echo $this->formSelect($guardian->get('gender')); ?>
										</label>
										 <?php echo $this->formElementErrors($guardian->get('gender')); ?>
									</section>

									<section class="col col-4">
										<label class="input"><i class="icon-append fa fa-user"></i>
											<?php echo $this->formInput($guardian->get('fname')); ?>
										</label>
										 <?php echo $this->formElementErrors($guardian->get('fname')); ?>

									</section>

									<section class="col col-4">
										<label class="input"><i class="icon-append fa fa-user"></i>
											<?php echo $this->formInput($guardian->get('lname')); ?>
										</label>
										 <?php echo $this->formElementErrors($guardian->get('lname')); ?>
									</section>

									<section class="col col-4">
										<label class="input"><i class="icon-append fa fa-user"></i>
											<?php echo $this->formInput($guardian->get('mname')); ?>
										</label>
										 <?php echo $this->formElementErrors($guardian->get('mname')); ?>
									</section>
									
									<section class="col col-4">
										<label class="input"><i class="icon-append fa fa-mobile-phone"></i>
											<?php echo $this->formInput($guardian->get('mobile1')); ?>
										</label>
										 <?php echo $this->formElementErrors($guardian->get('mobile1')); ?>
									</section>	

									<section class="col col-4">
										<label class="input"><i class="icon-append fa fa-mobile-phone"></i>
											<?php echo $this->formInput($guardian->get('mobile2')); ?>
										</label>
										 <?php echo $this->formElementErrors($guardian->get('mobile2')); ?>
									</section>	

									<section class="col col-4">
										<label class="input"><i class="icon-append fa fa-envelope-o"></i>
											<?php echo $this->formInput($guardian->get('email')); ?>
										</label>
										 <?php echo $this->formElementErrors($guardian->get('email')); ?>
									</section>	


									<section class="col col-4">
										<label class="input"><i class="icon-append fa fa-briefcase"></i>
											<?php echo $this->formInput($guardian->get('occupation')); ?>
										</label>
										 <?php echo $this->formElementErrors($guardian->get('occupation')); ?>
									</section>						

				
				
					
									</div>
							</fieldset>
					<header>Academic Information</header>
							<fieldset>

								<div class="row">
									<section class="col col-4">
										<label class="select">
											<?php echo $this->formSelect($student->get('year')); ?>
										</label>
										 <?php echo $this->formElementErrors($student->get('year')); ?>
									</section>

									<section class="col col-4">
										<label class="select">
											<?php echo $this->formSelect($student->get('term')); ?>
										</label>
										 <?php echo $this->formElementErrors($student->get('term')); ?>
									</section>

									<section class="col col-4">
										<label class="select">
											<?php echo $this->formSelect($student->get('section')); ?>
										</label>
										 <?php echo $this->formElementErrors($student->get('section')); ?>
									</section>

									<section class="col col-4">
										<label class="select">
											<?php echo $this->formSelect($student->get('class')); ?>
										</label>
										 <?php echo $this->formElementErrors($student->get('class')); ?>
									</section>

									

									<section class="col col-4">
										<label class="input"><i class="icon-append fa fa-tags"></i>
											<?php echo $this->formInput($student->get('admNo')); ?>
										</label>
										 <?php echo $this->formElementErrors($student->get('admNo')); ?>
									</section>	

									<section class="col col-4">
										<label class="input"><i class="icon-append fa fa-calendar"></i>
											<?php echo $this->formDate($student->get('admDate')); ?>
										</label>
										 <?php echo $this->formElementErrors($student->get('admDate')); ?>
									</section>					

				
				
					
									</div>
							</fieldset>

							<footer>
								<?php echo $this->formRow($form->get('submit')); ?>
								
							</footer>
						
							<?php echo $this->form()->closeTag(); ?>
					</div>
					<!-- end widget content -->
					
				</div>
				<!-- end widget div -->
				
			</div>
			<!-- end widget -->


				
</article>

 <script>
  /* DO NOT REMOVE : GLOBAL FUNCTIONS!
     *
     * pageSetUp(); WILL CALL THE FOLLOWING FUNCTIONS
     *
     * // activate tooltips
     * $("[rel=tooltip]").tooltip();
     *
     * // activate popovers
     * $("[rel=popover]").popover();
     *
     * // activate popovers with hover states
     * $("[rel=popover-hover]").popover({ trigger: "hover" });
     *
     * // activate inline charts
     * runAllCharts();
     *
     * // setup widgets
     * setup_widgets_desktop();
     *
     * // run form elements
     * runAllForms();
     *
     ********************************
     *
     * pageSetUp() is needed whenever you load a page.
     * It initializes and checks for all basic elements of the page
     * and makes rendering easier.
     *
     */

    pageSetUp();
    
    /*
     * ALL PAGE RELATED SCRIPTS CAN GO BELOW HERE
     * eg alert("my home function");
     * 
     * var pagefunction = function() {
     *   ...
     * }
     * loadScript("js/plugin/_PLUGIN_NAME_.js", pagefunction);
     * 
     * TO LOAD A SCRIPT:
     * var pagefunction = function (){ 
     *  loadScript(".../plugin.js", run_after_loaded);  
     * }
     * 
     * OR you can load chain scripts by doing
     * 
     * loadScript(".../plugin.js", function(){
     *   loadScript("../plugin.js", function(){
     *     ...
     *   })
     * });
     */
    
    // pagefunction
    
    var pagefunction = function() {

    	
    };
    
   
    // end pagefunction

    // destroy generated instances 
    // pagedestroy is called automatically before loading a new page
    // only usable in AJAX version!

    var pagedestroy = function(){
        
        /*
        Example below:

        $("#calednar").fullCalendar( 'destroy' );
        if (debugState){
            root.console.log("✔ Calendar destroyed");
        } 

        For common instances, such as Jarviswidgets, Google maps, and Datatables, are automatically destroyed through the app.js loadURL mechanic

        */
    }

    // end destroy
    
    // run pagefunction
    pagefunction();
     

</script>