
	<article class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
			

							<!-- Widget ID (each widget will need unique ID)-->
							<div class="jarviswidget" id="wid-id-0">
								<!-- widget options:
									usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">
									
									data-widget-colorbutton="false"	
									data-widget-editbutton="false"
									data-widget-togglebutton="false"
									data-widget-deletebutton="false"
									data-widget-fullscreenbutton="false"
									data-widget-custombutton="false"
									data-widget-collapsed="true" 
									data-widget-sortable="false"
									
								-->
								<header>
									<h2>Add section</h2>				
									
								</header>

								<!-- widget div-->
								<div>
									
									<!-- widget edit box -->
									<div class="jarviswidget-editbox">
										<!-- This area used as dropdown edit box -->
										
										
									</div>
									<!-- end widget edit box -->
									
									<!-- widget content -->
									<div class="widget-body">
										<?php $form = $this->form;
				 $form->setAttribute('action', $this->url('section',array('action'=> 'add','controller' => 'section')));
        		 $form->setAttribute('class', 'smart-form');
        		  $form->setAttribute('role', 'form');
        		 $form->setAttribute('id', 'section');
				 $form->prepare(); ?>
				<?php echo $this->form()->openTag($form);?>
							<fieldset>
										<div class="row"> 
				                        	<section class="col col-4">
				                        		 <label class="input">
				                            <?php echo $this->formElementErrors($form->get('name')); ?>
				                            <?php echo $this->formInput($form->get('name')); ?> </label> 
				                        	</section>

				                       		 <section class="col col-5">
				                       		 	 <label class="input">
				                        	<?php echo $this->formElementErrors($form->get('shortname')); ?>
				                        	<?php echo $this->formInput($form->get('shortname')); ?> </label>   
				                        	</section>
				                        	<section class="col col-3">  
				                        	<?php echo $this->formRow($form->get('submit')); ?>           
                        					</section>
				                        	 <?php echo $this->form()->closeTag(); ?>
				                        </div>
				            </fieldset>
									</div>
									<!-- end widget content -->	
								</div>
								<!-- end widget div -->
								
							</div>
							<!-- end widget -->
</article>



 <script>
$(function() {
$( "#datepicker" ).datepicker();
			
		


				// Validation
				$("#section").validate({

					// Rules for form validation
					rules : {
						name: {
							required : true
						},
						shortname: {
							required : false
							
						},
						
					},

					// Messages for form validation
					messages : {
						name : {
							required : 'Please enter section name'
						},
						shortname: {
							required : 'Please enter a shortname'
						},
					},

					// Do not change code below
					errorPlacement : function(error, element) {
						error.insertAfter(element.parent());
					},

				});


});
</script>