
	<article class="col-xs-12 col-sm-12 col-md-8 col-lg-6">
			

							<!-- Widget ID (each widget will need unique ID)-->
							<div class="jarviswidget" id="wid-id-0">
								<!-- widget options:
									usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">
									
									data-widget-colorbutton="false"	
									data-widget-editbutton="false"
									data-widget-togglebutton="false"
									data-widget-deletebutton="false"
									data-widget-fullscreenbutton="false"
									data-widget-custombutton="false"
									data-widget-collapsed="true" 
									data-widget-sortable="false"
									
								-->
								<header>
									<h2>Edit section</h2>				
									
								</header>

								<!-- widget div-->
								<div>
									
									<!-- widget edit box -->
									<div class="jarviswidget-editbox">
										<!-- This area used as dropdown edit box -->
										
										
									</div>
									<!-- end widget edit box -->
									
									<!-- widget content -->
									<div class="widget-body">
										<?php $form = $this->form;
				
							$form->setAttribute('action', $this->url('section',array('action'=> 'editsection','controller' => 'section', 'id'=>$this->id)));
							
							$form->prepare(); ?>
							<?php echo $this->form()->openTag($form); 
							
							$section = $form->get('section'); ?>
													
				
												<section class="col-6">
													<label>Section Name</label>
													
														<?php echo $this->formInput($section->get('name')); ?>
													
												</section>
												
												
				
												<section class="col-12">
													<label class="label">Association Subjects</label>
													<div class="col-12">
														<?php echo $this->formMultiCheckbox($section->get('subject')); ?><i></i>
													</div>
												</section>
												
												<div class="form-actions">
													<div class="row">
														<div class="col-11">
													
															<?php echo $this->formRow($form->get('submit')); ?>
															<?php echo $this->form()->closeTag(); ?>
														</div>
													</div>
												</div>

									</div>
											
				
									<!-- end widget content -->	
								</div>
								<!-- end widget div -->
								
							</div>
							<!-- end widget -->
</article>



 <script>
$(function() {
$( "#datepicker" ).datepicker();

$("input").button (); $("div").buttonset ();
			
		
	

				// Validation
				$("#section").validate({

					// Rules for form validation
					rules : {
						name: {
							required : true
						},
						description: {
							required : false
							
						},
						
					},

					// Messages for form validation
					messages : {
						name : {
							required : 'Please enter section name'
						},
						description: {
							required : 'Please select a section'
						},
					},

					// Do not change code below
					errorPlacement : function(error, element) {
						error.insertAfter(element.parent());
					},

				});


});
</script>